### ISSUE TITLE
Examples for traverse_util module

### ISSUE THREAD

**Issue by n2cholas** [google/flax#1022]
First off, loving the new linen api 🎉!!!

The `traverse_util` module looks useful for manipulating parameters/state, but I could not figure out how to use it effectively (apart from `unflatten_dict` and `flatten_dict`, which are both extremely useful). The simple examples in the docs make sense, but it'd be nice to see how to use this in a real setting. Perhaps the power of this module can be illustrated in a transfer learning example, where you need to manipulate subsets of parameters?

The module seems similar to [Haiku's `data_structures`](https://dm-haiku.readthedocs.io/en/latest/api.html#module-haiku.data_structures) module, but the API seems more complex.

Also, it's unfortunate that Flax has `jax_utils` (plural) and `traverse_util` (singular). Is it too late to pluralize `traverse_util` for consistency?

**Comment by avital** [comment]
Our users mostly use `traverse_util` indirectly, via `ModelParamTraversal` that they pass into the `focus` argument to an optimizer, or via `MultiOptimizer`.

Perhaps there is a simpler and more powerful way to do it via Haiku's `data_structures`? If you've tried both I'd appreciate learning from your experience, perhaps we would also be better off using something like `data_structures` (and perhaps we could work with the Haiku team to move that out of Haiku into some shared JAX commons type place)

**Comment by jheek** [comment]
`traverse_util` isn't used much in practise. `flax.optim.ModelParamTraversal` does a similair thing compared to haiku data_stractures (map & filter)

**Comment by n2cholas** [comment]
Thanks @avital  and @jheek. It looks like I can use `flax.optim.ModelParamTraversal.update` with the identity function in order to do the filter I want (not quite sure how to do the merge, though).

[Here](https://colab.research.google.com/drive/1-0K2K8VQWwFhggtDK_2IecwhSwA89IGo?usp=sharing) is my previous project, where I'm doing transfer learning. Perhaps you can recommend a more idiomatic way to structure my code. I essentially load a pretrained ResNet, train only the head, then finetune the entire network.

Below are some relevant code snippets. In the beginning I have to partition and merge pretrained params and newly initialized params:

```python
_, backbone_vars = partition_nested_dict(
    unfreeze(pretrained_variables), 
    [('params', 'Dense_0', 'bias'), ('params', 'Dense_0', 'kernel')])

dense_vars, _ = partition_nested_dict(
    unfreeze(freshly_initialized_model_variables), 
    [('params', 'Dense_0', 'bias'), ('params', 'Dense_0', 'kernel')])

dense_params = freeze(dense_vars['params'])
model_state, backbone_params = freeze(backbone_vars).pop('params')
```

For the first stage of training, I train only the `dense_params`:

```python
state = TrainState(
    trainable_params=dense_params,
    frozen_params=backbone_params,
    opt_state=optimizer.init(dense_params),  # optax optimizer
    model_state=model_state,
    metrics=Metrics('loss', 'accuracy', 'f1'),
    step=0)
```

Later, I merge all the params into one to train them all together:

```python
all_params = freeze(merge_nested_dicts(
    unfreeze(state.trainable_params), 
    unfreeze(state.frozen_params)))

state = TrainState(
    trainable_params=all_params,
    frozen_params={},
    opt_state=optimizer.init(all_params),
    model_state=state.model_state,
    metrics=Metrics('loss', 'accuracy', 'f1'),
    step=state.step+1)
```

My training step to deal with trainable/frozen params:

```python
def train_step(batch, state):
    def loss_fn(trainable_params):
        variables = {'params': {**trainable_params, **state.frozen_params}, 
                     **state.model_state}
        logits, model_state = apply(freeze(variables), batch['image'])
        loss = criterion(logits, batch['label'])
        return loss, (logits, model_state)
    
    grad_fn = jax.value_and_grad(loss_fn, has_aux=True)
    # only compute gradients with respect to trainable parameters
    (loss, (logits, model_state)), grad = grad_fn(state.trainable_params)
		
		# optimizer updates etc...
```

I currently have helper functions to partition/merge to avoid the additional dependency on Haiku:

```python
def partition_nested_dict(d, flat_left_keys):
    left, right = {}, {}
    flat_left_keys = set(flat_left_keys)
    for k, v in flatten_dict(d).items():
        if k in flat_left_keys:
            left[k] = v
        else:
            right[k] = v
    
    return tuple(map(unflatten_dict, (left, right)))

def merge_nested_dicts(*ds):
    merged = {}
    for d in map(flatten_dict, ds):
        if any(k in merged.keys() for k in d.keys()):
            raise ValueError('Key conflict!')
        merged.update(d)
    return unflatten_dict(merged)
```

**Comment by avital** [comment]
I wonder if we should pause on this as work work through #1011 as that might lead to deprecating `traverse_util`. WDYT @n2cholas?

**Comment by n2cholas** [comment]
@avital sounds good to me!

**Comment by marcvanzee** [comment]
@n2cholas  @avital  it seems this wasn't deprecated after #1011, so shall we pick up this issue again?

**Comment by n2cholas** [comment]
@marcvanzee Sounds good! The [`MultiOptimizer`](https://github.com/google/flax/blob/78d9aa0d68a1135c6fb01834ad3846cdfc45d718/flax/optim/base.py#L444-L449) docstring example is pretty good, perhaps one more example with composing `ModelParamTraversal`s would be helpful.

On a side note, since this wasn't deprecated, does that mean flax won't fully migrate to optax optimizers?

**Comment by marcvanzee** [comment]
I think @avital suggested to remove this API all together, since most of the logic can be done with tree_maps, and all the optimizations we thought we would get with this library can mostly be handled by XLA, which does a lot of graph optimization, at the cost of more compile time.

**Comment by n2cholas** [comment]
Got it, I agree that it makes sense to remove this API altogether. I think the equivalent tree_map code is easier to understand as well. In this case, should I close this issue?

**Comment by marcvanzee** [comment]
Yes, but maybe we should create a new one for removing the traverse_util API. Since you started this issue as well, do you want to do that?
