### ISSUE TITLE
Linen upgrade guide

### ISSUE THREAD

**Issue by andsteing** [google/flax#1034]
It would be great to have a short document that explains in some detail how to
upgrade a model from the old API to the new Linen API.

**Comment by avital** [comment]
Is that not covered in the "upgrade guide" linked to from https://github.com/google/flax/tree/master/flax/linen? Is there more we're missing? Or is it hard to find this link?

**Comment by andsteing** [comment]
Yes htat is what I was looking for!

I would say it's not exactly easy to discover.

I think we want to avoid having a main RTD documentation and then a parallel Github-README documentation.

Maybe we should add a new main menu point "Linen" to RTD and add subpages there (brief intro, upgrade guide, design principles)?

Note also that we have both a Google doc [Linen Design Principles](https://docs.google.com/document/d/1ZlL_4bXCw5Xl0WstQw1GpnZqfb9JFOeUGAPcBVk-kn8) and an RTD page [Linen Design Principles](https://flax.readthedocs.io/en/latest/design_notes/linen_design_principles.html)

The bulk text about Linen we could move from the README into `docs/flax.linen.rst` so it would show up in RTD's [flax.linen package](https://flax.readthedocs.io/en/latest/flax.linen.html) description.

**Comment by avital** [comment]
I agree that we should move all docs into RTD. There are a few other stranglers, like https://github.com/google/flax/blob/master/docs/design_notes/arguments.md

I think your proposal to add a "Linen" section in RTD is good, and unify the design principles under there.

**Comment by marcvanzee** [comment]
This can be closed. Update guide is here: https://flax.readthedocs.io/en/latest/howtos/linen_upgrade_guide.html
