### ISSUE TITLE
Save and Load parameters

### ISSUE THREAD

**Issue by RodrigoAVargasHdz** [google/flax#1035]
You would like to see a new example being implemented by the Flax core team or the community? Please let us know by filling the following template.

### Description of the model to be implemented
I created a vanilla MLP trained with Adam. I will like to save the parameters into a file so I can read them for future usage. 

### Specific points to consider
How to save and load the parameters to/from a file

### Reference implementations in other frameworks

**Comment by marcvanzee** [comment]
Hi @RodrigoAVargasHdz, what is it exactly your are proposing in this issue? Do you want know how to save/load parameters to/from a file for a model you created?

**Comment by marcvanzee** [comment]
Close this since the issue is too vague.
