### ISSUE TITLE
Correct Linen Module Documentation

### ISSUE THREAD

**Issue by joelgarde** [google/flax#1039]
The example in the documentation for Linen.module uses a parameter list to hold its features:
https://github.com/google/flax/blob/master/flax/linen/module.py#L370

This is not compatible with dataclasses and trying to run the example throws a Value Error "mutable default <class 'list'> for field features is not allowed: use default_factory."

Changing from a list to a tuple (as hinted by the type annotation) would fix it.

**Comment by marcvanzee** [comment]
Thanks for finding this @joelgarde ! Do you want to file a PR fixing this isssue?

**Comment by joelgarde** [comment]
Yes, would be nice. 
I just have to sign the contributor agreement and then submit the PR?

**Comment by marcvanzee** [comment]
You should indeed sign the agreement, then send the PR for review and we can merge it once it is approved.

**Comment by joelgarde** [comment]
Thanks for the help for my first PR! 
PR is here: https://github.com/google/flax/pull/1040

**Comment by marcvanzee** [comment]
Fixed
