### ISSUE TITLE
Replace flax.optim with Optax in examples

### ISSUE THREAD

**Issue by andsteing** [google/flax#1053]
See https://github.com/google/flax/blob/master/docs/flip/1009-optimizer-api.md#update-plan

The following examples need to be updated

- [x] imagenet #1251 
- [x] mnist #1302 
- [x] nlp_seq #1916
- [x] pixelcnn #1413
- [x] ppo #1404
- [x] seq2seq #1396
- [x] vae #1361 
- [x] wmt #1476
- [x] lm1b #1479

**Comment by andsteing** [comment]
Run finished:
https://tensorboard.dev/experiment/w4PcKXloQMG7gXJhjskVjw/

- final test accuracy 0.7640
- total run time 5h4m

Compared to previous run using `flax.optim.Adam` (from `examples/imagenet/README.md`):
https://tensorboard.dev/experiment/iJzNKovmS0q6k5t6k5wvOw/#scalars&_smoothingWeight=0&regexInput=v100_x8_mixed_precision

- final test accuracy 0.7647
- total run time 4h51m

Note that the final test accuracy of the imagenet example fluctuates between 0.7625 and 0.7650, so the result is compatible.

**Comment by avital** [comment]
Nice! Where is the branch of the code that you ran that used Optax?

**Comment by andsteing** [comment]
Another finished run with the Optax code:
https://tensorboard.dev/experiment/xOpycRYnT7m3inYbEuNMxw/

- final test accuracy 0.766
- total run time 5h1m

**Comment by marcvanzee** [comment]
Updated the checklist since PixelCNN++ doesn't exist anymore.
