### ISSUE TITLE
NN DeprecationWarning

### ISSUE THREAD

**Issue by philippeller** [google/flax#1064]
When `from flax import linen as nn` I get the following deprecation warning:

```DeprecationWarning: The `flax.nn` module is Deprecated, use `flax.linen` instead. Learn more and find an upgrade guide at https://github.com/google/flax/blob/master/flax/linen/README.md```

Under that link I find that instead of the old `from flax import nn` I should use  `from flax import linen as nn` - which is what I was doing in the first place!

This warning is very confusing and should only be thrown when the _old_ way is being used.

**Comment by avital** [comment]
Hi @philippeller -- sorry for that, the 0.3.2 upload to pypi is stalled on GitHub actions: https://github.com/google/flax/actions/runs/610119419

Can you confirm that `pip install --upgrade git+https://github.com/google/flax.git` resolves the problem for you?

I'll get the build out shortly.

**Comment by avital** [comment]
OK -- 0.3.2 [is released](https://pypistats.org/packages/flax). I have verified that `from flax import linen as nn` doesn't lead to an error there. (And on v0.3.1 it did).

**Comment by philippeller** [comment]
Great! Can confirm that with the updated version it doesn't show the warning anymore :+1:

**Comment by avital** [comment]
👍
