### ISSUE TITLE
Extend examples/imagenet/ with illustration of fine-tuning

### ISSUE THREAD

**Issue by andsteing** [google/flax#1065]
Something along the lines : download pretrained resnet, replace head with a new initialized head, train first head, then whole network.

This would illustrate some model surgery & multi optimizer.

**Comment by andsteing** [comment]
See also related issue #1022

**Comment by marcvanzee** [comment]
Nice idea! Maybe we can consider doing a HOWTO and marge this issue with #789?

**Comment by marcvanzee** [comment]
This seems to be duplicate of #1567.
