### ISSUE TITLE
HOWTO use nn.apply and bind

### ISSUE THREAD

**Issue by jheek** [google/flax#1087]
It would be good to have a howto explaining the various patterns involved in using nn.apply and bind.
In particular:

- HOWTO combine apply with transforms (and why you should probably always jit the init/apply)
- HOWTO rewrite usage of bind to apply
- HOW-NOT-TO combine jax transforms with Modules (eg. jit+bind) and closure over modules.

**Comment by marcvanzee** [comment]
Closing this in favor of https://github.com/google/flax/issues/2116.
