### ISSUE TITLE
flax.training.checkpoint.save_checkpoint with keep=1 leads to "file already exists" error

### ISSUE THREAD

**Issue by AlexiaJM** [google/flax#1091]
I'm using Jax latest, Tensorflow latest, Jaxlib 0.1.59.

Let say I run a python code which does a save_checkpoint with keep=1 once. Then, I rerun the python code again, it will give me a "tensorflow.python.framework.errors_impl.AlreadyExistsError: file already exists". This is really annoying because this means that I have to manually delete the checkpoints if I want to reuse the same python code which happens a lot when debugging. 

I think that this happens because the extra files are only deleted at the end of save_checkpoint.

>  File "/localscratch/jolicoea.63359842.0/1/ScoreSDEMore/run_lib.py", line 469, in evaluate
>     checkpoints.save_checkpoint(
>   File "/localscratch/jolicoea.63359842.0/1/env/lib/python3.8/site-packages/flax/training/checkpoints.py", line 99, in save_checkpoint
>     gfile.rename(ckpt_tmp_path, ckpt_path)
>   File "/localscratch/jolicoea.63359842.0/1/env/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 548, in rename_v2
>     _pywrap_file_io.RenameFile(
> tensorflow.python.framework.errors_impl.AlreadyExistsError: file already exists

**Comment by AlexiaJM** [comment]
There could be an option called "overwrite" which defaults to False.

**Comment by jheek** [comment]
We could add an overwrite option. But I think the current implementation has more issues when you reuse the same checkpoint directory. It might also store let's say at step 10 while you also have a checkpoint at step 100 leading to the new checkpoint at step 10 to be removed.
