### ISSUE TITLE
pixelcnn.py: README is outdated and bug in dataset downloading

### ISSUE THREAD

**Issue by brettkoonce** [google/flax#1114]
python3 main.py --workdir=./pixelcnn --config=configs/default.py

fails on

    TypeError: __init__() got an unexpected keyword argument 'deterministic'

rolling back #683:

     git reset --hard feb9119d76b0e23d89670ba752caa414c5a7ade2

works again.  ping @jheek

**Comment by marcvanzee** [comment]
Thanks @brettkoonce for catching this! I can fix this today.

**Comment by brettkoonce** [comment]
per discussion in #1122, upgrading to 0.3.2 fixes this, closing!

**Comment by marcvanzee** [comment]
Actually I tried running it and it didn't work since the dataset wasn't downloaded. Also the README instructions were outdated, so I'm reopening and attaching a PR that fixes it.

**Comment by brettkoonce** [comment]
kk, i had something similar in https://github.com/brettkoonce/flax/commit/84faadf6070b9df5aebcc29562ee063ab864badf, but yours is fancier!
