### ISSUE TITLE
Add an explicit error message when trying to set Module.name

### ISSUE THREAD

**Issue by marcvanzee** [google/flax#1139]
From @avital : 

Maybe we should also make a separate explicit error for when you try to assign to module.name
Looks like this comes up pretty regularly, and this leads to a different need than the more general "module instances are frozen"

**Comment by melissatan** [comment]
I can pick this up, but would like to better understand the context. Currently
```
model = nn.Dense(features=5, name="a")
print(model.name)
model.name = "b"
print(model.name)
```
results in
```
a
b
```
Is that behavior not desired? Or is this issue obsolete?

**Comment by marcvanzee** [comment]
Hmm maybe this was resolved already? Changing the top-level Module name should not matter (it is not part of the param tree anyway), and if you change the name of a submodule then this is caught by an error already, e.g.:

```py
class Foo1(nn.Module):
  @nn.compact
  def __call__(self, x):
    self.name = "bar"  # Throws an error
    ...

class Foo2(nn.Module):
  def setup(self):
    self.name = "bar"  # Throws an error

  def __call__(self, x):
    ...
```

@jheek @levskaya  do you have more context on this?

**Comment by melissatan** [comment]
As discussed offline issue is obsolete so closing.
