### ISSUE TITLE
np.array parameters may lead to a silent failure

### ISSUE THREAD

**Issue by akolesnikoff** [google/flax#1157]
Passing np.array parameters (instead of jnp.array) to a linen module may lead to a silent failure, see the following example:

```
import flax.linen as nn

import jax
import jax.numpy as jnp

import numpy as np

t = jnp.zeros([2, 196], jnp.int32)
print(f'Input shape: {t.shape}')

m = nn.Embed(32, 10)
rng = jax.random.PRNGKey(0)
vars = m.init(rng, t)
o1 = m.apply(vars, t)
print(f'Expected output shape: {o1.shape}')

o2 = m.apply(jax.tree_map(np.array, vars), t)
print(f'Numpy output shape: {o2.shape}')
```

Output:

```
Input shape: (2, 196)
Expected output shape: (2, 196, 10)
"Numpy params" output shape: (196,)  <-- Different output shape
```

**Comment by marcvanzee** [comment]
Thanks for catching this!

When you map the embedding to an `np.array`, what will happen when applying the `Embed` module is that the embedding (which is now a Numpy array) is indexed with a `jax.numpy` array. This causes Numpy to treat the `jnp.array` as a tuple, which is not what we want:

```python
embedding = jnp.array([[1], [2]])
idx = jnp.array([0], jnp.int32)

embedding[idx]  # Similar to your o1 -- correct
>>> [[1]]

np.array(embedding)[idx]  # Similar to o2 -- wrong
>>> [1]
```

We can verify the `jnp` is cast incorrectly by changing its type:

```python
np.array(embedding)[tuple(idx)]
>>> [1]

np.array(embedding)[np.array(idx)]
>>> [[1]]
```

Actually this also throws a Deprecationwarning, suggesting we should explicitly cast the index to either np.arr or tuple.

So I think we can do two things:

1. Force the embedding to be a jnp array (and not a numpy array)
2. Check whether the embedding is a np array, and if so, explicitly cast the indexer to np.array.

**Comment by jheek** [comment]
I think we want to use `jnp.asarray` here to avoid unnecessary copies but guarantee that the embedding is a jax numpy array.

**Comment by marcvanzee** [comment]
@jheek I think that may still break if the params aren't jax numpy arrays, which can happen if you load weights from a file. See also #1261.
