### ISSUE TITLE
Surprising behaviour for integer kernel_size in linen.Conv 

### ISSUE THREAD

**Issue by relational** [google/flax#1234]
I was quite surprised with how `linen.Conv` treats `int` as an argument for `kernel_size`

```
key1, key2 = jax.random.split(jax.random.PRNGKey(0), 2)
image = jax.random.normal(key1, (8, 256, 256, 3))
conv = flax.linen.Conv(features=48, kernel_size=5)
params = conv.init(key2, image)
```

This errors on the last line with
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
google3/third_party/py/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     55     try:
---> 56         return getattr(obj, method)(*args, **kwds)
     57 

AttributeError: 'tuple' object has no attribute 'take'

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
11 frames
google3/third_party/py/numpy/core/fromnumeric.py in _wrapit(obj, method, *args, **kwds)
     44     except AttributeError:
     45         wrap = None
---> 46     result = getattr(asarray(obj), method)(*args, **kwds)
     47     if wrap:
     48         if not isinstance(result, mu.ndarray):

IndexError: index 3 is out of bounds for size 3
```

And I can see it creates a kernel for only 1 spatial dimension.

So it seems it says `5 == (5,)`

Changing to `conv = flax.linen.Conv(features=48, kernel_size=(5,5))` fixes the error.

Overall I find:
a) the error is cryptic
b) if this is the desired behaviour, perhaps it should only accept kernel_size as a sequence of ints?

**Comment by marcvanzee** [comment]
Your input is of shape `(8, 256, 256, 3)`, and when you specify a 1D kernel you are applying a 1D convolution. This doesn't work on your input shape, which expects 2D convolutions (your have 2 spatial dimensions). So you can fix this by reducing your input to one special dimension:

```python
from flax import linen as nn
import jax

key1, key2 = jax.random.split(jax.random.PRNGKey(0), 2)
image = jax.random.normal(key1, (8, 256, 4))
conv = nn.Conv(features=48, kernel_size=3)
params = conv.init(key2, image)
```

Closing this for now but please re-open if you think I missed something!

**Comment by levskaya** [comment]
I think we want to keep this open as we want to get rid of flax's magic integer --> tuple conversion here
