### ISSUE TITLE
Add HOWTO: Early Stopping

### ISSUE THREAD

**Issue by avital** [google/flax#1239]
We recently merged https://github.com/google/flax/pull/711, which gives a simple non-(inversion of control) API for early stopping in a user-defined training loop.

It would be good to showcase a HOWTO with side-by-side diffs like in https://flax.readthedocs.io/en/latest/howtos/lr_schedule.html showcasing how this would be integrated into a real (sample) training loop.

**Comment by ayush-1506** [comment]
@avital I'm not sure how early stopping is working here. The API example [here](https://github.com/google/flax/issues/728#issuecomment-749454920) says that `early_stop.update` returns a bool, but the implementation [here](https://github.com/google/flax/blob/master/flax/training/early_stopping.py#L58) returns a tuple. Am I missing something?

**Comment by thomkeh** [comment]
Duplicate of #886?

**Comment by avital** [comment]
Thanks @thomkeh -- yes, this is a dupe of #886
