### ISSUE TITLE
Re-used BatchNorm layer with named axis can't be initialised in train mode

### ISSUE THREAD

**Issue by JamesAllingham** [google/flax#1250]
### Problem you have encountered:

When trying to initialise a model with a re-used `BatchNorm` layer a failure occurs when `use_running_average=False` and I've set a named axis (e.g. `axis_name="batch"`). Here is a minimal example which will fail:

```
class TestNet(nn.Module):
    @nn.compact
    def __call__(self, x, train: bool = True):
        norm = nn.BatchNorm(
            name="norm",
            use_running_average=not train,
            momentum=0.9,
            epsilon=1e-5,
            axis_name="batch"
        )

        for _ in range(2):
            x = norm(x) 

        return x

key = random.PRNGKey(0)
model = TestNet()
variables = model.init(key, jnp.ones((10,)))
```

### What you expected to happen:

I'd expect the initialization to be successful since this works if any of these three conditions are not met:
1. `use_running_average=False`,
2. there is a named axis, and
3. the `BatchNorm` layer is not reused. 

Instead, I get the following error...

### Logs, error messages, etc:

```
NameError: unbound axis name: batch. The following axis names (e.g. defined by pmap) are available to collective operations: []
```

### Steps to reproduce:
Here is a Colab to reproduce the failure as well as successful cases when any of the conditions above are not met: https://colab.research.google.com/drive/1N7Wk6eUdW4UO6Ckj_tUscDhOlO0DtY0P?usp=sharing&forceEdit=true&sandboxMode=true

Please let me know if I can clarify anything!

**Comment by jheek** [comment]
This is indeed a known bug and it has existed for a long time I'm working on a fix now.

The reason why it hasn't been fixed before is that re-using a BatchNorm layer is rarely the correct behaviour because two inputs share batch statistics even if they aren't i.i.d..

**Comment by JamesAllingham** [comment]
Yeah, to be honest, posting this issue did make me think carefully about whether what I was doing was reasonable – and I am still not too sure! But I thought that it would be worth fixing since it took me a while to figure out what the problem actually was. My use case is a little more complicated than this minimal example and the error message didn't immediately make it clear what I was doing wrong (but did point me in the right direction :)). Hopefully, this saves someone else the time to figure it out.

Thanks for the quick fix!

**Comment by jheek** [comment]
Your example is a nice minimal repro indeed. But just be aware that composing BN doesn't really make sense because the output of BN is mean 0 std 1 so for the iid assumption to hold your original input should also be mean 0 std 1 but if that were true than why are you using BN in the first place because it acts as a no-op
