### ISSUE TITLE
Pip installing from source throws an error 

### ISSUE THREAD

**Issue by yashs97** [google/flax#1271]
I created a fresh miniconda environment and followed the steps in How to Contribute documentation (https://flax.readthedocs.io/en/latest/contributing.html).
Installing from my fork (Step 4) returns the below error : 

```
(flax) ➜  flax git:(master) pip install -e . .[testing]
zsh: no matches found: .[testing]
```

**Comment by yashs97** [comment]
Ah for zsh, the square brackets must be escaped(:
`pip install -e  .\[testing]\` (removes the extra dot)
Also FYI,  python. version must be <=3.7 for the. requirement `tensorflow-cpu>=2.4.0` to. be satisfied.
Let me know if this info should be included in the documentation

**Comment by jheek** [comment]
I created a PR that should fix the instructions for zsh.

>>Also FYI, python. version must be <=3.7 for the. requirement tensorflow-cpu>=2.4.0 to. be satisfied.
Let me know if this info should be included in the documentation

This I'm not sure about? From what I can see tensorflow-cpu should be supported for 3.6 to 3.8?

**Comment by yashs97** [comment]
> This I'm not sure about? From what I can see tensorflow-cpu should be supported for 3.6 to 3.8?

Yeah you're right about that, I was using 3.9. My bad!
