### ISSUE TITLE
flax.errors.ScopeParamNotFoundError: No parameter named "kernel" exists in "/Conv_0".

### ISSUE THREAD

**Issue by Haxxardoux** [google/flax#1303]
`Model.apply({'params':params}, batch)` in the loss function seems to throw the error above. I pretty much followed the examples in the docs line-by-line with no luck.

Here is a minimal example of the issue reproduced in google colab - https://colab.research.google.com/drive/12mRim_N4cWmv4nmeuknq8RT2VWUA5egB

**Comment by andsteing** [comment]
you wrote

```
parameters = SimpleCNN6Layer(n=16).init({'params':jax.random.PRNGKey(0)}, jax.numpy.ones((16, 4000, 1)))
optimizer = optim.Adam(learning_rate=3e-4).create(parameters)
```

but you probably meant

```
variables = SimpleCNN6Layer(n=16).init({'params':jax.random.PRNGKey(0)}, jax.numpy.ones((16, 4000, 1)))
optimizer = optim.Adam(learning_rate=3e-4).create(variables['params'])
```

**Comment by marcvanzee** [comment]
You have to make sure you take the `params` of the variable dict returns by `init`. So when you create your optimizer you should do:

```
variables = SimpleCNN6Layer(n=16).init({'params':jax.random.PRNGKey(0)}, jax.numpy.ones((16, 4000, 1)))
optimizer = optim.Adam(learning_rate=3e-4).create(variables['params'])
```

The error message is not very clear, so thank you for bringing this up! 👍 

We should consider improving the error message to something like "Maybe you passing in an incorrect variable dict"?

**Comment by marcvanzee** [comment]
Wow, @jheek beat me to it with an identical code snippet 😄

**Comment by andsteing** [comment]
hah you clearly spent that 1 minute on a much better explanation !

👍  👍  👍

**Comment by melissatan** [comment]
Additionally discovered that the example snippet in the docs for ScopeParamNotFoundError no longer seems to work, but with a different error than ScopeParamNotFound. Will update it.
