### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by bastings** [google/flax#1308]
In line with https://github.com/github/renaming it'd be good to rename the default branch to "main".

**Comment by bastings** [comment]
Could we make a list of things that need to make done so that nothing breaks? Any integrations?

- [ ] Read the docs

**Comment by avital** [comment]
I added two things that came to mind. Maybe @marcvanzee @andsteing or @jheek have thoughts for more. Also looks like GitHub retains the old branch names (printing a warning when you use them) so I don't think things will break...

**Comment by marcvanzee** [comment]
I also added two things that came to mind!

**Comment by levskaya** [comment]
I believe we've switched everything over at this point.  The only remaining occurrences of `master` in the repo are references to external repository branches.  I'll tentatively close this issue, please feel free to re-open if we've missed something.
