### ISSUE TITLE
AttributeError: module 'flax.linen' has no attribute 'merge_param'

### ISSUE THREAD

**Issue by n2cholas** [google/flax#1319]
[This guide](https://flax.readthedocs.io/en/latest/design_notes/arguments.html) suggests using `nn.merge_param` to combine arguments, but `merge_param` is only available through `nn.module.merge_param`. I believe it needs to be added to the import line [here](https://github.com/google/flax/blob/4ae9143f7ef46ffab6d9123ba1b2e4f3303e68d1/flax/linen/__init__.py#L28). I can open a PR if this is the case.

**Comment by jheek** [comment]
Good catch! Please do open that PR
