### ISSUE TITLE
lm1b sampler update is out of bound?

### ISSUE THREAD

**Issue by thisiscam** [google/flax#1322]
Hi,

_Disclaimer: I'm not confident if this is some intended behavior._

I think in the lm1b example, the prediction sampler could write to indices out of bound of the result.
The particular offending line is:  https://github.com/google/flax/blob/master/examples/lm1b/temperature_sampler.py#L109.

Since `i <= max_decode_len` according to https://github.com/google/flax/blob/master/examples/lm1b/temperature_sampler.py#L75, and since `prompt_inputs.shape[1] == max_decode_len`, the last iteration (or two iterations?) of while loop would overwrite to `prompt_inputs[..., max_decode_len - 1]` (due to XLA semantics). 

It's either a subtle bug (it won't raise cause error), or there's something I'm not understanding about the sampling procedure.

**Comment by marcvanzee** [comment]
Hmm yes, this code looks a bit odd to me. It seems we should stop 2 iterations earlier, so `not_at_end` should be defined as follows:

```python
not_ at_end = (i < max_decode_len - 1)
```

@levskaya who I think wrote this code: what do you think of this?

**Comment by marcvanzee** [comment]
Reassigning to @zaxtax who will take a look at this problem.
