### ISSUE TITLE
Make documentation examples runnable without changes

### ISSUE THREAD

**Issue by n2cholas** [google/flax#1325]
UPDATE: Updated title based on discussion to make examples runnable without changes as opposed to just including imports.

Many of the self contained examples in the documentation do not include imports, which can make getting started tough for new users. For example, many examples use `nn.Module`, and a new user may try `from flax import nn` instead of `import flax.linen as nn` when trying to run the example on their own.  I think all _standalone_ snippets should include all necessary imports, so one can simply paste the example and run.

Here's an initial list of examples I think could use imports:

- All the readme examples (these are quite inconsistent, e.g. [this](https://github.com/google/flax/blame/master/README.md#L101) line uses `Dense` directly instead of `nn.Dense`)
- [Managing Parameters and State](https://flax.readthedocs.io/en/latest/howtos/state_params.html)
- [Extracting Intermediates](https://flax.readthedocs.io/en/latest/howtos/extracting_intermediates.html)
- [Model Surgery](https://flax.readthedocs.io/en/latest/howtos/model_surgery.html)
- [Module.bind](https://flax.readthedocs.io/en/latest/flax.linen.html#flax.linen.Module.bind)
- [Module.sow](https://flax.readthedocs.io/en/latest/flax.linen.html#flax.linen.Module.sow)

I noticed Flax uses doctest to ensure examples in the documentation run, is there any way to mark/enforce that certain examples are self-contained (i.e. have the required imports)? 

cc @8bitmp3

**Comment by 8bitmp3** [comment]
What do you think about doctests with `pytest`? https://github.com/google/jax/pull/6330/files by @jakevdp, and also this https://github.com/google/jax/pull/2994/files @avital @andsteing

**Comment by andsteing** [comment]
Actually, these examples are run with the Sphinx [doctest extension](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html):

https://github.com/google/flax/blob/491ce18759622506588784b4fca0e4bf05f8c8cd/docs/conf.py#L54

Maybe we should transform the `testsetup` blocks into `testcode` blocks so the imports are shown in the docs as well?

@n2cholas would you really want every snippet to contain all the imports or would it be enough to have a list of imports at the top of the file? The first might be a bit too verbose and it should be easy enough to copy the imports from the same page when copying the snippet...

As for `from flax import nn` - @avital why don't we currently have a deprecation warning on import? Because that indeed seems like a thing a beginner would do, and it might be rather confusing to have to discover that "Linen is the new nn".

**Comment by n2cholas** [comment]
@andsteing I think the top of the file would do for the longer examples.

When I was opening this issue, I was mostly motivated by the code snippets in docstrings, e.g. for `linen.scan`, adding the imports + some other boilerplate made the docstring example easier to work with (dc78886b46a0e1bc918aa7fb9fb07d8d6e27e317). Similarly, for [`Module.bind`](https://flax.readthedocs.io/en/latest/flax.linen.html#flax.linen.Module.bind), I think adding the imports and one more line to actually create the variables makes it a stand alone example, copy-paste-run example.

Perhaps this issue should be named "make doc string code snippets runnable".

**Comment by andsteing** [comment]
I think it's great if we can extend our pydoc examples to make them runnable. So whenever you see snippets where something is missing, feel free to open PRs to extend/fix them...

(Even better would be to have something similar to doctest to run them automatically as part of `pytest`)

**Comment by n2cholas** [comment]
Cool, I'd be happy to open PRs for the specific links I mentioned. 

Would it ok to keep this issue open until we can figure out how to run specific docstring code snippets as a part of pytest? In my view, this should be the default, so new docstrings must be runnable unless there is a reason not to (e.g. too much boilerplate).

**Comment by n2cholas** [comment]
@andsteing I noticed the examples include `testsetup::` code, is there any way to make this (optionally) visible in the documentation webpage? Perhaps under a dropdown, e.g. below is the setup from [extracting intermediates](https://github.com/google/flax/blob/master/docs/howtos/extracting_intermediates.rst):

# Extracting intermediate values
<details>
  <summary>Setup code</summary>
  
```py
import flax.linen as nn
import jax
import jax.numpy as jnp
from flax.core import FrozenDict
from typing import Sequence

batch = jnp.ones((4, 32, 32, 3))
```
  
</details>

[then rest of example]

**Comment by avital** [comment]
> testsetup:: code, is there any way to make this (optionally) visible in the documentation webpage? Perhaps under a dropdown

@n2cholas -- That would be awesome if we could pull it off. I guess we'd need to make a plugin for Sphinx?

**Comment by avital** [comment]
> As for from flax import nn - @avital why don't we currently have a deprecation warning on import?

It's because we re-export `flax.nn` in `flax/__init__.py` so that `import flax` `flax.nn.<...>` works. But that seems like a bad answer. We should get rid of that, but honestly it's probably time to remove `flax.nn`.

**Comment by andsteing** [comment]
Note that #1910 proposes to include links to Colabs for all HOWTOs. That way the HOWTOs themselves would be short and easy to read (i.e. without all the setup code), but users would only be one link away from a full Colab that contains all the code and runs it on some actual data.

(Of course with the disadvantage that the two files need to be kept in sync)

**Comment by marcvanzee** [comment]
@n2cholas: @cgarciae and I are thinking to auto-generate Colabs from the HOWTOs, and include a "Open in Colab" button above each HOWTO. I believe this would solve your problem here, since if users would like to copy/paste code they can just go to the Colab.

I am therefore thinking we can close this issue in favor of #1910, what do you think?

**Comment by n2cholas** [comment]
@marcvanzee sounds good, thank you!
