### ISSUE TITLE
UserWarning: enable_omnistaging() is a no-op in JAX versions 0.2.12 and higher

### ISSUE THREAD

**Issue by rohit901** [google/flax#1341]
### Problem you have encountered:

I just started out with Flax and was following this tutorial [here](https://flax.readthedocs.io/en/latest/notebooks/flax_basics.html), by running it on Google Colab, but I'm getting this warning after running the second code cell, i.e

```
import jax
from typing import Any, Callable, Sequence, Optional
from jax import lax, random, numpy as jnp
import flax
from flax.core import freeze, unfreeze
from flax import linen as nn

from jax.config import config
config.enable_omnistaging() # Linen requires enabling omnistaging
```
The warning is:

> UserWarning: enable_omnistaging() is a no-op in JAX versions 0.2.12 and higher

I do not understand what does that means, could someone please explain what implication does this warning has / what is actually happening? I apologize if this is not the right place to ask this.

**Comment by marcvanzee** [comment]
Omnistaging is relatively new in JAX, and for some time it was disabled by default. Linen requires it to be enabled, so we had to enabled it manually. Currently, omnistaging is enabled by default, so we no longer have to manually enable it. However we forgot to remove it in this Colab.

The bottom line is: we should remove the last two lines from the Colab. Do you want to file a PR for this?

**Comment by rohit901** [comment]
Sure, I can try doing that if you want

**Comment by jheek** [comment]
I already did a quick search-and-replace so you don't have to bother ;)

**Comment by rohit901** [comment]
Thank you for the help :) maybe then this issue can be closed, thank you for making it clear.
