### ISSUE TITLE
how to change this torch to flax?

### ISSUE THREAD

**Issue by lu-ming-lei** [google/flax#1373]
optimizer = torch.optim.Adam([variable1, variable2], 0.001)

how to change this torch to flax?

I try this but no success:  optimizer = flax.optim.Adam([variable1, variable2], 0.001)

**Comment by joaogui1** [comment]
Hey @lu-ming-lei can you provide a longer code snippet? In Flax we don't pass the variables we want to optmize when initialising the optimizer

**Comment by lu-ming-lei** [comment]
optimizer = torch.optim.Adam([
  {'params': variables1, 'lr':0.1},  
   {'params': variables2, 'lr':0.01}, 
  ])
how to change this code into flax?
