### ISSUE TITLE
Review and update all TFDS pipelines to use modern splitting API.

### ISSUE THREAD

**Issue by levskaya** [google/flax#138]
As noted in #136 the lm1b example we're still using the deprecated TFDS splitting API, we should review and update all of our pipelines to use the modern version.  This is the tracking issue for those fixes.

**Comment by AlexeyG** [comment]
Marking this as PRs welcome, however, we will need to verify that with the new API we get the same results. So the PR should include TensorBoard logs on 8x V100 (see `README.md` of `examples/lm1b` for expected results).

**Comment by avital** [comment]
@andsteing Do you know if we've already made this update in the Linen examples?

**Comment by levskaya** [comment]
Closing this issue as none of the existing linen examples still use the old tfds subsplit API.
