### ISSUE TITLE
Bad magic number error when following huggingface setup TPU totorial

### ISSUE THREAD

**Issue by BirgerMoell** [google/flax#1405]
I followed the huggingface tutorial for setting up a repo for huggingface
https://github.com/huggingface/transformers/tree/master/examples/research_projects/jax-projects#how-to-install-relevant-libraries

```
pip install "jax[tpu]>=0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
```

```
import jax
jax.device_count()
```

### Problem you have encountered:
I get a bad magic number error

### What you expected to happen:
Get a device count

### Logs, error messages, etc:
python3 jax-setup.py 
Traceback (most recent call last):
  File "jax-setup.py", line 1, in <module>
    import jax
ImportError: bad magic number in 'jax': b'\x03\xf3\r\n'

### Steps to reproduce:
Whenever possible, please provide a *minimal example*. Please consider submitting it as a Colab link.

pip install "jax[tpu]>=0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html

import jax
jax.device_count()

**Comment by avital** [comment]
Did you maybe first run with python2 and then python3? You'll need to delete your `.pyc` files.

**Comment by BirgerMoell** [comment]
Yes, I did that by accident, where is the.pyc file located?

**Comment by BirgerMoell** [comment]
I deleted the jax.pyc file and now it's working! Thanks for the incredibly quick help!
