### ISSUE TITLE
Example request for teacher-student / distillation style network training (e.g. BYOL, dino, etc.)

### ISSUE THREAD

**Issue by jennyjin19** [google/flax#1417]
You would like to see a new example being implemented by the Flax core team or the community? Please let us know by filling the following template.

### Description of the model to be implemented
teacher-student style network training (momentum update of student weights to teacher) which is widely used in self-supervised training 

### Dataset the model could be trained on
any dataset, e.g. ImageNet, cifar, etc. 

### Reference implementations in other frameworks
BYOL: https://github.com/deepmind/deepmind-research/tree/master/byol
dino: https://github.com/facebookresearch/dino

**Comment by marcvanzee** [comment]
Thanks for filing this issue! We decided that for now, we want to focus on making our core library excellent, and we are not planning to add new examples to our repo. This may change in the future, but for now I am closing this issue.

We do encourage you to let us know (e.g., through Github Discussions) when you have written examples in your own repo, and we gladly link to it!

@andsteing FYI
