### ISSUE TITLE
Module Interceptor.

### ISSUE THREAD

**Issue by zpolina** [google/flax#1436]
This FLIP discusses adding a new module interceptor API into calls to Flax modules to add functionality for various purposes. For example, interceptors would make it possible to change the input of a Module call or to perturb its output. Interceptors can also be used to access or modify the gradients that pass through a Module and expose those.

**Comment by marcvanzee** [comment]
@jheek ended up implementing custom solution that did not involve hooks, and shared it offline. I am therefore closing this issue.

**Comment by nova77** [comment]
@marcvanzee this is not super helpful. How does this custom solution work?
I still believe a module interceptor would be very valuable.
