### ISSUE TITLE
Automatic Speech Recognition Example Request

### ISSUE THREAD

**Issue by ckt624** [google/flax#1449]
You would like to see a new example being implemented by the Flax core team or the community? Please let us know by filling the following template.

### Description of the model to be implemented
RNN-Transducer

### Dataset the model could be trained on
LibriSpeech

### Reference implementations in other frameworks
https://github.com/mlcommons/training/tree/master/rnn_speech_recognition/pytorch

**Comment by marcvanzee** [comment]
Thanks for filing this issue! We decided that for now, we want to focus on making our core library excellent, and we are not planning to add new examples to our repo. This may change in the future, but for now I am closing this issue.

We do encourage you to let us know (e.g., through Github Discussions) when you have written examples in your own repo, and we gladly link to it!

@andsteing FYI
