### ISSUE TITLE
Add flax logo in SVG format

### ISSUE THREAD

**Issue by ghosh-r** [google/flax#1454]
Hi,

It would be really helpful if you add a logo for the Flax library.

A similar request was made for JAX [here on Issue#4389](https://github.com/google/jax/issues/4389) and was granted in [this commit](https://github.com/google/jax/commit/ebf7c1b6127d6df3a64a4d969297ca70e126a341).

It would be really helpful to have an official Flax logo.

**Comment by andsteing** [comment]
@8bitmp3 who was working on the SVG logo recently IIRC

**Comment by marcvanzee** [comment]
@8bitmp3 @avital Do you perhaps have the logo in SVG format?

**Comment by 8bitmp3** [comment]
Nice @levskaya 👍
