### ISSUE TITLE
jax.jit causes type error

### ISSUE THREAD

**Issue by INF800** [google/flax#1492]
I used annotated mnist notebook for cifar10 dataset. Removing `@jax.jit` decorator for `train_step` and `eval_step` runs everything fine (but slow).

But keeping the decorator (as in annotated MNIST example) raises following error:
```python
TypeError: Argument '[b'test_09933' b'test_05669' b'test_00163' ... b'test_03829' b'test_08858'
 b'test_04202']' of type <class 'numpy.ndarray'> is not a valid JAX type.
```

Error is reproducible in this notebook: https://colab.research.google.com/drive/1T4qJ-nxvYZsVMzA8NZJ7ZdFtC92RiaYO?usp=sharing

Note that `train_step` without decorator runs perfectly but `eval_step` with decorator terminates with error

**Comment by INF800** [comment]
Does it have something to do with `# TODO(necula): this duplicates code in core.valid_jaxtype`? May be type check with `core.valid_jaxtype` will not cause this error?

**Comment by andsteing** [comment]
You can fix this error with `del test_ds['id']`
