### ISSUE TITLE
New Training and Evaluation API

### ISSUE THREAD

**Issue by manifest** [google/flax#1503]
This FLIP discusses a new Training and Evaluation API.

**Comment by marcvanzee** [comment]
Hello @manifest, many apologies for not replying to this, I suppose it got burried!

* Your `Checkpoint` abstraction seems very useful, and in fact @andsteing implemented something similar called `TrainState`, which we now use in all of our examples.
* Your abstractions `TrainLoop` and `EvalLoop` really go against the [Flax Philosophy](https://flax.readthedocs.io/en/latest/advanced_topics/philosophy.html) quite a bit. Generally we try to avoid inversion of control. While this is unavoidable in general, we really want the user to own their training loop and evaluation loop. This avoids creating abstractions with many parameters, which lead to a lot of confusion and maintenance burden.
* Your summary writing and logging ideas are very nice! We are currently using `tensorboard.SummaryWriter` and `clu.metric_writers` in our examples, which seem to have roughly similar functionality.

So overall I think we cannot realistically continue with this FLIP. You are proposing a new API on top of Flax that is no longer functional. I do think that many users would be very happy with such an API, and I would encourage you to write it on top of Flax, but then in a separate repository. 

Again, thanks for writing this up and sorry for not being able to give you better news.
