### ISSUE TITLE
Training Imagenet Example when restoring from checkpoint fails with ValueError

### ISSUE THREAD

**Issue by Nils-Hoffmann** [google/flax#1550]
When optimizer state is restored from a checkpoint the resulting state has different flax.serialization types instead of the expected optax ones. Gradient application works fine with these types [but the conditional application of new optimizer state using tree_map in the example ](https://github.com/google/flax/blob/d098f2514d008ac5798fa5ad1e09a18485d4188e/examples/imagenet/train.py#L155) fails with a ValueError due to different types.

[Minimal Example Colab](https://colab.research.google.com/drive/1Y3HZ830ukugyII8AeRWMTsWCGMZE6N9a?usp=sharing)

**Comment by andsteing** [comment]
This was fixed in #1432 ... which is not yet included in the latest release - expect that to be updated soon

In the meantime you can fix it by install `flax` from head: 

```
!pip install pip install git+https://github.com/google/flax optax
# ...
```
