### ISSUE TITLE
fix checkpointing handling of giant msgpack array leaves

### ISSUE THREAD

**Issue by levskaya** [google/flax#1556]
We added "chunking"/"unchunking" of giant array leaves in our msgpack serialization format to get around msgpack's 32-bit limits on leaf-sizes.  However python msgpack has a safety `max_buffer_size` kwarg in unpacking that we don't handle.  

We should capture `BufferFull` exceptions and reraise w. a user-friendly error pointing to a `max_buffer_size` kwarg that we should add for setting this in our restore functions.

**Comment by marcvanzee** [comment]
@IvyZX I wonder if this issue is still relevant, given that we are considering switching to Orbax. WDYT?

**Comment by IvyZX** [comment]
Somehow this fell through the cracks... agreed that this would soon be irrelevant because of the Orbax migration.
