### ISSUE TITLE
Showcase "transfer learning" with imagenet example

### ISSUE THREAD

**Issue by andsteing** [google/flax#1567]
The existing [`examples/imagenet/notebook.ipynb`](https://colab.research.google.com/github/google/flax/blob/main/examples/imagenet/imagenet.ipynb) could be extended to showcase how to do transfer learning, i.e. use a pre-trained imagenet model, remove some layers, and then train with some other layers frozen.

#1565

**Comment by marcvanzee** [comment]
@cgarciae who is working on a transfer learning example

**Comment by marcvanzee** [comment]
@andsteing given that Cristian created a [Transfer learning example](https://flax.readthedocs.io/en/latest/guides/transfer_learning.html), I am closing this issue but feel free to re-open if you are still planning on adding it to the Colab (just trying to trim down our issues a bit).
