### ISSUE TITLE
Fully deprecate `optimizer.compute_gradient`

### ISSUE THREAD

**Issue by avital** [google/flax#157]
We're replacing the use of `optimizer.compute_gradient` with calls to JAX's `jax.grad` or `jax.value_and_grad`.

- [ ] The docstring for `compute_gradient` should specify that it's deprecated and print a warning, like for `optimizer.optimize()`.
- [ ] The ImageNet example shouldn't use` compute_gradient`

**Comment by joaogui1** [comment]
Guess we can close this @avital

**Comment by avital** [comment]
I agree :) Thanks!
