### ISSUE TITLE
Add doc: "Flax Module lifecycle"

### ISSUE THREAD

**Issue by avital** [google/flax#1576]
Should cover:

- When/why does setup() get called?
- When/why do module instances get cloned -- and relatedly why do we freeze module instances outside of setup?
- What happens to Flax modules inside a JAX transformations?
- Why/when is it safe to override `__post_init__`
- How does construction of submodules know to attach itself to parent
- How to use functional "submodules", e.g. `Dense(parent=None).apply(...)`

cc @andsteing for additional topics if they come to mind

**Comment by marcvanzee** [comment]
This can be closed. Module lifecycle doc is here: https://flax.readthedocs.io/en/latest/design_notes/module_lifecycle.html
