### ISSUE TITLE
RNN Layers

### ISSUE THREAD

**Issue by kamalkraj** [google/flax#1677]
### Description of the model to be implemented
Is there a plan to add a simple RNN cell and a Layer wrapper that can take an RNN Cell, output an RNN Layer like in TensorFlow

### Reference implementations in other frameworks
https://www.tensorflow.org/api_docs/python/tf/keras/layers/RNN

I am interested in contributing this feature

**Comment by cgarciae** [comment]
Interested in this topic as well.

**Comment by jheek** [comment]
There's nothing concrete on the roadmap right now. I think such an abstraction could be helpful and pretty lightweight in Flax as well. Do you want to make a proposal?

**Comment by kamalkraj** [comment]
Sure @jheek.

**Comment by marcvanzee** [comment]
Assigning this to @cgarciae since he proposed the RNN Flip in #2396

**Comment by marcvanzee** [comment]
Duplicate of #2170
