### ISSUE TITLE
DenseGeneral does not use dtype of initializer

### ISSUE THREAD

**Issue by tvieijra** [google/flax#1705]
I tried intializing a DenseGeneral layer with a kernel_init and bias_init function that initializes the parameters as float64 instead of the default float32.  However, the layer ends up creating float32 parameters.  The problem can be reproduced with following MWE
```
import jax
from jax.config import config
config.update("jax_enable_x64", True)
import flax
from flax.linen.initializers import lecun_normal

initializer = lecun_normal(dtype=jax.numpy.float64)

layer = flax.linen.DenseGeneral(2, dtype=jax.numpy.float64, kernel_init=initializer)
_, weights = layer.init_with_output(jax.random.PRNGKey(0), (2,))
```

This yields the following parameters:
`FrozenDict({
    params: {
        kernel: DeviceArray([[1.4876375, 1.4234805]], dtype=float32),
        bias: DeviceArray([0., 0.], dtype=float32),
    },
})`

As far as I can see, this issue is caused by the wrapper functions `kernel_init_wrap` and `bias_init_wrap` in the DenseGeneral class.  They accept a dtype keyword but are called without using it.  I think the fix is just passing the correct dtype to these functions, but I am not sure this causes problems anywhere else.

**Comment by marcvanzee** [comment]
Looks like a bug! The init wrapper takes a `dtype` argument but that one is never set, so the default `float32` is always used. I'll file a PR for this.

**Comment by marcvanzee** [comment]
Reopening this since my proposed solution didn't work and @levskaya may have some thoughts on this.

**Comment by levskaya** [comment]
#1739 should hopefully fix this issue by offering a second `param_dtype` parameter for determining the dtype of variables stored in memory/disk (separate from activation dtype).
