### ISSUE TITLE
Please consider lifting custom_vjp

### ISSUE THREAD

**Issue by NeilGirdhar** [google/flax#1713]
According to the [documentation](https://flax.readthedocs.io/en/latest/design_notes/lift.html), there is no `flax.custom_vjp` yet.  Are there any plans to implement it?

I love the design of `flax.vmap`, which adds `variable_axes` and `split_rngs`.  If a similar approach were taken with `custom_vjp`, then the ability to lift parameters that I requested https://github.com/google/flax/issues/1712 might be unnecessary.

**Comment by levskaya** [comment]
I'll let @jheek comment on his own work, but FYI he merged in #1738 recently.

**Comment by NeilGirdhar** [comment]
@levskaya That was impressively fast!!  I'd like to try to integrate it with my work over the next few days to see if the interface solves my problem.  Would it be okay if I left the issue open?

**Comment by levskaya** [comment]
yeah no worries, let us know if it works for you.

**Comment by jheek** [comment]
Lol I linked the PR to itself instead of to this issue. Thanks for mentioning @levskaya
