### ISSUE TITLE
Complicated aliasing issue when passing modules as arguments in transforms

### ISSUE THREAD

**Issue by levskaya** [google/flax#1746]
For a setup-style module with helper methods, under named_call or other transforms we raise a name-reuse error when a helper-method takes a `self.some_submodule` as a method argument.  

For instance the simplest breaking example, reduced from a user bug, is:
```
k = random.PRNGKey(0)
x = jnp.ones((2,))
class Foo(nn.Module):
  def setup(self):
    self.inner = nn.Dense(2)
  @nn.jit
  def helper(self, x, m):
    return x   # we don't even need to call 'm' to trigger the issue!
  @nn.jit
  def __call__(self, x):
    return self.helper(x, self.inner)
vs_bar = Foo().init(k, x)
```
Here, we pass local submodule `self.inner` as a helper-method argument.  This means that inside a transform `dedup_scopes` will already create the child scope for `self.inner` from the scope of `self`.  However, when `setup` is actually called "non-shallowly" inside the transform this causes a name-reuse error.

I tried fixing it by not having dedup_scopes reserve names during `push`, but of course _that_ breaks detection of compact-style name conflict:
```
k = random.PRNGKey(0)
x = jnp.ones((2,))
class Foo(nn.Module):
    @nn.jit
    def helper(self, x, m):
      a = nn.Dense(2, name="a")
      return m(x)
    @nn.jit
    @nn.compact
    def __call__(self, x):
      a = nn.Dense(2, name="a")
      return self.helper(x, a)
vs_bar = Foo().init(k, x)
```

I also tried some complicated lifecycle state-management tweaks in an earlier flawed PR...  I'm not sure how to fix this error.  I'm not even sure how to reliably throw a more helpful error since even detecting this sort of aliasing is just as hard as handling it correctly.  

I _might_ be able to fix things if I moved name reservations back into the linen level vs. at the scope level?  But I'm not actually sure and that's a large change.  

Honestly at this point I'd be tempted to remove the ability to pass Modules as arguments altogether, but I'm afraid a ton of our users are already using this feature... so ideally I'd like to find a way to rule out this class of obscure bugs.

**Comment by levskaya** [comment]
I believe #1745 handles this issue correctly.  We need to evaluate static checks on `setup` immediately via abstract evaluation for name-collision, but under transforms allow scope-name aliasing by calling `push` with `reuse=True`.

**Comment by jheek** [comment]
@levskaya is this completly fixed now?

**Comment by levskaya** [comment]
I had forgotten to handle one other line doing a "name-check on scope" in #1745, but #2001 should resolve that and let us close this.

**Comment by levskaya** [comment]
#1745 and #2001 should fix this.
