### ISSUE TITLE
Add tests to all examples that one step of training works without crashing.

### ISSUE THREAD

**Issue by avital** [google/flax#176]

**Comment by MostafaDehghani** [comment]
There is already 

- [ ] mnist
- [ ] Module.apply
- [ ] Module.call
- [ ] Module should get a docstring
- [ ] nn.stateful
- [ ] nn.stochastic
- [ ] Module.get_param (explain when it should be used)

**Comment by levskaya** [comment]
I think the challenge here is running w. minimized-model hparams such that our CI doesn't slow to a terrible crawl, and in that case we're not really testing the training loop, though we would at least be exercising the code paths.

**Comment by MostafaDehghani** [comment]
@AlexeyG has sent a PR with a nice proposal for regression testing for Flax examples (#144). Not sure if we really want to train all our examples to the convergence (although it would be nice), but having that, we probably don't need to have tests with a single step of training for flax examples?

**Comment by avital** [comment]
We won't be able to run full end-to-end tests for all examples on every
commit. And it's valuable to run tests even before you submit a pull
request, as part of your experimentation flow. Moreover, we would want to
run this test on all HOWTOs as well, which won't be covered by the
end-to-end integration and performance testing.

Thus, it's still very valuable to have a small unit test per example (and
is good practice regardless)

**Comment by danielsuo** [comment]
Does it make sense to have different test suites run at different times? E.g.,:

1. for a first, easy pass, just make sure all unit tests pass.
2. Run convergence or regression testing on a beefier set of machines (@marcvanzee pointed out that maybe not all developers can easily do this locally) possibly less frequently.
3. Run performance tests (to flag memory issues or bad optimizations)

**Comment by avital** [comment]
Closing this as it's being taken care of by #231
