### ISSUE TITLE
flax.linen.pool returns array with 0 dimensions

### ISSUE THREAD

**Issue by SarthakYadav** [google/flax#1829]
Hi!

### Problem you have encountered:
`flax.linen.pool` can return array with 0 dimensions, depending on the input array shape and the kernel/stride parameters.

Minimal example taking `flax.linen.avg_pool`:

```python
for i in range(2, 5):
    x = jnp.ones((2,) + (2,)*i)
    print("x.ndim: {} | x.shape:{}".format(x.ndim, x.shape))
    # although a trivial example, but should be checked and an exception should be raised
    window_shape = (3,)*i                  
    print("len(window_shape):", len(window_shape))
    print("output_shape:", nn.avg_pool(x, window_shape).shape)
    print("------------------------------")
    
x.ndim: 3 | x.shape:(2, 2, 2)
len(window_shape): 2
output_shape: (0, 0, 2)
------------------------------
x.ndim: 4 | x.shape:(2, 2, 2, 2)
len(window_shape): 3
output_shape: (0, 0, 0, 2)
------------------------------
x.ndim: 5 | x.shape:(2, 2, 2, 2, 2)
len(window_shape): 4
output_shape: (0, 0, 0, 0, 2)
------------------------------
```

### What you expected to happen:

- An exception should be raised if any dimension of the output is evaluated to `< 1` for the given arguments (It is raised for dimensions `< 0` by `jax.lax`)

PyTorch raises an exception:
```python
import torch
x = torch.randn(2, 2, 2)

>>> torch.nn.functional.avg_pool1d(x, (3, ))   # the correct pool for the corresponding input

"""
RuntimeError: Given input size: (2x1x2). Calculated output size: (2x1x0). Output size is too small
"""

>>> torch.nn.functional.avg_pool2d(x, (3, 3))

"""
RuntimeError: Given input size: (2x2x2). Calculated output size: (2x0x0). Output size is too small
"""
```

- Pooling operation is much less likely to be applied to the batch dimension of the input. If a `window_shape` of `len(window_shape) == inputs.ndim - 1` is provided to `flax.linen.pool` the default behaviour should be to not pool the first dimension. This is what torch does
```python
import torch
x = torch.randn(1, 16, 16)

# although the correct pooling function to use is avg_pool1d, just making my point here
print(torch.nn.functional.avg_pool2d(x, (2, 2), stride=(2, 2)).shape)    # prints (1, 8, 8)

```

-------------------------------------------

I understand these situations are likely to arise more due to human error than anything else, but it is only aggravated by the fact that flax does not have explicit `whatever_poolNd` layers which (allow to) check for inconsistencies between shapes of inputs and arguments. Also, in very deep networks with enough downsampling operations, this could easily happen.

One can also argue that the onus of checking output dimensions is on `lax.reduce_window`. However, flax being a higher-level library, I think some validation should be performed here as well.

**Comment by SarthakYadav** [comment]
@jheek sorry to tag you directly, but can you please comment on this?

I'm not sure if this issue is better suited for the JAX repository, though I feel adding some validation check on output dimensions on the flax side makes sense.

**Comment by jheek** [comment]
> the default behaviour should be to not pool the first dimension. This is what torch does

We cannot do this because we support a batch free usage of all the linen layers so the batch dim isn't always there. In this case the first dim is a spatial dim and thus should be pooled over


I guess the second issue is whether pooling to size 0 is an error.

I think that is really a question about JAX semantics. You would expect this to be consistent for both conv and pool operations. Right now I think we support 0 sized arrays which are also effectively handled by XLA as zero-cost. So there are legit use cases for wanting to make a 0 sized array.

**Comment by SarthakYadav** [comment]
Makes sense. Thanks for the clarification. Closing this one!
