### ISSUE TITLE
Can we get rid of the `sep` argument used in the "Model Surgery" HOWTO?

### ISSUE THREAD

**Issue by avital** [google/flax#1849]
In this HOWTO (https://flax.readthedocs.io/en/latest/howtos/model_surgery.html), we use this pattern:

```
# Get flattened-key: value list.
flat_params = traverse_util.flatten_dict(params, sep='/')
print(jax.tree_map(jnp.shape, flat_params))
{'Conv_0/bias': (32,),
 'Conv_0/kernel': (3, 3, 1, 32),
 'Conv_1/bias': (64,),
 'Conv_1/kernel': (3, 3, 32, 64),
 'Dense_0/bias': (256,),
 'Dense_0/kernel': (3136, 256),
 'Dense_1/bias': (10,),
 'Dense_1/kernel': (256, 10)}
```

But I think the use of `sep` here is misleading, making people think you need to use string keys. Instead, I would imagine that this would work and perhaps be clearer:
```
# Get flattened-key: value list.
flat_params = traverse_util.flatten_dict(params)
print(jax.tree_map(jnp.shape, flat_params))
{('Conv_0', 'bias'): (32,),
 ('Conv_0', 'kernel'): (3, 3, 1, 32),
 ('Conv_1', 'bias'): (64,),
 ('Conv_1', 'kernel'): (3, 3, 32, 64),
 ('Dense_0', 'bias'): (256,),
 ('Dense_0', 'kernel'): (3136, 256),
 ('Dense_1', 'bias'): (10,),
 ('Dense_1', 'kernel'): (256, 10)}
```

So I propose someone give a shot at this, filing a PR carefully changing that HOWTO and fixing all of the outputs as well. (Or looking for feedback whether people think it would not be better)

**Comment by wdg3** [comment]
Agreed that removing `sep` makes more clear - PR raised.
