### ISSUE TITLE
Write a guide, HOWTO and/or example that shows how to correctly deal with the last batch during eval

### ISSUE THREAD

**Issue by avital** [google/flax#1850]
See #264 for the original motivation -- many naive implementations of eval loop over a full dataset would incorrectly deal with the last batch, that may be smaller than the others, including most of our examples. A fully complete solution would add complexity to the examples, so depending on how educational they are, it may not be the right tradeoff. Instead, we should clearly document in one place the full set of best practices to achieve this, and if needed, add utility functions to Flax to make this easier to do.

**Comment by andsteing** [comment]
See also #527 about computing metrics correctly in examples.

**Comment by marcvanzee** [comment]
Closing this in favor of https://github.com/google/flax/issues/2116.

**Comment by andsteing** [comment]
See also #2111
