### ISSUE TITLE
Add HOWTO: Data-parallel training

### ISSUE THREAD

**Issue by marcvanzee** [google/flax#1986]
See #1982, this HOWTO will implement data-parallel training using pmap in the seq2seq example.

**Comment by marcvanzee** [comment]
@gmittal mentioned he would like to implement this based on #1982

**Comment by marcvanzee** [comment]
@gmittal any updates on this?

**Comment by marcvanzee** [comment]
FYI I am closing this issue in favor of #2116

**Comment by gmittal** [comment]
@marcvanzee sorry for delay -- this is still in-progress and will have a PR for this in the next week.
