### ISSUE TITLE
msgpack_serialize does not work with FrozenDict PyTree

### ISSUE THREAD

**Issue by daniel-j-h** [google/flax#2005]
### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`: jax 0.3.1, jaxlib 0.3.0+cuda11.cudnn82, flax 0.4.0
- Python version: 3.8.10
- GPU/TPU model and memory: 
- CUDA version (if applicable): 

Hey folks, I quickly wanted to save some flax.linen module params to disk. Because of https://github.com/google/flax/issues/1924 I am not using the checkpoints module, but instead I'm using the serialization module.

When trying to serialize my flax.linen module's params (FrozenDict) I get an error (see below). Unfreezing the FrozenDict before serializing works as a workaround. See self-contained reproducible example below.

The documentation makes it sound like it should work with FrozenDicts just as fine.
https://flax.readthedocs.io/en/latest/flax.serialization.html#flax.serialization.msgpack_serialize

```python3
>>> import jax
>>> import jax.numpy as jnp
>>> import flax.linen as nn
>>> from flax.serialization import msgpack_serialize, msgpack_restore
>>>
>>> params = nn.Dense(1).init(jax.random.PRNGKey(0), jnp.zeros((1,)))
>>> params
FrozenDict({
    params: {
        kernel: DeviceArray([[-1.4588346]], dtype=float32),
        bias: DeviceArray([0.], dtype=float32),
    },
})
>>>
>>> msgpack_serialize(params)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/python/.local/lib/python3.8/site-packages/flax/serialization.py", line 331, in msgpack_serialize
    return msgpack.packb(pytree, default=_msgpack_ext_pack, strict_types=True)
  File "/home/python/.local/lib/python3.8/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 291, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'FrozenDict' object
>>>
>>> msgpack_serialize(params.unfreeze())  # WORKAROUND
b'\x81\xa6params\x82\xa4bias\xc7\x11\x01\x93\x91\x01\xa7float32\xc4\x04\x00\x00\x00\x00\xa6kernel\xc7\x12\x01\x93\x92\x01\x01\xa7float32\xc4\x04\x18\xbb\xba\xbf'
```

### What you expected to happen:

Serializing params (FrozenDict) works by default, because that is a common use case.

The manual `unfreeze()` is a workaround for now.

**Comment by levskaya** [comment]
Hey! sorry `msgpack_serialize` and `msgpack_restore` are low-level function entrypoints that are only intended to work with native python objects + numpy arrays.  To serialize/restore general things including user-registered types, use `serialization.to_bytes` and `serialization.from_bytes`

**Comment by daniel-j-h** [comment]
Awesome, thanks this works! Maybe we should change the docs or even hide the internal functions then.

https://flax.readthedocs.io/en/latest/flax.serialization.html#flax.serialization.msgpack_serialize
