### ISSUE TITLE
Impure functions used in documentation without clarification

### ISSUE THREAD

**Issue by MatthewCaseres** [google/flax#2060]
### Description of the model to be implemented
In the JAX for the impatient section, they use an impure function which confused me as a beginner, because I just read about the dangers of this in the JAX docs. `mse` reads `predict` from the global state. Why is it okay to do this?
```py
# Linear feed-forward.
def predict(W, b, x):
  return jnp.dot(x, W) + b

# Loss function: Mean squared error.
def mse(W, b, x_batched, y_batched):
  # Define the squared loss for a single pair (x,y)
  def squared_error(x, y):
    y_pred = predict(W, b, x)
    return jnp.inner(y-y_pred, y-y_pred) / 2.0
  # We vectorize the previous to compute the average of the loss on all samples.
  return jnp.mean(jax.vmap(squared_error)(x_batched, y_batched), axis=0)
```

### Dataset the model could be trained on
No major changes needed. 

### Specific points to consider
Clarify if any unsafe consequences are possible, or explain the safe way to nest pure functions.

**Comment by marcvanzee** [comment]
This is not a side effect, because in your example `predict` comes from the global scope and it can't be modified by `mse` (you need to use the `global` keyword for that). `mse` would be impure if it would modify a variable in the outside scope.

**Comment by MatthewCaseres** [comment]
It is like this example in "JAX: the sharp bits" from official docs.
```py
g = 0.
def impure_uses_globals(x):
  return x + g
```
but maybe this is nitpicky. Thanks for reply.

**Comment by jheek** [comment]
According to this logic jnp.mean and jnp.dot would be globals as well.
Closing over globals is not a problem as long as they don't change and aren't large arrays. 
Especially for functions it is normally a bad practice to change them after definition.

**Comment by MatthewCaseres** [comment]
Great to know, thanks.
