### ISSUE TITLE
Investigate and fix cause of warnings defined in pytest.ini

### ISSUE THREAD

**Issue by mohitreddy1996** [google/flax#210]
With pytest.ini defined, all the warnings captured during a test execution are reported as exceptions. 

Although there are a few warnings which are independent of flax's implementation (for e.g: DeprecationWarning and UserWarning captured due to importing tensorflow.compat.v2.io import gfile). 

Ideally we should have ZERO entries as exemptions in pytest.ini. Investigate the root cause and fix them.

**Comment by mohitreddy1996** [comment]
Currently the whitelist consists of the following:

`ignore:numpy.ufunc size changed.*:RuntimeWarning`
Warning due to scipy (or another package) that was compiled against an older numpy than is installed.

`ignore:No GPU/TPU found, falling back to CPU.*:UserWarning`
XLA level warning, origin: https://github.com/google/jax/blob/a1b4fe47bded33d37cb69c6b70a6d53421ed718e/jax/lib/xla_bridge.py#L123.

`ignore:can't resolve package from.*:ImportWarning
 ignore:the imp module is deprecated.*:DeprecationWarning`
Warning due to `from tensorflow.compat.v2.io import gfile`

**Comment by mohitreddy1996** [comment]
@avital could please change the bug label? Thanks!

**Comment by levskaya** [comment]
BTW: "ignore:No GPU/TPU found, falling back to CPU.*:UserWarning" is considered a user-facing warning from JAX to insure people are aware when they accidentally run in CPU-only mode (e.g. bad nvidia drivers, cuda install, etc etc).  This warning isn't going to be "fixed".
