### ISSUE TITLE
Test Notebooks during CI

### ISSUE THREAD

**Issue by cgarciae** [google/flax#2125]
Currently notebooks are not tested which could lead to them breaking as the API changes or they simply contain errors that go unnoticed as happened recently in #2089. The basic idea would be to convert notebooks to python scripts and run these, if the notebook/script takes too long to run maybe some parameters (e.g. epochs, steps per epoch, etc) could be programmatically replaced to minimize this. 

Since there isn't a standard way to do this for all notebooks, CI support would have to be added in a per-notebook fashion, and probably to a subset of the most relevant ones. I think `flax_basics.ipynb` could be one of those notebooks since it was already supported and its one of the most important guides in our documentation.

**Comment by marcvanzee** [comment]
@cgarciae this actually came up during a chat I had today with @gnecula who asked if we are currently testing our notebooks. Could you please add a link to the PR that enables this to this issue? Then we can always find it back easily later on.

**Comment by cgarciae** [comment]
This issue was addressed in #2166.
