### ISSUE TITLE
Flax actually requires jax 0.3.2

### ISSUE THREAD

**Issue by PhilipVinc** [google/flax#2135]
https://github.com/google/flax/blob/ef6bf4054c30271a58bfabb58f3d0049ef5d851a/flax/linen/initializers.py#L19

the constant initialiser was added in this commit https://github.com/google/jax/commit/86e8928e709ac07cc51c10e815db6284507c320e that was first included in jax 0.3.2

This came up in NetKet's automated oldest-version-dependencies testing.

**Comment by jheek** [comment]
> NetKet's automated oldest-version-dependencies testing.

Nice catch, we should do this too! Is there some kind of pip flag for this?

**Comment by PhilipVinc** [comment]
ahahahahahahahahahahahahahahahahahahaha

Sorry, pip is terrible so either I laugh or I cry.

No, I spent considerable time investigating and neither pip, nor `pip-tools` nor `pipenv` support this.
We use a kind-of-a hacky script:

https://github.com/netket/netket/blob/master/conf/compute_oldest_dependencies.py

and run a single runner in GitHub actions with thee variable `oldest_deps=True` with the json file below

```json
      - name: Pip install oldest dependencies
        if: matrix.oldest_deps
        run: |
          python conf/compute_oldest_dependencies.py
          pip install -r oldest_requirements.txt
      - name: Pip install packages
        run: |
          pip install -e ".[dev, extras]"
``` 

It works. It's not super-resistant, as for example if netket depends on `numpy>=0.18` and jax requires `numpy>=0.19`, this script will attempt to install `numpy==0.18, jax==0.3` and pip will fail complaining that `jax require numpy>=0.19`.

But it gets the job done, and ensures we always bump required versions which is handy.
