### ISSUE TITLE
BatchNorm error message

### ISSUE THREAD

**Issue by david-waterworth** [google/flax#214]
The `flax.nn.normalization.BatchNorm` error message "batch_stats should be provided if use_running_averages is True" is slightly misleading. 

I think would be clearer if it say something like "when use_running_averages is True either use a stateful context or provide batch_stats"

It wasn't clear to me why the `imagenet` example worked without providing batch_stats and my layer failed until I looked closer at the source and realised that it was using a stateful context.

**Comment by avital** [comment]
Good point. We're reconsidering our use of context managers (perhaps in favor of function decorators), and perhaps that would simplify the mental model.

In the meanwhile, would you like to give a shot at improving the error message in a pull request? The language in the new error should really direct the user towards the right solution, so it's important to think carefully about the wording.

**Comment by avital** [comment]
Hi @david-waterworth -- any interesting in submitting a pull request improving the error message?

**Comment by ayush-1506** [comment]
@avital I've opened a PR that should fix this: #301. Would love a review. Thanks
