### ISSUE TITLE
Port HOWTOs to notebooks

### ISSUE THREAD

**Issue by cgarciae** [google/flax#2185]
Currently HOWTO's are written in `.rst` which leverage the `.. testsetup::` directive to hide some code while keeping the document testable. There are a couple of downsides to this:

* We have 2 ways of writing tutorials (`.ipynb` and `.rst` files)
* You cannot (easily) generate a colab from this.

After #2166 is merged we can use `myst_nb` mechanisms for both hiding content and testing it on CI to replace some/most of the `.rst` files with `.ipynb` or `.md` versions.

**Comment by marcvanzee** [comment]
@cgarciae is this done?

**Comment by cgarciae** [comment]
We've ported some, however, those that use the `codediff` directive have no equivalent in jupyter/markdown. Closing this as we've done everything possible.
