### ISSUE TITLE
Automated linting and formatting

### ISSUE THREAD

**Issue by danielsuo** [google/flax#219]
Creating a new issue so there's space to discuss since it's come up as asides in some other issues (#207, #147).

My personal view on the topic is easy, reasonable consistency, but I know it can be quite controversial! It seems practical to start with minimal configuration and progress from there as we find issues that annoy. Hopefully this is something we set up early and don't need to think about much after the initial pain.

Two positions to seed the discussion:
1. **Enforce via CI**: right now, we have a `pylintrc`, but folks appear free to ignore.
2. **Enforce on commit**: more controversial / more overhead, but saves CI from linting/formatting fails. 

Some package suggestions:
- **Formatters**: [yapf](https://github.com/google/yapf) and [black](https://github.com/psf/black) are two good choices. Even though the former is google, I've tended towards `black` because it's faster (I believe `yapf` is quadratic) and treats non-determinism as a bug. Two dings against, however:
  1. It requires Python 3.6+ to run, which may or may not be a problem, especially if we use pre-commit hooks (see below)
  2. Could `flax` handle the transition from 2-space indent to 4-space tab?!
- **Linters**: We already have `pylint`, so it may be good to leave at that.
- **Imports**: This issue cropped up from sorting imports, so I'd be remiss to leave out; there's the ever-popular [isort](https://github.com/timothycrosley/isort), but I've preferred [this one](https://github.com/asottile/reorder_python_imports) just because it's a little simpler. Either is fine.
- **Pre-commit**: I've found the [pre-commit](https://pre-commit.com/) project very helpful to manage commit hooks. Here is the [configuration](https://github.com/MinRegret/timecast/blob/master/.pre-commit-config.yaml) from `timecast`. Two pain points:
  1. Requires people to install pre-commit hooks (a one-liner that I'd imagine goes into dev on-boarding docs)
  2. Failed pre-commit hooks fail a commit; good hygiene, but this might annoy people since it's not the standard git loop

## Proposal
TBD. No proposal because just discussion for now.

## Transition
TBD. Such a change could create a _lot_ of merge conflicts. Once we decide on the scope of linting/formatting, first thing to do is understand how much conflict will actually arise. We can go from there (e.g., if it's really bad, either change scope or set a date by which all changes need to be in before The Linting; and we can refer to flax history as BL and AL...)

**Comment by danielsuo** [comment]
Tagging @mohitreddy1996 and @joaogui1

**Comment by avital** [comment]
Thanks @danielsuo for starting this conversation! A few comments:

1. @levskaya had spoke of black being really unhelpful with numpy codebases (maybe because of long argument lists to functions?) -- @levskaya can you elaborate more as to how black might be suboptimal for us?

2. Re: enforce on commit. Do we have a sense for how long linting our current codebase would take? Seems like we could do a back-of-the-envelope for codebase growth to assess whether this would be a viable idea.

3. Python 3.6+ is fine.

4. pre-commit.com looks neat, I hadn't heard of it before.

5. Transition plan -- here's my proposal: Choose a particular subdirectory of flax/, set up the linter rules just for that directory and all the relevant machinery you proposed and let's see what the diff looks like. Then we can discuss whether we should make the linter rules more strict or more lenient. Once we're happy with them, we can split up the codebase and coordinate a virtual hackathon to fix the rest. @danielsuo if you want to give it a shot to get the ball rolling, that would be great.

cc @bastings who had also thought about linters for Flax before (though I don't think he is actively working on it)

**Comment by danielsuo** [comment]
Happy to get started! Responses inline:

> 1. @levskaya had spoke of black being really unhelpful with numpy codebases (maybe because of long argument lists to functions?) -- @levskaya can you elaborate more as to how black might be suboptimal for us?

No special love for `black` except that it's easy. Happy to configure something else. As Guideo [says](https://twitter.com/gvanrossum/status/1227126706089021440), `black` only if the team argues about style a lot.

> 2. Re: enforce on commit. Do we have a sense for how long linting our current codebase would take? Seems like we could do a back-of-the-envelope for codebase growth to assess whether this would be a viable idea.

Good point. Typically, this isn't an issue since with the right tooling, linting only operates on changes, but could be a problem in certain cases (e.g., during transition) when exclude patterns are very long, diffs are large, etc. I suppose more advanced cross-file/cross-module checks could also cause problems. Just ran `flake8` on a couple of repositories in their entireties to get a rough sense for what simpler checks might look like:

| repo | cores | time |
|:-----|:----:|-----:|
| flax | 1 | 3.89 |
| flax | 16 | 0.69 |
| jax | 1 | 17.87 |
| jax | 16 | 2.08 |
| tensorflow | 1 | 3:53.70 |
| tensorflow | 16 | 13.29 |

```bash
# flax with 1 core
flake8 -q -j 1 3.85s user 0.04s system 99% cpu 3.888 total

# flax with 16 core
flake8 -q 6.33s user 1.97s system 1205% cpu 0.689 total

# jax with 1 core
flake8 -q -j 1 17.61s user 0.25s system 99% cpu 17.865 total

# jax with 16 core
flake8 -q 24.66s user 3.20s system 1338% cpu 2.081 total

# tensorflow with 1 core
flake8 -q -j 1 230.18s user 3.47s system 99% cpu 3:53.70 total

# tensorflow with 16 core
flake8 -q  458.48s user 15.71s system 3567% cpu 13.291 total
```

> 3. Python 3.6+ is fine.

To clarify, Python 3.6+ would be a developer requirement if we used black and formatted/linted on commit. 

> 4. pre-commit.com looks neat, I hadn't heard of it before.

I love it! But...I can see if some would find it annoying. Below is an example where I intentionally remove some docstrings, force the coverage badge to regenerate, and fail the commit. In this case, the fixes are automatic, but I still need to re-commit.

![image](https://user-images.githubusercontent.com/2692566/80211264-67a34a80-8603-11ea-9fbe-da3183827514.png)

> 5. Transition plan -- here's my proposal: Choose a particular subdirectory of flax/, set up the linter rules just for that directory and all the relevant machinery you proposed and let's see what the diff looks like. Then we can discuss whether we should make the linter rules more strict or more lenient. Once we're happy with them, we can split up the codebase and coordinate a virtual hackathon to fix the rest. @danielsuo if you want to give it a shot to get the ball rolling, that would be great.

Sounds good! Will throw something together later today. I'll use `black`, `flake8`, etc just as an example, but I have no religion about any of these. I will emphasize that at least once or twice more in case blood pressures rise!

**Comment by joaogui1** [comment]
I like yapf because it allows for more customization compared to black 
[Here's](https://github.com/google/jax/issues/1445) a discussion we had about that on the JAX repo

**Comment by danielsuo** [comment]
Thanks for the link! Helpful to see @levskaya's and @shoyer's responses. @joaogui1's PRs in jax ([here](https://github.com/google/jax/pull/1450) and [here](https://github.com/google/jax/pull/1623)) also instructive. Seems like there's quite a bit of resistance to automated Python formatting (possibly linting). I'll leave the issue open, but this might be DOA.

**Comment by joaogui1** [comment]
I don't think it's DOA, folks on JAX didn't seem to want it, but @avital seems open to the idea

**Comment by danielsuo** [comment]
Oops, I phrased too dramatically, my bad. Yes different projects, but the Jax folks did have good points that may apply here given the overlap of contributors. Just wanted to make it easier for the maintainers to reject the issue if they want to. Happy to go either way!

**Comment by marcvanzee** [comment]
It seems like it is very hard to get agreement on this, and since there hasn't been much recent activity I'm closing this issue.
