### ISSUE TITLE
Learning rate schedule HOWTO

### ISSUE THREAD

**Issue by joaogui1** [google/flax#222]
Is there interest in a PR showing how to use learning rate schedules?

**Comment by MostafaDehghani** [comment]
We probably want to figure out if we can unify and standardize the use of learning rate schedulers in Flax examples.  Currently different examples do different things, for instance CIFAR10 example uses  learning rate schedulers implemented in [flax/training/lr_schedule.py](https://github.com/google/flax/blob/master/flax/training/lr_schedule.py), but LM1b example has its own [learning rate scheduling function](https://github.com/google/flax/blob/master/examples/lm1b/train.py#L142).

**Comment by joaogui1** [comment]
Good idea, I think we should use the ones defined on [flax/training/lr_schedule.py](https://github.com/google/flax/blob/master/flax/training/lr_schedule.py) and if needed implement the ones used in the examples.
When a decision is reached I'm more than happy to write the PR

**Comment by joaogui1** [comment]
Hey @avital can you give your opinion on this?

**Comment by avital** [comment]
Hi @joaogui1, I agree with @MostafaDehghani that in the longer term we should unify our use of learning rate schedules but now I'd take a PR adding a HOWTO showing how to implement a simple(!) LR schedule for the MNIST example. Take a look at the HOWTO HOWTO in the docs to learn more about the process for that.

**Comment by marcvanzee** [comment]
@joaogui1 are you still planning to do this? We are currently using a simpler HOWTO system, where we write them as markdown in readthedocs. Here is [an example](https://flax.readthedocs.io/en/latest/howtos/state_params.html) and [here is the source](https://github.com/google/flax/blob/master/docs/howtos/state_params.rst), but we are actually planning to use a slightly different setup in which we make sure our code is tested automatically using Sphinx's `testcode` directive (you can see an example of this in https://github.com/google/flax/pull/771). 

Would you like to give this HOWTO a try in the new HOWTO system?

**Comment by joaogui1** [comment]
@marcvanzee I'm happy to do it, is it ok if I open a PR around Friday?

**Comment by marcvanzee** [comment]
Yes, that would be great, thanks a lot!

**Comment by joaogui1** [comment]
Hi, I got sick on Wednesday (not Covid thankfully) and so I may end up delaying this, sorry

**Comment by joaogui1** [comment]
Sorry for the delay, opened the pr @marcvanzee
