### ISSUE TITLE
More optimizers

### ISSUE THREAD

**Issue by joaogui1** [google/flax#223]
Is there interest in any of the following optimizers?

- AdamW
- Radam
- Look Ahead (either as something that wraps optimizers or as SGD-LookAhead, SGD-Adam, Ranger, Over9000 and so on)

I know that Flax isn't about just adding more features to the framework, but I think it would be good to have "canonical" implementations of those algorithms

**Comment by levskaya** [comment]
Just a note that the current Adam already supports "AdamW" behavior via its weight-decay parameter.

**Comment by joaogui1** [comment]
Hey @avital, @marcvanzee any opinion on this?

**Comment by avital** [comment]
Hi @joaogui1, sounds like these would be valuable but we want to make sure that all the code in Flax is maintained by members of the Flax core team. Given that AdamW works with our current implementation and we haven't year heard requests for the other optimizers, it's not clear that these optimizers are best placed inside the Flax repo.

That being said, if you'd like to implement these in separate repositories we're happy to link to them from `flax/optim/README.md` (which doesn't yet exist but we are happy to create).

If you make these, feel free to file a PR adding `flax/optim/README.md` linking to them.

**Comment by AlexeyG** [comment]
Closing this for now, please feel free to re-open the issue @joaogui1

**Comment by samaritanhu** [comment]
> Hi @joaogui1, sounds like these would be valuable but we want to make sure that all the code in Flax is maintained by members of the Flax core team. Given that AdamW works with our current implementation and we haven't year heard requests for the other optimizers, it's not clear that these optimizers are best placed inside the Flax repo.
> 
> That being said, if you'd like to implement these in separate repositories we're happy to link to them from `flax/optim/README.md` (which doesn't yet exist but we are happy to create).
> 
> If you make these, feel free to file a PR adding `flax/optim/README.md` linking to them.

Hi @avital, recently in our company optimizer like 
- madam (I saw other GitHub repo also implement this: https://github.com/jxbz/madam)
- nadam
works pretty great(than adam), so I think if there are opportunities, we can add these optimizers in separate repositories and link to them from flax/optim/README.md

**Comment by avital** [comment]
Absolutely @samaritanhu, if you implement those for Flax we'll link to them.

**Comment by nestordemeure** [comment]
> Hi @avital, recently in our company optimizer like
> 
> * madam (I saw other GitHub repo also implement this: https://github.com/jxbz/madam)
> * nadam
>   works pretty great(than adam), so I think if there are opportunities, we can add these optimizers in separate repositories and link to them from flax/optim/README.md

Feel free to send a PR to my [Flax Optimizers](https://github.com/nestordemeure/flaxOptimizers) repository.

I just submitted a PR where I add a link to the repository (which already contains my implementation of RAdam and Ranger) following @avital's suggestion.
