### ISSUE TITLE
How to share a parameter between modules in FLAX

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [google/flax#2242]
HI
Hi, I need to share a parameter between two modules,  I still could not make it work, my previous question (https://github.com/google/flax/issues/2240#issuecomment-1167026441) is closed so I reopen it here, I did as below, but I am getting `Invalid type annotation '<instance of Callable>' for param [invalid-annotation] Not a type`, what is the type for Module.param in FLAX? thanks!
```
class Foo(nn.Module):
  def setup(self):
    self.dense = nn.Dense(3)
    self.shared = self.param("external_memory_bias", nn.zeros,(6,), "float32")
    self.A_enc = A(shared=self.shared, is_shared=False)
    self.C_enc = A(shared=self.shared, is_shared=True)

  def __call__(self, x, y):
    x = self.dense(x)
    y = self.dense(y)
    y = self.A_enc(y)
    return x, y

class A(nn.Module):
  is_shared: bool 
  shared: Optional[nn.Module.param] = None 

  def setup(self, is_shared=False, shared=None):
     if is_shared:
       self.param = shared 
     else:
      self.param = self.variable(
        'database', 'key_db', functools.partial(jnp.zeros, dtype=jnp.float32), (4))
     
  def __call__(self, x):
    return x*self.param
```

**Comment by rabeehkarimimahabadi** [comment]
I think this should be of type jnp.DeviceArray? module.param has return type T ```def param(self, name: str, init_fn: Callable[..., T], *init_args) -> T:```  and if one uses jnp.zeros for init_fn, then it should be jnp.DeviceArray as return type, is this correct? thanks

**Comment by jheek** [comment]
The old issue was converted to a [discussion](https://github.com/google/flax/discussions/2241) please follow up there

**Comment by rabeehkarimimahabadi** [comment]
Hi @jheek  please do not close this, as I am still looking for answer, the one I posted there did not work at the end! thanks

**Comment by rabeehkarimimahabadi** [comment]
thanks. Fixed
