### ISSUE TITLE
Remove flax.optim

### ISSUE THREAD

**Issue by marcvanzee** [google/flax#2273]
flax.optim is deprecated and unused but we still have it around. We should remove it in a new version to not confuse new users.

**Comment by OhadRubin** [comment]
fyi, entirely removing the documentation makes updating code from flax.optim to optax harder since I don't know what anything in flax.optim does....

**Comment by andsteing** [comment]
Good point. Activated v0.5.3 for reference of `flax.optim` API:

https://flax.readthedocs.io/en/v0.5.3/flax.optim.html

(Make also sure to read the update guide, which is still available in the `latest` version: https://flax.readthedocs.io/en/latest/advanced_topics/optax_update_guide.html )
