### ISSUE TITLE
Would you like to add link to tutorial demonstrating Wav2Vec2 finetuning

### ISSUE THREAD

**Issue by thevasudevgupta** [google/flax#2285]
Hello @avital, @marcvanzee 

I recently created a tutorial showing how to fine-tune wav2vec2 on full librispeech data (960h). You can find link to my work here: https://github.com/vasudevgupta7/speech-jax

This tutorial builds the data pipeline using `tf.data.Dataset` and shows how to use tensorflow datasets for streaming data to train FLAX models (specifically Wav2Vec2) on cloud TPUs.

Would you like to refer this tutorial in this repository?

**Comment by cgarciae** [comment]
Hey @vasudevgupta7! We might be able to reference it in [Community Examples](https://github.com/google/flax/blob/main/examples/README.md#community-examples) section. Feel free to send a PR or share it.
