### ISSUE TITLE
Typo in the PPO example

### ISSUE THREAD

**Issue by fuyw** [google/flax#2305]
https://github.com/google/flax/blob/830f2aec35b3ea690eca9a080181c143562f3b84/examples/ppo/ppo_lib.py#L343

A typo: return `state` instead of `train_state` here.

**Comment by marcvanzee** [comment]
Nice, thanks! Do you want to file a PR fixing this?

**Comment by fuyw** [comment]
Sure, PR #2306  needs a reviewer.
