### ISSUE TITLE
SORRY This page does not exist yet  / 404 on google query and logs

### ISSUE THREAD

**Issue by remic33** [google/flax#2335]
Many google queries and some flax logs are linking to 404 pages. 

Example with error : 
flax.errors.InvalidRngError: Dropout_0 needs PRNG for "dropout" (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.InvalidRngError)

Example with flax google query:
Query: https://www.google.com/search?channel=fs&client=ubuntu&q=flax+linen+relu
404 page URL: https://flax.readthedocs.io/en/latest/_autosummary/flax.linen.relu.html

It must have been a documentation update with no redirection.

**Comment by levskaya** [comment]
Sorry for the trouble!  We did just rearrange the organization of the docs.  I've added redirects to the old URLs, so hopefully most of the old links should work for now while we wait for google to rescan.  I'll close this now, but feel free to reopen if you encounter more breakage.  Thanks for the alert.
