### ISSUE TITLE
Transpose Convolution module issue when used with circular padding and vmap

### ISSUE THREAD

**Issue by zhong1wan** [google/flax#2362]
### Problem you have encountered:
I'm simply trying to `vmap` a `ConvTranspose` layer with circular padding, and it results in a `jax._src.errors.TracerArrayConversionError`. I'm running things on GPU.

### Steps to reproduce:
Here is a minimum example that reproduces the error.
```
import jax
import jax.numpy as jnp
import flax.linen as nn

layer = nn.ConvTranspose(features=5, kernel_size=(3,), padding="CIRCULAR")

# this is ok
sample_input = jnp.ones((1, 32, 2))
out, vars = layer.init_with_output(jax.random.PRNGKey(0), sample_input)
print(out.shape)

batch_input = jnp.ones((8, 4, 32, 2))
batch_apply = jax.vmap(layer.apply, in_axes=(None, 0))

# this breaks with the error provided
batch_out = batch_apply(vars, batch_input)
print(batch_out.shape)
```
I'm moderately confident that this is a bug that is specific to the transpose convolution because I verified that the code works ok if `nn.ConvTranspose` is replaced with `nn.Conv`. Things are also ok when `vmap` is not used.

### Logs, error messages, etc:

```
UnfilteredStackTrace: jax._src.errors.TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on the JAX Tracer object Traced<ShapedArray(float32[4,34,5])>with<BatchTrace(level=1/0)> with
  val = DeviceArray([[[[ 0.19632685,  0.56257343,  0.6327205 ,  0.278047  ,
...
```

### My guess at what's happening:
I'm suspecting that since padding needs to be added, the shape information becomes not static any more at some point?

**Comment by cgarciae** [comment]
Thanks @zhong1wan for reporting this! The issues was an incorrect use of `np.pad` for the circular case, this was converting JAX arrays into Numpy arrays which doesn't work for tracers (and its wrong anyways). I've pushed a patch to use `jnp.pad` instead.
