### ISSUE TITLE
imagenet demo not working out of the box

### ISSUE THREAD

**Issue by brettkoonce** [google/flax#2403]
Basically, flax 0.4.3 (current requirements.txt spec) no longer has the correct imports, things semi-work with the latest flax (eg cda7a4c85bbce744e412ab82e298ddf76d4770d2) but trying to pull things forward myself exposes various library dependency mismatches.

Is there a better way to upgrade this?  Testing ROCm 5.2 for https://github.com/google/jax/issues/2012.

```
python3 main.py --workdir=./imagenet --config=configs/default.py
2022-08-16 21:19:25.121102: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/code/flax/examples/imagenet/main.py", line 29, in <module>
    import train
  File "/code/flax/examples/imagenet/train.py", line 32, in <module>
    from flax.training import dynamic_scale as dynamic_scale_lib
ImportError: cannot import name 'dynamic_scale' from 'flax.training' (/usr/local/lib/python3.9/dist-packages/flax/training/__init__.py)
```

**Comment by andsteing** [comment]
Thanks for flagging this. We first need to release the latest version `v0.6.0` in a pip package. Updating JAX/Flax versions in the examples should then solve the issue.

**Comment by brettkoonce** [comment]
no rush, thanks for looking into it! 🦾

**Comment by andsteing** [comment]
#2405 should fix this ... @brettkoonce you can already check it out if you want to run the imagenet example

**Comment by brettkoonce** [comment]
@andsteing thank you that seems to fix things!  i am hitting something in absl but i think that it is over here: https://github.com/google/jax/issues/11972

**Comment by brettkoonce** [comment]
@andsteing confirmed working with a new jax build, thanks again!
