### ISSUE TITLE
Unnecessary assert in `merge_param`

### ISSUE THREAD

**Issue by tflahaul** [google/flax#2421]
https://github.com/google/flax/blob/14dffa6dbe3419acf4bc9ec9459a426cf61d6079/flax/linen/module.py#L1602

I believe this assert to be unnecessary as the check for `b` when `a` is None has already been done a few lines above.

**Comment by cgarciae** [comment]
Only reason I see to do this is because the type checker cannot infer `b` is of type `T` without that assert, else I agree that its not logically required.

**Comment by jheek** [comment]
Indeed, if I recall correctly this was required for type inference with pytype. I'll close this for now as the assert itself doesn't hurt.
