### ISSUE TITLE
[Accessibility] Enable EPUB output on ReadTheDocs

### ISSUE THREAD

**Issue by NightMachinery** [google/flax#2463]
Currently there is only HTML output [enabled](https://readthedocs.org/projects/flax/downloads/). It would be great if EPUB and PDF could also be enabled.

**Comment by coddiw0mple** [comment]
Mind if I do it? It's a really small fix, just gotta add 
```

  - epub
  - pdf
 
```
To the .readthedocs.yml under `formats:`
