### ISSUE TITLE
from_state_dict is too lenient 

### ISSUE THREAD

**Issue by cgarciae** [google/flax#2474]
I was checking #1261 and found this pattern:
```python
with open(model_file, "rb") as state_f:
  state = from_bytes(AwesomeModel, state_f.read())
```
However setting `target` to a regular `Module` subclass type in `from_bytes` just results in no checks being performed as state is returned as is for unregistered types:

https://github.com/google/flax/blob/6fd24460e88c833fa481228582937c692e9c182c/flax/serialization.py#L63-L64

Using an unregistered type just gives a false sense of security that validation is happening, it would be more correct to accept `target=None` as a way of opting-out of this check but anything else should require the type to be registered.

**Comment by jheek** [comment]
Agree

**Comment by cgarciae** [comment]
cc @patrickvonplaten

**Comment by cgarciae** [comment]
Proved more complex than expected to try to fix `from_state_dict` it feels as if there are two possible versions for this function, one which is lenient and is used extensively through the code base to check structures, another one which could be made more strict and could be targeted towards adding safety for end users when de-serializing. There is no easy way to reconcile both modes without significant changes, therefore I'll be closing this issue.
