### ISSUE TITLE
unbind API

### ISSUE THREAD

**Issue by cgarciae** [google/flax#2478]
As suggested in https://github.com/google/flax/pull/2394#discussion_r978744557, its currently not clear for users that `clone` produces an unbounded copy of the module. To get hold of a submodule and its variables you currently have to use this pattern:

```python
module, variables = load_module()
bounded_module = module.bind(variables)
submodule = bounded_module.some_submodule.clone()
submodule_variables = bounded_module.variables
```
The new proposed `.unbind()` method provide more clarity on how to do this process:

```python
module, variables = load_module()
submodule, submodule_variables = module.bind(variables).some_submodule.unbind()
```
Signature could be:
```python
unbind(self, **clone_kwargs) -> Tuple[Module, FrozenVariableDict]
```

cc @jheek

**Comment by marcvanzee** [comment]
How about `unbind()`?

**Comment by marcvanzee** [comment]
@cgarciae Just so you won't be confused, I renamed the issue "snapshot API" --> "unbind API"

**Comment by cgarciae** [comment]
Perfect, edited the original comment with the new name.
