### ISSUE TITLE
`./howtos/scripts/pack_howto_diffs.sh` adds all untracked files, not just files shown to user

### ISSUE THREAD

**Issue by danielsuo** [google/flax#249]
Issue is straightforward:
- `./howtos/scripts/pack_howto_diffs.sh` gives a warning stating which files will be packed into a diff
- Later, it runs `git add .` on all untracked files

Was surprised when my `.vim` and `environment.yml` files got packed in.

Not sure what folks would like the solution to be since this gets to what is fair game for a `howto` diff (e.g., which directories can in touch).

**Comment by danielsuo** [comment]
Er, started a bug template, but then deleted; didn't realize it would add a label. That's a bit aggressive IMO, but I can't remove.

**Comment by danielsuo** [comment]
It looks like at minimum, packing the `examples`. It didn't sound like folks wanted examples or howtos to modify core code, but I'm not sure. I could imagine also packing `tests` in case we want unit tests for `howto`s / we need to modify existing tests (that might be a no-no).

**Comment by avital** [comment]
> That's a bit aggressive IMO, but I can't remove the bug label.
Yeah, we need other types of labels...

**Comment by avital** [comment]
It's OK to assume that HOWTOs only affect examples/. In fact, we already
assume that in `pack_howto_diffs.sh`.

**Comment by avital** [comment]
`tests/` can't depend on examples (by design) so it should only be necessary to run the particular tests for the example being changed by the howto.

(Right now each HOWTO modifies a single example, and I think that's probably the way we'll go, in case that assumption helps the scripting in any way)

**Comment by danielsuo** [comment]
> > That's a bit aggressive IMO, but I can't remove the bug label.
> 
> Yeah, we need other types of issue templates...

Ah, oops, I meant this particular issue is too aggressively labeled a bug; I think the template is fine.

> It's OK to assume that HOWTOs only affect examples/. In fact, we already assume that in `pack_howto_diffs.sh`.

Yep! Just meant that `git add .` then adds more stuff into the commit besides just the changes to the example.

> `tests/` can't depend on examples (by design) so it should only be necessary to run the particular tests for the example being changed by the howto.
> 
> (Right now each HOWTO modifies a single example, and I think that's probably the way we'll go, in case that assumption helps the scripting in any way)

Perfect!
