### ISSUE TITLE
nn.Sequential causes persistent GPU arrays across loop iterations

### ISSUE THREAD

**Issue by zhangqiaorjc** [google/flax#2493]
A JAX GPU user reported seeing GPU OOM with a simple program that uses nn.Sequential in https://github.com/google/jax/issues/12575

If the repro doesn't use `model = nn.Sequential([nn.Dense(50)]` and does `model = nn.Dense(50)`, then the OOM goes away, and debugging info shows that persistent GPU arrays are gone as well.

nn.Sequential is quite simple, it's unclear what's holding onto the python references

Repro is in the linked JAX issue

**Comment by zhangqiaorjc** [comment]
@levskaya

**Comment by zhangqiaorjc** [comment]
@mattjj and I discovered that this `_caches` is leaking references.

https://github.com/google/flax/blob/main/flax/linen/module.py#L510-L511

cc @jheek as well

**Comment by levskaya** [comment]
closing for now - but we can re-open if this hasn't fixed the original memory issue.
