### ISSUE TITLE
Some more fleshed out instructions for resolving a HOWTO conflict

### ISSUE THREAD

**Issue by danielsuo** [google/flax#250]
From my own (limited) experience just now. Happy to write this up more cleanly/thoroughly in the "HOWTOs HOWTO" doc, but wasn't sure if others had best practices to share.

## Start with clean master
For example:
```bash
git checkout master
git fetch upstream
git rebase upstream/master
```

## Apply the hunks we can
The `--reject` flag tells `git apply` to apply whatever hunks in the supplied diff file it can and outputs the rejected hunks to a `*.rej` file.

```bash
git apply $diff_file --reject
```

## Go through the remaining hunks manually
Just open up text editor to make the changes

## Re-pack the HOWTO
Overwrite the existing one
```bash
./howtos/scripts/pack_howto_diffs.sh
```

**Comment by avital** [comment]
Yes please do improve out HOWTO HOWTO based on this experience report, thanks!!
