### ISSUE TITLE
Flax readthedocs website doesn't have any docs for ```save_checkpoint_multiprocess```. 

### ISSUE THREAD

**Issue by lucaslingle** [google/flax#2504]
The Flax readthedocs website references ```flax.training.checkpoints.save_checkpoint_multiprocess``` in the docs for ```flax.training.checkpoints.save_checkpoint```, and it appears in the source code linked by the readthedocs website, complete with a docstring. 

However, Flax readthedocs website [doesn't](https://flax.readthedocs.io/en/latest/api_reference/flax.training.html) [have](https://flax.readthedocs.io/en/latest/search.html?q=save_checkpoint_multiprocess) any docs for ```flax.training.checkpoints.save_checkpoint_multiprocess```.

**Comment by IvyZX** [comment]
Great catch! Making https://github.com/google/flax/pull/2519 now.
