### ISSUE TITLE
Error with save_checkpoint

### ISSUE THREAD

**Issue by cmoyacal** [google/flax#2506]
Provide as much information as possible. At least, this should include a description of your issue and steps to reproduce the problem. If possible also provide a summary of what steps or workarounds you have already tried.

### System information
- OS: Ubuntu
- Flax version: 0.6.1
- Jax version: 0.3.17 
- jaxlib version:  0.3.15+cuda11.cudnn805  
- Python version: 3.7.14

### Problem you have encountered:
I have been trying to save a train_state using checkpoints.save_checkpoint. To check if my code was not the problem, I used the following code you guys posted on one of your discussions: 

```
import jax.numpy as jnp
import jax
import flax
import flax.linen as nn
from flax.training import train_state, checkpoints
import optax
import numpy as np


class Net(nn.Module):
    features: int

    @nn.compact
    def __call__(self, x):
        x = nn.Dense(self.features)(x)
        x = nn.Dense(self.features)(x)
        return x


model = Net(features=2)
params = model.init(jax.random.PRNGKey(0), jnp.ones((1, 2)))

tx = optax.adam(learning_rate=0.0001)
state = train_state.TrainState.create(apply_fn=model.apply,
                                      params=params,
                                      tx=tx)


CKPT_DIR = 'ckpts'
checkpoints.save_checkpoint(ckpt_dir="./", target=state, step=0)
restored_state = checkpoints.restore_checkpoint(ckpt_dir=CKPT_DIR, target=state)

assert jax.tree_util.tree_all(jax.tree_multimap(lambda x, y: (x == y).all(), state.params, restored_state.params))
```
However, I got the same error (described below)

### Logs, error messages, etc:
AttributeError                            Traceback (most recent call last)
[<ipython-input-11-2aced07bedc2>](https://localhost:8080/#) in <module>
     28 
     29 CKPT_DIR = 'ckpts'
---> 30 checkpoints.save_checkpoint(ckpt_dir="./", target=state, step=0)
     31 restored_state = checkpoints.restore_checkpoint(ckpt_dir=CKPT_DIR, target=state)
     32

[/usr/local/lib/python3.7/dist-packages/flax/serialization.py](https://localhost:8080/#) in _np_convert_in_place(d)
    251   if isinstance(d, dict):
    252     for k, v in d.items():
--> 253       if isinstance(v, jax.Array):
    254         d[k] = np.array(v)
    255       elif isinstance(v, dict):

AttributeError: module 'jax' has no attribute 'Array'

### Steps to reproduce:
Colab link: https://colab.research.google.com/drive/1TgOt-ERfSRXXEFyfUAQxmWK0ERqMPLNf?usp=sharing

**Comment by lucaslingle** [comment]
You can upgrade jax to 0.3.18 or newer, and the error should resolve itself!

The jax.Array type was introduced in that version, see https://jax.readthedocs.io/en/latest/changelog.html

**Comment by cgarciae** [comment]
This is correct, `jax` recently deprecated some APIs and created new ones, please upgrade to the latest version of `jax` and `flax`.

**Comment by cgarciae** [comment]
Closing the issue assuming this assessment is correct, but feel free to reopen it if you continue to face the problem.
