### ISSUE TITLE
An error happened but i just import checkpoints

### ISSUE THREAD

**Issue by zhywanna** [google/flax#2542]
### System information
- OS Platform and Distribution:Linux Ubuntu
- Flax=0.6.1, jax=0.3.23, jaxlib=0.3.15 tensorflow=2.10.0
- Python version:3.8.8
- GPU/TPU model and memory: Quadro RTX 8000
- CUDA version (if applicable): 10.1

### Logs, error messages, etc:
![image](https://user-images.githubusercontent.com/47680024/196376527-5663f7b1-359b-446b-9de8-645b55e7fc77.png)

Is there any version miss matching or something? Please help me out !

**Comment by jheek** [comment]
It looks like there is a version mismatch between NumPy and TensorFlow. Could you update NumPy and see if it works?

**Comment by zhywanna** [comment]
I solved it by `upgrade numpy to 1.23.4 and downgrade tensorflow to 2.9.2`. Thanks!
