### ISSUE TITLE
Assign maintainers for HOWTOs

### ISSUE THREAD

**Issue by danielsuo** [google/flax#260]
From #256:

> Bringing an earlier discussion with @avital and @Marvin182 back here: I think it makes sense to have maintainers for howtos. They are examples in their own right and may occasionally take non-trivial effort to keep up-to-date.

Perhaps this should be rolled into the proposal in #231.

**Comment by avital** [comment]
Let's wait on this until we see how much the burden is on collaborators to fix HOWTOs when they break. Hopefully, that's uncommon, and the burden is low so this may be premature.

**Comment by avital** [comment]
At the moment, we haven't ported our HOWTOs to Linen and are considering instead using small design notes for these, so I'll close this issue for now.
