### ISSUE TITLE
cannot import name 'dataclass_transform' from 'typing_extensions' while using TPU

### ISSUE THREAD

**Issue by deadsoul44** [google/flax#2605]
### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 524ec3303516 5.15.65+ https://github.com/tensorflow/tensorflow/issues/1 SMP Thu Nov 10 10:13:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`: flax -> 0.6.1, jax & jaxlib -> 0.3.24
- Python version: 3.7.12
- GPU/TPU model and memory: TPU v3-8 (kaggle env.)
- CUDA version (if applicable):

### Problem you have encountered:
error while importing flax

### What you expected to happen:
import flax without any error

### Logs, error messages, etc:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_19/1030813116.py in <module>
      5 import tensorflow_datasets as tfds
      6 from absl import logging
----> 7 import flax
      8 from flax import linen as nn
      9 from flax.training import train_state

/opt/conda/lib/python3.7/site-packages/flax/__init__.py in <module>
     16 """Flax API."""
     17 
---> 18 from . import core
     19 from . import jax_utils
     20 from . import linen

/opt/conda/lib/python3.7/site-packages/flax/core/__init__.py in <module>
     26 )
     27 
---> 28 from .scope import (
     29   Scope as Scope,
     30   Array as Array,

/opt/conda/lib/python3.7/site-packages/flax/core/scope.py in <module>
     26 from flax import config
     27 from flax import errors
---> 28 from flax import struct
     29 from flax import traceback_util
     30 from .frozen_dict import freeze

/opt/conda/lib/python3.7/site-packages/flax/struct.py in <module>
     23 
     24 import jax
---> 25 from typing_extensions import dataclass_transform  # pytype: disable=not-supported-yet
     26 
     27 

ImportError: cannot import name 'dataclass_transform' from 'typing_extensions' (/opt/conda/lib/python3.7/site-packages/typing_extensions.py)

### Steps to reproduce:
import flax in Kaggle TPU environment.

**Comment by cgarciae** [comment]
Hey @deadsoul44, I did get your error by running
```
! pip install -U flax jax jaxlib
```
followed by
```python
import flax
```
However, just clicking on `Restart & clear all outputs` fixed it, I was able run `import flax` without errors.

**Comment by deadsoul44** [comment]
Hi, thanks for the workaround. But it is not useful when saving and running the Kaggle notebook.

**Comment by cgarciae** [comment]
Not sure exactly what causes this error but it has nothing to do with Flax per se, try reporting this to the Kaggle team.

**Comment by deadsoul44** [comment]
Thanks a lot. I opened an issue in Kaggle repo. You can close this one if you think it is not related to Flax.
