### ISSUE TITLE
BatchNorm should ignore self.axis_name when not running under `pmap`

### ISSUE THREAD

**Issue by IvyZX** [google/flax#2606]
Currently user need to pass `axis_name=None` when not running under pmap, otherwise BatchNorm will throw error. Ignoring it automatically when such axis is not available (i.e. not under pmap) will relieve user from the hassle.

**Comment by cgarciae** [comment]
What if users have a typo and this is silently ignored?

**Comment by IvyZX** [comment]
This is a fair point. We should at least log warning messages when ignoring an axis_name. 

I wonder if there are better ways to see if we are inside a pmap - like only ignore the `axis_name` when there's no logical axis available at all. Perhaps I should ask JAX people if this idea makes sense.

**Comment by marcvanzee** [comment]
@IvyZX I don't really get it, `axis_name=None` is the default so users do not have to pass it right? Could you provide a MWE of the problem?
