### ISSUE TITLE
Promoting certain HOWTOs to examples

### ISSUE THREAD

**Issue by danielsuo** [google/flax#261]
From #256:

> I know howtos are fairly baked into flax at this point, but I wonder whether we should consider making more howtos into their own examples. The maintenance effort may actually be lower (i.e., don't need to understand the howto mechanism; have to edit each one in either case) and it may be easier for users to find / use (i.e., don't need to apply diffs or go to other branches).

> For example, the distributed training example seems fairly important to easily access and although the code is essentially a copy of mnist, its purpose is fundamentally different (i.e., not just showing a variation of mnist).

Perhaps this should be rolled into the proposal in #231.

**Comment by danielsuo** [comment]
Caveat: I don't know the full context behind howtos, but sharing some "in-the-field" experience to put a finer point on the initial comment.

For the users, accessing the examples is harder; I first need to become aware of `howtos` (vs. just navigating to `examples`), then I need to figure out how to access those `howtos`.

For the maintainers, the `howto mechanism` complicates life a little bit, but is not the fundamental issue; rather, maintaining "branched" examples (e.g., `distributed-training`) on top of moving "base" examples (e.g., `mnist`) is just going to be challenging. Hopefully this settles down as examples like `mnist` settle.

**Comment by avital** [comment]
I think there are a few issues here:

1. Discoverability of HOWTOs. We should fix this, e.g. each example should link to their HOWTOs at the top of the README and/or HOWTOs should be visible directly on the left pane in ReadTheDocs.

2. What is the best way to show people "this is how you do distributed training in JAX/Flax". I still think showing real diffs are ideal here -- you have to modify a real training loop and that requires changes in more than one place. We could write a stand-alone doc for "distributed training" but I'm having a hard time seeing how that would be clearer or easier to maintain than a HOWTO

3. Regarding promoting to a full example, that seems like even higher maintenance burden than what we have now. Every time JAX or Flax APIs change, or any time we change patterns in our examples, we have to update two places. With HOWTOs, most/some of the time the same diff cleanly applies and you're told explicitly when it doesn't.

Curious what you think @danielsuo -- if HOWTOs were clearly discoverable from both the example READMEs as well as from ReadTheDocs would this still be an issue?

**Comment by danielsuo** [comment]
1. Discoverability: more links in more places would be helpful. I'm not sure it makes sense that in order to know about distributed training, I should first know to go to mnist, but this is easy to resolve. There is also a related point about accessibility: in order to use a `howto`, I need to navigate to another branch or apply a diff. The former can be resolved with links, the latter probably doesn't matter.

2. Showing: I agree that a diff is really succinct and conceptually, I think, what we want, but a literal diff may not be what people are used to consuming. I think this is also easy to resolve with low-overhead docs (e.g., read `mnist` documentation as background, here are the changes and how they work).

3. Maintenance: Partially agree. In the worst case, we have to update example and all underlying `howtos`, but as noted from my "in-the-field" experience, this isn't a limitation because without diffs, we need to update all these files every change no matter what.

At the end of the day, the `howto` mechanism is fine, but it does break with my [user hat] expectations because I've never seen such a thing before. For example, this mechanism could be transparent to me as the user:

- From the user's perspective, each `howto` is an example
- `howto` directory in examples (E.g., `examples/distributed-training`) contains 1) the diff from its base example and 2) the "low-overhead" doc described above
- From maintainer's perspective, `howto` mechanism continues to exist

The downside, of course, is more top-level examples and I am not at all familiar with what is in scope for a `howto`. If they are as "fundamental" as distributed training or ensembling, I think this is appropriate, but there may be more minor variations.

Anyway, no dog in this fight, just sharing opinions!

**Comment by dynamicwebpaige** [comment]
Is there anything that we could do to heighten SEO for `howto`s, or to encourage cross-posting on blog sites that **do** have good SEO (Medium, TowardsDataScience, etc.)? 

It might also make sense to have a community-maintained markdown file on Github with interesting JAX + Flax examples ([example](https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks)).

**Comment by danielsuo** [comment]
SEO is definitely something to think about, but before that, the place SEO
lands you on might not be easily consumable (e.g., `git diff` output), even
for someone comfortable with diffs. There isn't much context at the moment
for the `howto`s (e.g., motivation, what various changes might be doing).

In any case, just wanted folks to keep in mind without harping on it too
much since its maybe a little early to commit to some documentation plan.

**Comment by avital** [comment]
I think we should iterate towards increased visibility and discoverability of HOWTOs and then revisit this. I'll find time to chat with @danielsuo and @marcvanzee about a concrete proposal.

**Comment by danielsuo** [comment]
Tagged with `revisit-monthly` since there's no immediate action (at least until we speak next week). Let me know if this tag was meant to be used in some other way.

**Comment by avital** [comment]
Thanks Daniel, yeah that's how we plan to use `revisit-monthly`

**Comment by avital** [comment]
At the moment, we haven't ported our HOWTOs to Linen and are considering instead using small design notes for these, so I'll close this issue for now.
