### ISSUE TITLE
CIFAR10/ImageNet examples incorrectly calculate test metrics with default batch size

### ISSUE THREAD

**Issue by yanii** [google/flax#262]
If I understand the current example code for CIFAR10 and ImageNet, it calculates the test metrics by first taking the mean over the mini-batch in each step, and then taking the mean over all steps, i.e. calculating the mean of means:

https://github.com/google/flax/blob/58e340bee4dc12415ea9a46e59056c6f4f1b5527/examples/cifar10/train.py#L119-L127
https://github.com/google/flax/blob/58e340bee4dc12415ea9a46e59056c6f4f1b5527/examples/cifar10/train.py#L265-L276

When all mini-batches are of the same size this is equivalent to the mean of the metrics over all data samples, however in the case where mini-batches differ in size this is not equivalent to the mean of the samples. This is of course the case typically when test data set is not evenly divisible by the batch size — and this is the case in both the CIFAR and ImageNet examples currently.

If my understanding of this is correct, both the CIFAR10/ImageNet examples the test metrics are likely currently being calculated incorrectly.

There are a number of solutions, the simplest is probably to instead use a weighted mean, i.e. weighting the metrics by the batch size for each step, and then taking the mean over the weighted metrics over all batches:

```diff
diff --git a/examples/cifar10/train.py b/examples/cifar10/train.py
index b9e0b2d..8643939 100644
--- a/examples/cifar10/train.py
+++ b/examples/cifar10/train.py
@@ -270,10 +270,10 @@ def train(module, model_dir, batch_size,
         eval_batch = load_and_shard_tf_batch(eval_batch)
         # Step
         metrics = p_eval_step(optimizer.target, state, eval_batch)
-        eval_metrics.append(metrics)
+        eval_metrics.append(jax.tree_map(lambda x: len(eval_batch) * x, metrics))
       eval_metrics = common_utils.get_metrics(eval_metrics)
       # Get eval epoch summary for logging
-      eval_summary = jax.tree_map(lambda x: x.mean(), eval_metrics)
+      eval_summary = jax.tree_map(lambda x: x.sum()/data_source.EVAL_IMAGES, eval_metrics)
 
       # Log epoch summary
       logging.info(
```
Alternatively the batch vector of metrics could be returned and accumulated (probably a performance hit?) or the CIFAR10 example could be changed to use a different compatible test batch size to prevent this, but this would not work for the ImageNet example in general over multiple devices, and doesn't serve the primary purpose of this code which is to be a good starter/example of training.

**Comment by avital** [comment]
At the moment we actually drop the final batch (https://github.com/google/flax/blob/master/examples/imagenet/input_pipeline.py#L222) -- was also pointed out by #263, so the metrics are indeed misreported but for a different reason than described here.

I agree that we should fix this, but in general I'd prefer we just encapsulate a small "metrics" utility class that deals with this cleanly.

That being said, if you want to give a shot at fixing the input pipeline to not drop the final batch, as well as computing metrics correctly with the current example code, we'll be have to review a PR.

**Comment by yanii** [comment]
Sure, would be happy to try and address this after the NeurIPS deadline next week :-)

**Comment by avital** [comment]
Thanks @yanii! Keep us posted if you have any questions.

**Comment by yanii** [comment]
@avital CCed you internally on the bug tracking CLA approval

**Comment by andsteing** [comment]
Thanks for filing this issue!

I have created #527 that describes the problem in more detail and sketches a solution.
