### ISSUE TITLE
Use new CI runners

### ISSUE THREAD

**Issue by cgarciae** [google/flax#2620]
Use larger test runners provided by Google. Figure out how to config `build.yaml` to use them.
@levskaya says:
> I think it's a one-line change
something like "runs on" directive
it's in the docs somewhere but I've forgotten the line

**Comment by cgarciae** [comment]
Additionally, run `pytype` tests in parallel via bash sub-processes to leverage the additional cores.

**Comment by marcvanzee** [comment]
Fixed by #2635
