### ISSUE TITLE
ImageNet Example does not eval on the entire validation set

### ISSUE THREAD

**Issue by georgedahl** [google/flax#263]
### Problem you have encountered:

Load split https://github.com/google/flax/blob/master/examples/imagenet/input_pipeline.py#L180
drops the remainder when the batch size doesn't evenly divide the validation set size. 
https://github.com/google/flax/blob/master/examples/imagenet/input_pipeline.py#L222

The default batch size is 128 which doesn't evenly divide the ImageNet validation set of 50,000 images, but even if the default batch size evenly divided the number of validation images, the code would be fragile without a way to handle the final partial batch correctly.

### What you expected to happen:

All validation data should be used in evals.

**Comment by georgedahl** [comment]
I now see that https://github.com/google/flax/issues/262 mentions a similar issue.

**Comment by jheek** [comment]
duplicate, closing in favor of #262
