### ISSUE TITLE
Improve `Module.init()` docstring

### ISSUE THREAD

**Issue by marcvanzee** [google/flax#2653]
Right now the docstring of [`Module.init()`](https://github.com/google/flax/blob/df7fa7eed9965ab5117a50eee2813b8dc7c90426/flax/linen/module.py#L1351) is very short. It should explain much more and give more examples, including:

* Explain that users can pass both `{"params": rng}` as well as `rng` in case the only RNG used is the one for variable collection `params` (also link to the [Variables](https://flax.readthedocs.io/en/latest/api_reference/flax.linen.html#module-flax.core.variables) documentation).
* Give a few examples of how to use the various arguments.

We may have to change the docstring once #2428 is in as well.

**Comment by 8bitmp3** [comment]
Add me as a reviewer @zaxtax . We currently have to remind/teach users how to use `init` and `apply` in our notebooks/guides, while referencing the API docs for both (which don't go further i.t.o. explaining). This is a great Issue @marcvanzee .
