### ISSUE TITLE
Positional Embeddings in WMT Example

### ISSUE THREAD

**Issue by chitwansaharia** [google/flax#268]
I had a question regarding positional embeddings in wmt example (`flax/examples/wmt/models.py`)

`apply` function `AddPositionEmbs` calls the `sinusoidal_init` function for getting the positional embeddings (fixed position embedding mode). Code [here](https://github.com/google/flax/blob/aff10f032e892e28a1acf4dd4ee9dcc6cd39a606/examples/wmt/models.py#L110). 

Does this result in positional embeddings getting created everytime we call apply function ? If that is the case, then is there some work around, so that we only call it once for creation say for a specified `max_len` ?

I guess in this case, it wouldn't be expensive to create embeddings at every step, but I had a use case, where I want to use fixed embeddings loaded from a numpy file. In that case, I can't afford calling it again and again. From what I understand, one way of achieving this could be loading it in the main file, and assigning it as a fixed argument in `.partial` call for the model. But, I am again not sure, if that is the best way to do this.

**Comment by levskaya** [comment]
Hi!  Are you calling this function outside of a jit every time?  If you jit this function then the constant will be folded-out.  If you're trying to load your own constant embedding table, you can always just pass it as a constant argument or just call a function that returns the constant, which again under jit will be constant-folded out and saved on-device.
Let me know if that's clear or not!

**Comment by chitwansaharia** [comment]
Got it. Didn't know this constant folding out property of jit functions. Thanks @levskaya.
