### ISSUE TITLE
Add glossary page in flax docs

### ISSUE THREAD

**Issue by chiamp** [google/flax#2681]
I think the flax docs can benefit from a glossary page, similar to the one that [Jax](https://jax.readthedocs.io/en/latest/glossary.html) has. Some terms we can add can include: [Variable / variable dict](https://flax.readthedocs.io/en/latest/api_reference/flax.linen.html?highlight=variables#module-flax.core.variables), params, and collections. Depending on the user's background, they may confuse "variables" and "parameters" as being either synonymous or having different meanings compared to the way it is defined in Flax.

**Comment by cgarciae** [comment]
I like the idea! There are also the "RNG collections" (at least that is what I call them).

**Comment by 8bitmp3** [comment]
+1

Can also start working on this @chiamp if you need help.

This is related to @marcvanzee :

https://github.com/google/flax/pull/2671#issuecomment-1333676404

> We currently have already three "introduction" tutorials: [Flax Basics](https://flax--2671.org.readthedocs.build/en/2671/guides/flax_basics.html), [Getting Started](https://flax--2671.org.readthedocs.build/en/2671/getting_started.html), and [Linen intro](https://github.com/google/flax/blob/main/docs/notebooks/linen_intro.md). @8bitmp3 is planning on merging these into one tutorial.

Things like "train state/`TrainState`" aren't 100% self-explanatory at the moment.

**Comment by chiamp** [comment]
> Can also start working on this @chiamp if you need help.

Sure thing, I can start a draft doc to see what terms to put in.
