### ISSUE TITLE
Cannot serialize jax Arrays with flax for checkpointing, with jax_array=True

### ISSUE THREAD

**Issue by wookayin** [google/flax#2696]
Linked to google/jax#13540.

<details>
<summary>System Information</summary>

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OS independent
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`: jax 0.3.25, 0.4.0-HEAD
- Python version: 3.10, 3.11
- GPU/TPU model and memory: N/A
- CUDA version (if applicable): N/A

</details>

### Problem you have encountered:

Flax uses `msgpack` to serialize an object and make checkpoints of jax arrays. With the new ["jax.Array"](https://jax.readthedocs.io/en/latest/jax_array_migration.html), msgpack would raise an error while serializing a jax Array.

```
import jax.numpy as jnp
from flax import serialization

s = jnp.zeros(5)
t = serialization.msgpack_serialize(s)
print(len(t))
```

### What you expected to happen:

This code should work with no problem, printing 36 (in jax 0.3.25 or with `jax.config.update("jax_array", False)`.

### Logs, error messages, etc:

Trace:
```
 File "jaxbug.py", line 5, in <module>
    t = serialization.msgpack_serialize(s)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/flax/serialization.py", line 334, in msgpack_serialize
    return msgpack.packb(pytree, default=_msgpack_ext_pack, strict_types=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/msgpack/__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 291, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Array' object
```

## Other useful resources

Probably we need to use a custom data type handler: https://github.com/msgpack/msgpack-python#packingunpacking-of-custom-data-type

**Comment by yashk2810** [comment]
@levskaya @IvyZX

**Comment by jakevdp** [comment]
Flax updated its msgpack serialization to support `jax.Array` in this commit on Sept 26: https://github.com/google/flax/commit/6dba29098fba23a457e87f104bfef2704dbf54cd

I suspect your version of flax is older than this. Try updating flax to version 0.6.1 or newer.
