### ISSUE TITLE
Jax determinism on GPU

### ISSUE THREAD

**Issue by dgrangier** [google/flax#2700]
I have trouble with determinism for Jax code on GPU but not on CPU. This is easy to reproduce from the flax examples https://github.com/google/flax/tree/main/examples . 

From https://github.com/google/jax/issues/565, I had the impression that setting 
TF_DETERMINISTIC_OPS=1 and
TF_CUDNN_DETERMINISTIC=1 
would make the GPU run deterministic.

After 2 steps, the MNIST example give the same results on GPU or CPU:

4bda0ea4f536031c4619c394b64ede43 /tmp/mnist_cpu_1/checkpoint_1
4bda0ea4f536031c4619c394b64ede43 /tmp/mnist_cpu_2/checkpoint_1
1daae8e25344c91aea35c4836b46c798 /tmp/mnist_gpu_1/checkpoint_1
1daae8e25344c91aea35c4836b46c798 /tmp/mnist_gpu_2/checkpoint_1

This is not the case for the WMT transformer example where only the CPU run are deterministic.

cbcf1e88ed7b2bd61376e3c90c5dcdfc /tmp/wmt_cpu_1/checkpoint_1
cbcf1e88ed7b2bd61376e3c90c5dcdfc /tmp/wmt_cpu_2/checkpoint_1
3dd11fb219e9f37dd90542267cadc86e /tmp/wmt_gpu_1/checkpoint_1
3067f6d66fdf7e8b52baef7056422291 /tmp/wmt_gpu_2/checkpoint_1

Is this expected? Am I missing some flags to make my GPU run deterministic?

BTW I have the following setup CuDNN 8.4, tf = 2.11.0, jax = 0.3.13, flax = 0.5.3

**Comment by dgrangier** [comment]
Also filled as a Jax issue, see https://github.com/google/jax/issues/13672

**Comment by cgarciae** [comment]
Hey @dgrangier! I think we should track this on this JAX repo as Flax itself just leverages JAX for RNGs so we can't do anything on our side. Closing this issue.
