### ISSUE TITLE
Making use of module method in .apply

### ISSUE THREAD

**Issue by bayerj** [google/flax#271]
I am trying to access a module method of a module within the apply method of a containing module. 

Here is a minimal example. This scenario is synthetic, I am just creating a module `Multiplier` that multiplies the input with a paramteric scalar. Its inverse `.inv` (dividing by that scalar) is implemented with the `@nn.module_method` decorator. A container class `Container` is supposed to make use of a `Multiplier`. I would also like to use the inverse method `.inv` during `apply` of `Container`.

```python
import jax
import jax.numpy as jnp
import flax.optim as optim
import flax.nn as nn

class Multiplier(nn.Module):
    def apply(self, inpt):
        factor = self.param('factor', (1,), jax.nn.initializers.ones)
        return inpt * factor

    @nn.module_method
    def inv(self, inpt):
        factor = self.get_param('factor')
        return inpt / factor


class Container(nn.Module):
    def apply(self, inpt):
        result = Multiplier(inpt, name='multiplier')
        # How can I apply Multiplier.inv here?
        return result
```

The "obvious" way of using `Multiplier.inv()` does of course not work, as it tries to access a parameter that does not exist yet: `ValueError: Parameter with name 'factor' does not exist.`. 

But I am not sure how I can trigger the creation of that parameter and having a reference to it afterwards. I could use `.init` and use `.call` subsequently, however that requires doing the bookkeeping of the paramters manually, which feels unsatsifying.

Is there a best practice for this?

**Comment by bayerj** [comment]
I found a workaround that seems to work. It is not entirely obvious from the docs, though:

```python
class Container(nn.Module):
  def apply(self, inpt):
    multiplier = Multiplier.shared()
    multiplier(inpt)  # init parameters
    return multiplier.inv(inpt)
```

**Comment by jheek** [comment]
Because `inv` uses `get_param` it needs `apply` to be called before `inv` to init the parameter. You could instead do the folowwing:

```
import jax
import jax.numpy as jnp
import flax.optim as optim
import flax.nn as nn

class Multiplier(nn.Module):
    def apply(self, inpt):
        return inpt * self._factor()

    @nn.module_method
    def inv(self, inpt):
        return inpt / self._factor()

    def _factor(self):
      return self.param('factor', (1,), nn.initializers.ones)


class Container(nn.Module):
    def apply(self, inpt):
        return Multiplier.inv(inpt, name='multiplier')
```

**Comment by AlexeyG** [comment]
Closing the issue due to inactivity. Please re-open if necessary.
