### ISSUE TITLE
Submit all relevant near-SoTA examples to paperswithcode.com

### ISSUE THREAD

**Issue by avital** [google/flax#272]

**Comment by j-towns** [comment]
Have added all of the examples which directly implement models/results from specific papers.

**Comment by avital** [comment]
Awesome @j-towns! Do you have a link handy to those on paperwithcode.com?

**Comment by j-towns** [comment]
This should list all of the papers for which I've added a flax example:
https://paperswithcode.com/search?q_meta=&q=flax
Note the 'Attention is all you need' paper links to two of our examples.
