### ISSUE TITLE
Make a guide for scan over layers

### ISSUE THREAD

**Issue by IvyZX** [google/flax#2752]
As discussed on PR https://github.com/google/flax/pull/2730, it could be helpful to have a separate guide for scan over layers, since it's a helpful but convoluted subject.

Once the guide is available, we can add its link to the https://github.com/google/flax/pull/2730 guide.

**Comment by 8bitmp3** [comment]
This is awesome, thanks @IvyZX

**Comment by IvyZX** [comment]
We got [transform guide](https://flax.readthedocs.io/en/latest/guides/transforms.html) for NNX now which covers scan over layers.
