### ISSUE TITLE
support kwargs in vmap

### ISSUE THREAD

**Issue by cnsgsz** [google/flax#2772]
### System information
Google colab

```
# Install the newest JAXlib version.
!pip install --upgrade -q pip jax jaxlib
# Install Flax at head:
!pip install --upgrade -q git+https://github.com/google/flax.git
```

### Problem you have encountered:
```
# Make RNG Keys and a fake input.
key1, key2 = random.split(random.PRNGKey(0), 2)
x = random.uniform(key1, (4,4))

BatchDense = nn.vmap(
    nn.Dense,
    in_axes=0, out_axes=0,
    variable_axes={'params': 0},
    split_rngs={'params': True})
model = BatchDense(features=3)

# provide key and fake input to get initialized variables
init_variables = model.init(key2, inputs=x)
```

```
WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
/usr/local/lib/python3.8/dist-packages/flax/core/lift.py:111: RuntimeWarning: kwargs are not supported in vmap, so "inputs" is(are) ignored
  warnings.warn(msg.format(name, ', '.join(kwargs.keys())), RuntimeWarning)
---------------------------------------------------------------------------
UnfilteredStackTrace                      Traceback (most recent call last)
[<ipython-input-3-c56518a68a88>](https://localhost:8080/#) in <module>
     12 # provide key and fake input to get initialized variables
---> 13 init_variables = model.init(key2, inputs=x)
     14
```

[lift.py:111](https://github.com/google/flax/blob/62617dbd760193bb0147bca4b06cddd6304b241a/flax/core/lift.py#L111)

### What you expected to happen:
Without keywords, `init` and `apply` become hard to read e.g. `deterministic=True`. Does it make sense for `vmap` to support kwargs?

Also, the warning message is easy to miss, and does not seem to appear when I run the code again. Does it make sense to throw an error?

**Comment by IvyZX** [comment]
After some investigation I believe this is intentional, because the underlying `jax.vmap` was not intended on kwargs. 

For example, the `in_axes` argument does not work on kwargs. See [documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.vmap.html) on `in_axes`: 
```
Arguments passed as keywords are always mapped over their leading axis (i.e. axis index 0).
```

That means you may get different results when passing an arg as kwarg to an `vmap`ped function. Like:

```
import jax

def f(x, y):
    return x + y + 1
f_vmap = jax.vmap(f, in_axes=1)
inputs = jax.numpy.arange(10).reshape(2, 5)

print(f_vmap(x=inputs, y=inputs*2))  # shape=(2, 5)
print(f_vmap(inputs, inputs*2))          # shape=(5, 2)
```
Which could be more confusing after Flax lifted transforms (`nn.vmap`). 

Hopefully this helps.
