### ISSUE TITLE
Module's `__repr__` not showing parents' fields in its attributes

### ISSUE THREAD

**Issue by JyChang012** [google/flax#2791]
### System information
- `macOS 13.1`
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`:
```
Name: flax
Version: 0.6.1
---
Name: jax
Version: 0.4.1
---
Name: jaxlib
Version: 0.4.1
```
- `Python 3.10.8`

### Problem you have encountered:
For a module inheriting other modules or dataclasses, when `__repr__` is called, it only prints its own fields, but none of its parent classes' fields, under `# attributes`. 
These fields are not the same as the signature of the generated `__init__` constructor either.

### What you expected to happen:
The `attributes` should have the same fields as the generated `__init__` constructor (without `parent` and `name`). From the module user's point of view, since I need to fill these attributes when init the module, I expect to see them all when printing the module.

### Steps to reproduce:
For the following example
```Python
from flax.linen import Module
from inspect import signature


class Base1(Module):
    p11: int
    p12: int


class Base2(Module):
    p21: int
    p22: int


class Model(Base2, Base1):
    a: int
    b: int


m = Model(1, 2, 3, 4, 5, 6)
```

If we `print(signature(m.__init__))`, we get
```
(p11: int, p12: int, p21: int, p22: int, a: int, b: int, parent: Union[Type[flax.linen.module.Module], Type[flax.core.scope.Scope], Type[flax.linen.module._Sentinel], NoneType] = <flax.linen.module._Sentinel object at 0x12b7d7700>, name: str = None) -> None
```
but for `print(m)`, we get
```
Model(
    # attributes
    a = 5
    b = 6
)
```
I think it should be
```
Model(
    # attributes
    p11 = 1
    p12 = 2
    p21 = 3
    p22 = 4
    a = 5
    b = 6
)
```

**Comment by JyChang012** [comment]
[A quick fix](https://github.com/google/flax/compare/main...JyChang012:flax:fix/repr_attributes) that uses `__dataclass_fields__` to find all fields

**Comment by JyChang012** [comment]
Feel free to close this if current behavior of `__repr__` is intended. @cgarciae

**Comment by cgarciae** [comment]
Hey @JyChang012, thanks for posting this! 
Using `__annotations__` was indeed a bad idea, I've opened as PR with a fix.
