### ISSUE TITLE
Incorporate RMSNorm

### ISSUE THREAD

**Issue by MechCoder** [google/flax#2849]
Is there interest to incorporate RMSNorm (https://arxiv.org/pdf/1910.07467.pdf) either as a seperate normalization module or to make LayerNorm configurable to switch off the centering? It is becoming quite popular as a faster alternative to LayerNorm that maintains performance and is used for example in Palm.

**Comment by marcvanzee** [comment]
Yes, I think it makes sense to support this in Flax. I think having a separate layer called RMSNorm makes sense, but it most likely can re-use use some of the shared normalization code we currently have for BatchNorm/LayerNorm.
