### ISSUE TITLE
Module.tabulate doesn't show activation layers.

### ISSUE THREAD

**Issue by zguo235** [google/flax#2850]
Provide as much information as possible. At least, this should include a description of your issue and steps to reproduce the problem. If possible also provide a summary of what steps or workarounds you have already tried.

### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Red Hat 8.2

- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`: 

Name: flax
Version: 0.6.4
Summary: Flax: A neural network library for JAX designed for flexibility
Home-page: https://github.com/google/flax
Author: Flax team
Author-email: flax-dev@google.com
License: 
Location: /home/ace14560le/venv/jax/lib/python3.10/site-packages
Requires: jax, matplotlib, msgpack, numpy, optax, orbax, PyYAML, rich, tensorstore, typing-extensions
Required-by: clu, orbax

Name: jax
Version: 0.4.2
Summary: Differentiate, compile, and transform Numpy code.
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: /home/ace14560le/venv/jax/lib/python3.10/site-packages
Requires: numpy, opt_einsum, scipy
Required-by: chex, clu, flax, optax, orbax

Name: jaxlib
Version: 0.4.2+cuda11.cudnn86
Summary: XLA library for JAX
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: /home/ace14560le/venv/jax/lib/python3.10/site-packages
Requires: numpy, scipy
Required-by: chex, clu, optax, orbax

- Python version: 3.10.4
- GPU/TPU model and memory: A100
- CUDA version (if applicable): 11.8

### Problem you have encountered:
Module.tabulate method doesn't show the activation layers.

### What you expected to happen:
Module.tabulate shows the activation layers like pytorch model.
```
import torchvision.models.resnet as resnet

model = resnet.resnet18()
print(model)
```
```
ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  **(relu): ReLU(inplace=True)**
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      **(relu): ReLU(inplace=True)**
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      **(relu): ReLU(inplace=True)**
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer2): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      **(relu): ReLU(inplace=True)**
```
### Steps to reproduce:
Whenever possible, please provide a *minimal example*. Please consider submitting it as a Colab link.

[When use relu as the activation layer](https://colab.research.google.com/github/google/flax/blob/master/docs/guides/flax_basics.ipynb#scrollTo=1sllHAdRlpmQ)

```
class ExplicitMLP(nn.Module):
  features: Sequence[int]

  def setup(self):
    # we automatically know what to do with lists, dicts of submodules
    self.layers = [nn.Dense(feat) for feat in self.features]
    # for single submodules, we would just write:
    # self.layer1 = nn.Dense(feat1)

  def __call__(self, inputs):
    x = inputs
    for i, lyr in enumerate(self.layers):
      x = lyr(x)
      if i != len(self.layers) - 1:
        x = nn.relu(x)
    return x

key1, key2 = random.split(random.PRNGKey(0), 2)
x = random.uniform(key1, (4,4))

model = ExplicitMLP(features=[3,4,5])
print(model.tabulate(key2, x))
```
Output:
![image](https://user-images.githubusercontent.com/33446677/216958580-95a73638-cb1b-4b46-b841-a2635fd6660b.png)

When use tanh as the activation layer:
```class ExplicitMLP(nn.Module):
  features: Sequence[int]

  def setup(self):
    # we automatically know what to do with lists, dicts of submodules
    self.layers = [nn.Dense(feat) for feat in self.features]
    # for single submodules, we would just write:
    # self.layer1 = nn.Dense(feat1)

  def __call__(self, inputs):
    x = inputs
    for i, lyr in enumerate(self.layers):
      x = lyr(x)
      if i != len(self.layers) - 1:
        x = nn.tanh(x)
    return x

key1, key2 = random.split(random.PRNGKey(0), 2)
x = random.uniform(key1, (4,4))

model = ExplicitMLP(features=[3,4,5])
print(model.tabulate(key2, x))
```
Output:
![image](https://user-images.githubusercontent.com/33446677/216959169-1d2b2277-baf6-4014-8979-58496ecf87c6.png)

The outputs of the two model are the same. To make the differences in the models clear, a line describing the activation layer should be inserted between the layers_0 and layers_1.

**Comment by cgarciae** [comment]
Hey @zguo235, currently activation function such as `nn.relu` or `nn.tanh` are not Flax Modules but just regular JAX functions which is why they don't appear in the `tabulate` summary. If want them to appear consider creating wrapper Modules like this e.g:

```python
class Relu(nn.Module):
  def __call__(self, x):
    return nn.relu(x)
```

**Comment by zguo235** [comment]
@cgarciae Thank you for the reply! I will close this issue as your answer solved my problem perfectly. However, I think the activation function should be Flax Module instead of just JAX functions. I know the flax.linen is stable and it may be difficult to change the type of activation functions, but as activation functions are also layers of neural network, the default method in nn.Module should be available in activation layers.
