### ISSUE TITLE
Unexpected ScopeParamNotFoundError when sharing submodules

### ISSUE THREAD

**Issue by kvablack** [google/flax#2864]
### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`: flax 0.6.5, jax 0.4.3, jaxlib 0.4.3+cuda11.cudnn82
- Python version: 3.10.8
- GPU/TPU model and memory: NVIDIA GeForce GTX 1080ti
- CUDA version (if applicable): 11.7

### Problem you have encountered:
I encounter a `ScopeParamNotFoundError` when a shared submodule is nested under an unshared submodule. Here is a minimal working example:
```python
class Shared(nn.Module):
    @nn.compact
    def __call__(self, x):
        return nn.Dense(1)(x)

class Unshared(nn.Module):
    shared: nn.Module

    def __call__(self, x):
        return self.shared(x)

class Super(nn.Module):
    a: nn.Module
    b: nn.Module

    def run_a(self, x):
        return self.a(x)

    def run_b(self, x):
        return self.b(x)
    
    def __call__(self, x):
        return self.a(x) + self.b(x)


sh = Shared()
a = Unshared(shared=sh)
b = Unshared(shared=sh)
super = Super(a=a, b=b)

rng = jax.random.PRNGKey(0)
params = super.init(rng, jnp.ones(1))["params"]

print(params)
# FrozenDict({
#   a: {
#       shared: {
#            Dense_0: {
#                kernel: Array([[0.13082343]], dtype=float32),
#                bias: Array([0.], dtype=float32),
#            },
#        },
#    },
# })
# 
# as expected, the weights for `shared` only appear under the `a` key, since by my understanding flax caches the
# `shared` object and re-uses the same scope when it's encountered for the second time

print(super.apply({"params": params}, jnp.ones(1)))  # works as expected
print(super.apply({"params": params}, jnp.ones(1), method="run_a"))  # works as expected
print(super.apply({"params": params}, jnp.ones(1), method="run_b"))  # ScopeParamNotFoundError: Could not find parameter named "kernel" in scope "/b/shared/Dense_0"
```

### What you expected to happen:
When I call `apply` with `method="run_b"`, I expect flax to realize that the weights for `/b/shared` are under the path `/a/shared`, just like it does when `__call__` is used, but clearly it is looking in the wrong scope.

Edit: After reading a bit more, I'm thinking this has something to do with lazy binding? When `__call__` is used, first `a.shared` is bound, and then when `b.shared` is bound, flax finds the scope `a/shared` in the cache and so re-uses it for `b.shared`. However, when `run_b` is used, `a.shared` is never bound so the scope `a/shared` is never created.

Is there any way around this, perhaps using some sort of tricks in `setup`? I think there's a pretty strong argument for this use-case: it's nice to have a wrapper around multiple submodules where the submodules all get initialized at once (using `__call__`) but then individual subsets of modules can be used later on, potentially in a more complex way. And I don't see any reason why these submodules shouldn't be able to share parameters.

**Comment by cgarciae** [comment]
Hey @kvablack, thanks for reporting this!

I am fixing a related issue in #2748, one of the edge cases I found recently was related to lazy binding, as you suggest this is indeed the problem you are facing here. The solution I am currently exploring is to eagerly bind all sub-modules that are passed as inputs as soon as a scope is available, I suspect this will solve your issue.

I'll be adding the snippet you shared as a test case.
