### ISSUE TITLE
Google Colab Flax

### ISSUE THREAD

**Issue by averageFlaxUser** [google/flax#2865]
Provide as much information as possible. At least, this should include a description of your issue and steps to reproduce the problem. If possible also provide a summary of what steps or workarounds you have already tried.

### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`: Flax 0.6.5, Jax 0.4.3, jaxlib 0.4.3+cuda
- Python version: 3.9
- GPU/TPU model and memory: A100
- CUDA version (if applicable): 11

### Problem you have encountered:
Importing `flax` throws an error in Colab.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-1eb4e1389182>](https://g3zdp1l9s46-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230209-060050-RC00_508245393#) in <module>
     11 # Flax
     12 from flax import linen as nn
---> 13 from flax.training import train_state
     14 
     15 # NTK

12 frames
[/usr/local/lib/python3.8/dist-packages/numpy/__init__.py](https://g3zdp1l9s46-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230209-060050-RC00_508245393#) in __getattr__(attr)
    311         # The previous way Tester was imported also had a side effect of adding
    312         # the full `numpy.testing` namespace
--> 313         if attr == 'testing':
    314             import numpy.testing as testing
    315             return testing

AttributeError: module 'numpy' has no attribute '_no_nep50_warning'
```

### What you expected to happen:
No errors.

### Steps to reproduce:
I install modules as follows:

```
#@title Package Installation
!pip install -q flax
!pip install -q git+https://www.github.com/google/neural-tangents
!pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

**Comment by IvyZX** [comment]
It's possible that this is due to Colab pinning JAX at an older version (same cause as https://github.com/google/flax/issues/2861)
A quick way to solve this:
1. Move the line `!pip install "jax[cuda11_cudnn82]" ...` before the line `!pip install -q flax` to install the latest JAX first
2. After all installations are done, restart the runtime and use Flax as usual.
