### ISSUE TITLE
Update pjit flax tutorial to match updated jax interface

### ISSUE THREAD

**Issue by jenkspt** [google/flax#2876]
Jax has merged `pjit` and `jit` into a unified interface: https://jax.readthedocs.io/en/latest/jax-101/08-pjit.html

This is a request to update the Flax tutorial at: https://flax.readthedocs.io/en/latest/guides/flax_on_pjit.html
to match the update Jax tutorial [Distributed arrays and automatic parallelization](https://jax.readthedocs.io/en/latest/notebooks/Distributed_arrays_and_automatic_parallelization.html)

**Comment by cgarciae** [comment]
Thanks for the feedback @jenkspt! Indeed we already have a planned update this guide with JAX's new `jit` and `jit.sharding` APIs.

**Comment by wbrenton** [comment]
@cgarciae out of curiosity where does this updated tutorial stand?

**Comment by 8bitmp3** [comment]
On it (cc @cgarciae @IvyZX )

**Comment by IvyZX** [comment]
Hi, the updated tutorial is in this PR: https://github.com/google/flax/pull/3016
Hopefully it will be approved soon. @8bitmp3
