### ISSUE TITLE
Potentially make matplotlib an optional dependency

### ISSUE THREAD

**Issue by ntenenz** [google/flax#2883]
Apologies in advance for quoting, nearly verbatim, these issues from the [ott-jax](https://github.com/ott-jax/ott/issues/292) and [jaxopt](https://github.com/google/jaxopt/issues/396) packages but the issue is largely identical.

matplotlib is a fairly "heavy" dependency in that it pulls in lots of extra packages. However, it's not required to use the bulk of `flax` outside of potentially parts of [flax/metrics/tensorboard.py](https://github.com/google/flax/blob/1e7d843909faf48c034ea12eb7bf3d007efe4f7b/flax/metrics/tensorboard.py).

I'm wondering whether the team would consider either removing it or making it an optional dependency to minimize the number of packages pulled in by downstream projects.

**Comment by cgarciae** [comment]
I agree with this, we can create an e.g. `all` group and bundle `matplotlib` there:

```bash
pip install flax[all]
```
