### ISSUE TITLE
INVALID_ARGUMENT when running in the multi-host environment.

### ISSUE THREAD

**Issue by mingxu1067** [google/flax#2904]
### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`:
Flax: 0.6.4
jax: 0.4.5
jax: 0.4.5
- Python version: 3.8.10
- GPU/TPU model and memory: GPU, A100-80GB
- CUDA version (if applicable): 11.8

### Problem you have encountered:
I am implenting a mulit-process multi-device NN training examples via pjit + jax.distributed.initilze, but encounter some strange errors. The pjitted function passes in the first two step, BUT crashes on the third step. like
```
for i in range(5):
            rng, data_rng = jax.random.split(rng)
            inputs = get_synthesis_data(data_rng, GLOBAL_BATCH)
            loss, state, variables = pjitted_train_step(inputs, state, variables)
            if args.process_id == 0:
                print(f"Step {i} - Loss: {loss}")

# Step 0 - Loss: 3.67165e-05
# Step 1 - Loss: 0.000104904
# 2023-02-24 15:02:52.048815: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2410]Execution of # replica 0 failed: INVALID_ARGUMENT: Executable expected shape f32[512,32,1024]{2,1,0} for argument 0 butgot incompatible shape f32[512,256,1024]{2,1,0}
```

Besides, if I change batch size, each batch size can successfully pass exact two steps, like
```
for i in range(2):
            rng, data_rng = jax.random.split(rng)
            inputs = get_synthesis_data(data_rng, BATCH_1)
            loss, state, variables = pjitted_train_step(inputs, state, variables)
            if args.process_id == 0:
                print(f"Step {i} - Loss: {loss}")
                
for i in range(2):
            rng, data_rng = jax.random.split(rng)
            inputs = get_synthesis_data(data_rng, BATCH_2)
            loss, state, variables = pjitted_train_step(inputs, state, variables)
            if args.process_id == 0:
                print(f"Step {i} - Loss: {loss}")              
```

I saw there is a similar issue [2900](https://github.com/google/flax/issues/2900), but the solution in that issue not works to mine.

### What you expected to happen:
Expected to running without errors, like
```
# Step 0 - Loss: 3.67165e-05
# Step 1 - Loss: 0.000104904
# Step 2 - Loss: xxxxxxxxxxxx
# Step 3 - Loss: xxxxxxxxxxxx
# Step 4 - Loss: xxxxxxxxxxxx
```

### Logs, error messages, etc:
```
Step 0 - Loss: 3.67165e-05
Step 1 - Loss: 0.000104904
2023-02-24 15:02:52.048815: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2410]Execution of # replica 0 failed: INVALID_ARGUMENT: Executable expected shape f32[512,32,1024]{2,1,0} for argument 0 butgot incompatible shape f32[512,256,1024]{2,1,0}
```

### Steps to reproduce:
Whenever possible, please provide a *minimal example*. Please consider submitting it as a Colab link.
The full reproducer: [https://github.com/mingxu1067/flax_mpmd_issues](https://github.com/mingxu1067/flax_mpmd_issues)

**Comment by mingxu1067** [comment]
This issue is resolved by collecting all local arrays in each processes to a shared device array, like
```
def get_synthesis_data(data_rng, mesh, pspec):
    tensors = jax.random.normal(data_rng, [BATCH_PER_GPU, HIDDEN], jnp.float32)
    inputs_shared = jax.make_array_from_single_device_arrays(
                    (GLOBAL_BATCH, HIDDEN),
                    jax.sharding.NamedSharding(mesh, pspec),
                    [tensors])
    return inputs_shared
```

**Comment by samblouir** [comment]
You have to do this at every step? Does it slow your code down a lot?

**Comment by mingxu1067** [comment]
@samblouir I do that at every step. About performance, I have not tested on any benchmark (just on an example), could not give answer here.
