### ISSUE TITLE
Add more descriptive info to imagenet README for loading fake data

### ISSUE THREAD

**Issue by gkroiz** [google/flax#2916]
For the [imagenet](https://github.com/google/flax/tree/main/examples/imagenet) directory under `flax/examples/imagenet`, there is an option to create fake data. However, to correctly generate fake data, the user has to download the data via:
```
python -c "
import tensorflow_datasets as tfds
tfds.builder('imagenet2012').download_and_prepare(
    download_config=tfds.download.DownloadConfig(
        manual_dir='$IMAGENET_DOWNLOAD_PATH'))
"
```
(the code snippet above is from the [README.md](https://github.com/google/flax/blob/main/examples/imagenet/README.md)). Downloading the entire dataset seems somewhat counter-intuitive for generating fake data, making this step seem nonessential. When using the imagenet model, I skipped over the download step (since it seemed unrelated) and ran into issues when trying to run the model. For myself and a few other users, this seems to be a common gotcha.  Two suggestions:
1) Clarify in the readme that the data needs to be downloaded, even when generating fake data
2) Alternatively, add the brief snippet shown below, which only downloads the metadata of the dataset (the code for generating fake data relies on the metadata of the dataset, not the actual data itself)
```
mkdir -p $HOME/flax/.tfds/metadata/imagenet2012/5.1.0
curl https://raw.githubusercontent.com/tensorflow/datasets/v4.4.0/tensorflow_datasets/testing/metadata/imagenet2012/5.1.0/dataset_info.json --output $HOME/flax/.tfds/metadata/imagenet2012/5.1.0/dataset_info.json
```

I would be happy to write a PR for this if need be, thanks!

**Comment by cgarciae** [comment]
Hey @gkroiz, can you try clearing the downloaded data (plus all related folders) and running:

```bash
bash tests/download_dataset_metadata.sh
```
We do this for testing. This imagenet train test runs fine on our CI using mock data:

https://github.com/google/flax/blob/3568769a76cb46ca6d501528139efea91057d207/examples/imagenet/train_test.py#L68-L86

If the mentioned trick works for you we should add it to the readme.

**Comment by gkroiz** [comment]
When using the latest version of github, `bash tests/download_dataset_metadata.sh` generates metadata for the datasets as expect. However, my test environment uses git 2.25.1, where this script does not work. To work around this, I can use the `curl` script from my previous comment. Regardless, could the READMEs for imagenet and other tests include this information?
