### ISSUE TITLE
Incompatibility between `jax.jit` in jax>=4.3 and `nn.spmd.with_logical_constraint`.

### ISSUE THREAD

**Issue by andyehrenberg** [google/flax#2938]
With the pjit-jit merge, functions partitioned with `jax.jit` are not run within mesh contexts - instead their `in_shardings`, `out_shardings` and sharding_constraints use pytrees of Shardings like `NamedSharding(mesh, pspec)` (not direct `PartitionSpecs` - see https://github.com/google/jax/blob/main/jax/_src/pjit.py#L753). Currently, `nn.spmd.with_logical_constraint` is a no-op when not run within a mesh context. This is fine for older versions of JAX where pjit needs to be run in a mesh context, but now I think the logic would need to be similar to:

```
def with_logical_constraint(x, logical_axes, mesh):
    sharding = jax.tree_util.tree_map(
        lambda pspec: NamedSharding(mesh, pspec),
        nn.logical_to_mesh(logical_axes),
    )
    return jax.lax.with_sharding_constraint(x, sharding)
```

to work with partitioned functions not run in mesh contexts. 

Right now, it seems that any calls to `nn.spmd.with_logical_constraint` will be no-ops with the new `jax.jit` style of partitioning a function when not run in mesh contexts.

**Comment by cgarciae** [comment]
Hey @andyehrenberg! Two things: 

1. I tested using a mesh context and it worked on jax 0.4.5:

```python

import jax
import jax.numpy as jnp
from jax.experimental import mesh_utils

print("jax version:", jax.__version__)

device_mesh = mesh_utils.create_device_mesh((2, 2))
mesh = jax.sharding.Mesh(devices=device_mesh, axis_names=('model', 'data'))

@jax.jit
def f(x):
    return jax.lax.with_sharding_constraint(x, jax.sharding.PartitionSpec('model', 'data'))

x = jnp.ones((4, 4))

with mesh:
    y = f(x)

jax.debug.visualize_array_sharding(y, use_color=False)
```
```
jax version: 0.4.5
┌──────────┬──────────┐
│          │          │
│  TPU 0   │  TPU 1   │
│          │          │
│          │          │
├──────────┼──────────┤
│          │          │
│  TPU 2   │  TPU 3   │
│          │          │
│          │          │
└──────────┴──────────┘
```
Can you give an example where it would fail? I personally don't know the situation about context managers. That said...

2. I also like the idea of being able to pass the mesh and rules explicitly so I created #2939.

**Comment by yashk2810** [comment]
This works because with_sharding_constraint reads the mesh context manager and not jax.jit.

It is a good idea to not rely on the mesh context manager and pass the mesh value explicitly.
