### ISSUE TITLE
Flax specified version force-installs higher version than required, and higher than Colab allows

### ISSUE THREAD

**Issue by krahnikblis** [google/flax#2950]
summary:
- need to use Flax and Optax on Colab, specifically for TPU. Flax requires Jax [and as i discovered through chasing all this down for y'all, it also requires Orbax...]. i.e. everything is Google's and "in-house" re: this issue
- latest version of Jax if used on Colab breaks Optax simply on import. why? because...
- per [this comment](https://github.com/google/jax/issues/14544#issuecomment-1448538013) on a related issue in Jax, "Colab TPUs are only compatible with jax v0.3.25 and older".  
- but latest Flax [setup.py requires](https://github.com/google/flax/blob/main/setup.py) Jax > 0.4.x. workaround: use an obsolete version
- per this [setup.py file](https://github.com/google/flax/blob/v0.6.4/setup.py), the most recent obsolete version of Flax, 0.6.4, only requires Jax>=0.3.16
- Colab comes pre-configured with Jax 0.3.25. let the records show that 25 >= 16, i.e., requirement met.
- yet, installing Flax 0.6.4 still force-installs Jax 0.4.6, which breaks everything (Colab-Jax incompatibility, jaxlib incompatibility, Optax TPU array issue, etc.)
- looks like Flax requires Orbax (no version, i.e. pip will get latest) , and [Orbax latest pyproject.toml requires Jax >= 0.4.1](https://github.com/google/orbax/blob/main/pyproject.toml). Orbax is a Google product too. (_aside: hey why are y'all using `setup.py` to host requirements in some places, and `pyproject.toml` in other places? i.e. does Google dev not have a template or style guide for consistency across libraries?_)
- Orbax 0.1.2 (obsolete version) [pyproject.toml does not require a specific Jax version](https://github.com/google/orbax/blob/v0.1.2/pyproject.toml), just that jax is there
- **Orbax requires Flax, Flax requires Orbax, no matter what order you install them in, it auto-installs the latest version of the other, which then triggers the install of the incompatible [yet current] version of Jax**
- apparently a pip syntax allows a hack for this: do both obsolete versions in a one-liner, i.e. `!pip install flax==0.6.4 orbax==0.1.2` i.e., **this is a workaround** (which could be a "solution" if y'all pre-configure Colab this way; expectation preference # 2 below)

### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Colab defaults:
`!cat /etc/*release`
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Flax, jax, jaxlib versions:
**BEFORE installing Flax==0.6.4:**
`!pip show jax jaxlib`
Name: jax
Version: 0.3.25
...
Name: jaxlib
Version: 0.3.25
**AFTER installing Flax==0.6.4**
`!pip show jax jaxlib`
Name: jax
Version: 0.4.6 &#x1F534;
...
Name: jaxlib
Version: 0.3.25

- Python version:
`!python --version`
Python 3.9.16

- GPU/TPU model and memory:
Colab TPU v2-8

- CUDA version (if applicable):
not applicable

### Problem you have encountered:
installing Flax doesn't recognize existing Jax version is OK, and installs a version that is not compatible with Colab TPU and Optax and existing jaxlib. 

### What you expected to happen:
1. Google Colab and Google TPUs work with all Google software libraries, all versions (i.e. latest versions of everything "just work". this is a paid service, so i think a justifiable expectation...)
2. else, everything on Colab needed to run all other Google products is pre-configured and inter-compatible (i.e., all compatible versions of things are pre-installed and tested, i.e. your paying customers aren't forced to be your beta testers)
3. else, installing a specific version of a library (e.g. Flax), which names another specific version dependency (e.g. Jax), only references other dependencies (e.g. Orbax) that are also compatible with that version (of e.g. Jax)  (i.e., if i install Flax 0.6.4 which says it only needs Jax 0.3.16, then _no other Flax dependency should require a higher Jax version_)

### Steps to reproduce:
```python
from importlib.metadata import version
print("jax version before Flax install", version('jax'))
!pip install -v flax==0.6.4 
print("flax version installed", version('flax'))
print("jax version after flax install", version('jax'))
```
here's another attempt, after discovering the Orbax>Jax dependency:
```python
from importlib.metadata import version
print("jax version before Flax install", version('jax'))
!pip install orbax==0.1.2
print("orbax version installed", version('orbax'))
print("jax version after orbax install", version('jax'))
!pip install flax==0.6.4 
print("flax version installed", version('flax'))
print("jax version after flax install", version('jax'))
```
and here's the final version that actually prevents installing Jax by using a pip syntax hack:
```python
from importlib.metadata import version
print("jax version before Flax install", version('jax'))
!pip install flax==0.6.4 orbax==0.1.2 # one-liner syntax hack
print("orbax version installed", version('orbax'))
print("flax version installed", version('flax'))
print("jax version after flax and orbax install", version('jax'))
```

### Logs, error messages, etc:
relevant parts only, flagged with some good (&#x1F535;) and bad (&#x1F534;) derps. this is from the first version of install scripts above, but as you would expect the second version acts similarly. **only with the 3rd one is the Jax version maintained at 0.3.25...**
jax version before Flax install 0.3.25 &#x1F535;
Using pip 22.0.4 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting flax==0.6.4
  Downloading flax-0.6.4-py3-none-any.whl (204 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.3/204.3 KB 6.3 MB/s eta 0:00:00
Requirement already satisfied: msgpack in /usr/local/lib/python3.9/dist-packages (from flax==0.6.4) (1.0.4)
Requirement already satisfied: jax>=0.3.16 in /usr/local/lib/python3.9/dist-packages (from flax==0.6.4) (0.3.25) &#x1F535;&#x1F535;&#x1F535;
Collecting tensorstore
  Downloading tensorstore-0.1.33-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 80.4 MB/s eta 0:00:00
Requirement already satisfied: PyYAML>=5.4.1 in /usr/local/lib/python3.9/dist-packages (from flax==0.6.4) (6.0)
Collecting rich>=11.1
  Downloading rich-13.3.2-py3-none-any.whl (238 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.7/238.7 KB 25.4 MB/s eta 0:00:00
Collecting orbax
  Downloading orbax-0.1.3-py3-none-any.whl (74 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.2/74.2 KB 9.6 MB/s eta 0:00:00
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/dist-packages (from flax==0.6.4) (3.5.3)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.9/dist-packages (from flax==0.6.4) (4.5.0)
Collecting optax
  Downloading optax-0.1.4-py3-none-any.whl (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.9/154.9 KB 20.7 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.12 in /usr/local/lib/python3.9/dist-packages (from flax==0.6.4) (1.24.2)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.9/dist-packages (from jax>=0.3.16->flax==0.6.4) (3.3.0)
Requirement already satisfied: scipy>=1.5 in /usr/local/lib/python3.9/dist-packages (from jax>=0.3.16->flax==0.6.4) (1.10.1)
Collecting markdown-it-py<3.0.0,>=2.2.0
  Downloading markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.5/84.5 KB 11.8 MB/s eta 0:00:00
Collecting pygments<3.0.0,>=2.13.0
  Downloading Pygments-2.14.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 66.9 MB/s eta 0:00:00
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->flax==0.6.4) (4.39.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib->flax==0.6.4) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->flax==0.6.4) (8.4.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->flax==0.6.4) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib->flax==0.6.4) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->flax==0.6.4) (3.0.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->flax==0.6.4) (23.0)
Collecting chex>=0.1.5
  Downloading chex-0.1.6-py3-none-any.whl (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.9/87.9 KB 10.4 MB/s eta 0:00:00
Requirement already satisfied: jaxlib>=0.1.37 in /usr/local/lib/python3.9/dist-packages (from optax->flax==0.6.4) (0.3.25) &#x1F535;
Requirement already satisfied: absl-py>=0.7.1 in /usr/local/lib/python3.9/dist-packages (from optax->flax==0.6.4) (1.4.0)
Requirement already satisfied: importlib_resources in /usr/local/lib/python3.9/dist-packages (from orbax->flax==0.6.4) (5.12.0)
Collecting jax>=0.3.16
  Downloading jax-0.4.6.tar.gz (1.2 MB) &#x1F534;&#x1F534;&#x1F534;
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 75.8 MB/s eta 0:00:00
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-ab35lc74/jax.egg-info
  writing /tmp/pip-pip-egg-info-ab35lc74/jax.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-ab35lc74/jax.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-ab35lc74/jax.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-ab35lc74/jax.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-ab35lc74/jax.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-ab35lc74/jax.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  adding license file 'AUTHORS'
  writing manifest file '/tmp/pip-pip-egg-info-ab35lc74/jax.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
...
Successfully built jax
Installing collected packages: cached_property, tensorstore, pygments, mdurl, markdown-it-py, jax, rich, chex, optax, orbax, flax
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.6.1
    Uninstalling Pygments-2.6.1:
      Removing file or directory /usr/local/bin/pygmentize
      Removing file or directory /usr/local/lib/python3.9/dist-packages/Pygments-2.6.1.dist-info/
      Removing file or directory /usr/local/lib/python3.9/dist-packages/pygments/
      Successfully uninstalled Pygments-2.6.1
  changing mode of /usr/local/bin/pygmentize to 755
  changing mode of /usr/local/bin/markdown-it to 755
  Attempting uninstall: jax
    Found existing installation: jax 0.3.25 &#x1F535;
    Uninstalling jax-0.3.25: &#x1F534;&#x1F534;&#x1F534;
      Removing file or directory /usr/local/lib/python3.9/dist-packages/jax-0.3.25.dist-info/
      Removing file or directory /usr/local/lib/python3.9/dist-packages/jax/
      Successfully uninstalled jax-0.3.25
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.9.0 requires jedi>=0.10, which is not installed.
Successfully installed cached_property-1.5.2 chex-0.1.6 flax-0.6.4 jax-0.4.6 markdown-it-py-2.2.0 mdurl-0.1.2 optax-0.1.4 orbax-0.1.3 pygments-2.14.0 rich-13.3.2 tensorstore-0.1.33
flax version installed 0.6.4 &#x1F535;
jax version after flax install 0.4.6 &#x1F534;

**Comment by andsteing** [comment]
Thanks for the detailed bug report!

Yes, indeed, TPU Colab runtime does not support new JAX versions anymore.

So I would recommend to

1. either use the CPU or GPU runtime (both work with the latest `flax-0.6.7`)
2. install Flax like this on a TPU runtime while keeping JAX runtime fixed: `!pip install flax==0.6.4 jax==0.3.25 jaxlib==0.3.25`

We're sorry about the inconveniences caused, but making Colab TPU runtime infra compatible with new JAX versions is beyond what we can currently fix.

**Comment by krahnikblis** [comment]
add [Chex](https://pypi.org/project/chex/) to the mix - Orbax 0.1.2 doesn't specify chex specific required version (just min), so the newest is auto-installed. the latest update of Chex (0.1.7) requires Jax >= 0.4.6, so the above hack of pip install version syntax needs to be amended with an obsolete version of Chex now too.... 

this ([johnnydep](https://github.com/wimglenn/johnnydep)) is an **amazing** tool for figuring this shtuff out:
```python
!pip install johnnydep
!johnnydep orbax==0.1.2
```
interesting part of the output here was
```
│   ├── optax                                  A gradient processing and optimisation library in JAX.
│   │   ├── absl-py>=0.7.1                     Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
│   │   ├── chex>=0.1.5                        Chex: Testing made fun, in JAX!
│   │   │   ├── absl-py>=0.9.0                 Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
│   │   │   ├── dm-tree>=0.1.5                 Tree is a library for working with nested data structures.
│   │   │   ├── jax>=0.4.6                     Differentiate, compile, and transform Numpy code.
│   │   │   │   ├── ml-dtypes>=0.0.3
│   │   │   │   │   └── numpy>1.20             Fundamental package for array computing in Python
```

so, _for now_, this works for Colab to keep olde peepaw Jax and Friends in their porch rocking chairs shouting at all the new kids to stay off their lawns:
`!pip install -qq flax==0.6.4 chex==0.1.6 orbax==0.1.2 optax` << notice optax is a hold-out - how long y'think till that one upgrades and requires new Jax city too?

please, someone from one of these google softwares get on the horn with someone from the relevant department or put in a work order to just rip out all those old and busted TPU v2-8s and swap in some new hotness TPUs that are compatible with all this other google stuff

**Comment by andsteing** [comment]
Thanks @krahnkiblis for the additional details!

Indeed, having to specify all packages by their latest version that does not update JAX is not sustainable ...

Let's instead go with this:

```
!pip install jax==0.3.25 jaxlib==0.3.25 flax
```

I have also created a discussion to increase visibility about this problem:
https://github.com/google/flax/discussions/2995
