### ISSUE TITLE
Potentially wrong arguments in `input_pipeline.py` of  `ogbg_molpcba` example

### ISSUE THREAD

**Issue by JyChang012** [google/flax#2969]
https://github.com/google/flax/blob/23340bbb8e24e3fbf3a3bf958abb0a565c430267/examples/ogbg_molpcba/input_pipeline.py#L56-L61
It seems that `add_self_loops` are assigned to `add_virtual_node` mistakenly.

**Comment by andsteing** [comment]
Thanks for noticing this, @JyChang012 !

Fixed in #2970
