### ISSUE TITLE
How to pass nn.Module as an argument for a jax function?

### ISSUE THREAD

**Issue by MagiFeeney** [google/flax#3003]
Problem: I defined a class called `model` with multiple methods, which will be cross-referenced by other updating functions. If I just have the state information, I can only use one main method by calling `apply_fn`, however, not other methods. If I need to reuse those methods, I would pass the `model` into a jax.jit function, then use `model.apply(..., method=some_method)`, but it throws an error that the passed argument is not a valid JAX type.

How can I find a simple solution to reference submethods?

**Comment by cgarciae** [comment]
Hey @MagiFeeney, invalid JAX types must be passed as static arguments to `jit` e.g:

```python
from functools import partial

model = ...

@partial(jax.jit, static_argnums=(0,))
def train_step(some_method, x):
   y = model.apply(..., x, method=some_method)
   ...
```
If `model` is hashable then you can pass it directly to `jit`:
```python
@partial(jax.jit, static_argnums=(0, 1))
def train_step(model, some_method, x):
   y = model.apply(..., x, method=some_method)
   ...
```
In general we recommend the use of [TrainState](https://flax.readthedocs.io/en/latest/api_reference/flax.training.html#flax.training.train_state.TrainState), so could do something like this:

```python
state = TrainState.create(
    apply_fn=model.apply,
    params=variables['params'],
    tx=tx)
    
@partial(jax.jit, static_argnums=(1,))
def train_step(state, some_method, x):
   y = state.apply_fn({'params': state.params}, x, method=some_method)
   ...
```

**Comment by MagiFeeney** [comment]
That's exactly what I want! Thank you!

**Comment by qlan3** [comment]
I have a related question about TrainState. It seems that for  the latest flax (0.8.0), TrainState does not support str as the input method. For example, following the example [here](https://flax.readthedocs.io/en/latest/api_reference/flax.linen/module.html#flax.linen.Module.apply),
```
class Transformer(nn.Module):
  def encode(self, x):
    ...

x = jnp.ones((16, 9))
model = Transformer()
params = model.init(jax.random.key(0), x, method=model.encode)
```
The following two ways work well. 
```
encoded = model.apply(params, x, method=model.encode)
encoded = model.apply(params, x, method='encode')
```
However, when TrainState is used:
```
train_state = TrainState.create(
  apply_fn = model.apply,
  params = params,
  tx = ...
)
```
The following codes throws errors:
```
train_state.apply_fn(train_state.params, x, method='encode')

TypeError: Argument 'encode' of type <class 'str'> is not a valid JAX type
```
or
```
train_state.apply_fn(train_state.params, x, method=model.encode)

TypeError: Cannot interpret value of type <class 'method'> as an abstract array; it does not have a dtype attribute
```

Any idea how to fix this?
