### ISSUE TITLE
AttributeError: module 'flax.core' has no attribute 'pop'

### ISSUE THREAD

**Issue by ahx1997** [google/flax#3009]
### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux docker
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`:0.5.0
- Python version:3.85
- GPU/TPU model and memory:vid2seq 40G
- CUDA version (if applicable):11.1

### Problem you have encountered:
I need "pop" to use "train_lib_deprecated/train_utils.py" but
i cant find it

### Steps to reproduce:
Whenever possible, please provide a *minimal example*. Please consider submitting it as a Colab link.

**Comment by chiamp** [comment]
Hi @ahx1997, can you try to upgrade Flax via `pip install -U flax`? The utility functions like `flax.core.pop` were added recently: https://github.com/google/flax/releases
