### ISSUE TITLE
Bug in trace_level when switching to jax.4.6 with nested module levels

### ISSUE THREAD

**Issue by lccnl** [google/flax#3048]
Provide as much information as possible. At least, this should include a description of your issue and steps to reproduce the problem. If possible also provide a summary of what steps or workarounds you have already tried.

### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`: Flax=0.6.3 to 0.6.9, jax and jaxlib==0.4.6
- Python version:3.8.9
- GPU/TPU model and memory: CPU
- CUDA version (if applicable):

### Problem you have encountered:

Hello,
we have a deep learning model with nested modules where the outer module shares some params, the first inner module is basically a flax.vmap to parallelize across the first dimension and then there is a module that is a deep learning model per example. The loss is also structured similarly: it is a nested module where some parameters are optimized in advance and then bound. 

### What you expected to happen:

With jax versions below the pjit/jit fusion, everything works well.
From jax/jaxlib 0.4.6 an error due to the trace_levels occurs in the forward pass.

### Logs, error messages, etc:
```
flax.errors.JaxTransformError: Jax transforms and Flax models cannot be mixed
```
I looked a bit at the jax code and it appears that the method jax.core.find_top_trace returned in previous versions a DynamicJaxprTrace with level 0 and sublevel 1 while now it returns a DynamicJaxprTrace  with level 1 and sublevel 0. Not sure to understand why and if it is a flax or jax issue then.

### Steps to reproduce:

Here is a minimal example to reproduce with colab. I simplified as much as possible to reproduce just the module structure that leads to the error.

https://colab.research.google.com/drive/1p18gHQWpA9fi9B9C5pJNAWkuI1Vmw8o-#scrollTo=twROQZAFU-19

**Comment by cgarciae** [comment]
Hey @lccnl, I think the error is correct, you are passing a bounded as a capture to a jitted function. The following works:

```python
model=GlobalModel()
loss_module=BatchLoss()
_,params=model.init_with_output({"params": jax.random.PRNGKey(0)},jnp.ones((10,1)),method=model.decode)

def _loss_function(
    params: Any, batch_data:jnp.ndarray, rng: jax.random.PRNGKeyArray
):
    prediction = model.apply(
        params,
        batch_data,
        method=model.decode,
        rngs={"shuffle": rng},
    )
    return loss_module.apply({}, prediction, batch_data)
```

**Comment by cgarciae** [comment]
Honestly not sure what changed 🤔
