### ISSUE TITLE
Add links to HOWTOs from the main README

### ISSUE THREAD

**Issue by danielsuo** [google/flax#309]
Started looking at this and raising an issue since there are different scopes:

- Just add a link to the directory next to the "HOWTO guides" bullet under [What is Flax?](https://github.com/google/flax#what-is-flax)
- Add sub-bulleted examples or link in "Utilities and patterns" (e.g., distributed training, polyak averaging)
- Add a section much like the "Try Flax now by forking one of our starter examples" (e.g., example code for frequently-asked questions)

@avital @marcvanzee

**Comment by avital** [comment]
We have (perhaps temporarily, not sure yet) deprecated HOWTOs after the move to Linen, so I'm closing this. We'll be trying to add more short "pattern notes" that aren't formally tested and simply live as small markdown files.
