### ISSUE TITLE
[`struct.dataclass`] Frozen instance error when `field(init=False)`

### ISSUE THREAD

**Issue by ASEM000** [google/flax#3105]
Provide as much information as possible. At least, this should include a description of your issue and steps to reproduce the problem. If possible also provide a summary of what steps or workarounds you have already tried.

### System information
- OS Platform and Distribution = mac osx 13.3.1
- Flax, jax, jaxlib versions 0.6.9,0.4.8,0..4.7
- Python version: 3.10
- GPU/TPU model and memory: NA
- CUDA version (if applicable):NA

### Problem you have encountered:

```python
import flax
from flax import struct
import dataclasses as dc

# flax.__version__
# '0.6.9'

@struct.dataclass
class Tree:
    a: int = dc.field(init=False)

    def __post_init__(self):
        self.a = 1

tree = Tree()
```
```
FrozenInstanceError                       Traceback (most recent call last)
Cell In[55], line 16
     12     def __post_init__(self):
     13         self.a = 1
---> 16 tree = Tree()

File :3, in __init__(self)

Cell In[55], line 13, in Tree.__post_init__(self)
     12 def __post_init__(self):
---> 13     self.a = 1

File :4, in __setattr__(self, name, value)

FrozenInstanceError: cannot assign to field 'a'
```
### What you expected to happen:
```python
import dataclasses as dc

@dc.dataclass
class Tree:
    a: int = dc.field(init=False)

    def __post_init__(self):
        self.a = 1


tree = Tree()
tree
# Tree(a=1)

```

**Comment by cgarciae** [comment]
Hey @ASEM000! `flax.struct.dataclass` creates frozen dataclasses which don't support setting attributes even on `__post_init__`.

**Comment by ASEM000** [comment]
Ah got it. My bad

Thanks
