### ISSUE TITLE
Why flax.optim is removed?

### ISSUE THREAD

**Issue by zugexiaodui** [google/flax#3121]
I encountered some problems when installing an older version. Due to compatibility issues, I am unable to run the code with a newer version of flax. I don't hope flax to become the second TensorFlow.

**Comment by chiamp** [comment]
Hi @zugexiaodui, `flax.optim` was deprecated in favor of [`optax`](https://github.com/deepmind/optax). To convert to `optax`, you can read our update guide [here](https://flax.readthedocs.io/en/latest/guides/optax_update_guide.html). If you want to continue using `flax.optim` you'll need to install an older version of Flax (`flax.optim` was deprecated in [0.4.1](https://github.com/google/flax/releases/tag/v0.4.1))
