### ISSUE TITLE
nn.Sequential error message not informative for incorrect pytorch-like usage

### ISSUE THREAD

**Issue by JohannesAck** [google/flax#3147]
Hi, I'm currently porting some code from pytorch to Jax. Overall this has been a great experience, but I have a small improvement suggestion for a more informative error when using nn.Sequential incorrectly.

### System information
- Ubuntu22.04
- Flax=0.6.10, jax=0.4.10, jaxlib=0.4.10+cuda12.cudnn88
- Python version: 3.10.6
- GPU/TPU model and memory: CPU
- CUDA version (if applicable): 

### Problem you have encountered:
[Pytorch's nn.Sequential](https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html) supports passing multiple unnamed arguments that are then concatenated, i.e. `nn.Sequential(nn.Linear(16, 16), nn.ReLU())`

However, [flax's nn.Sequential](https://flax.readthedocs.io/en/latest/api_reference/_autosummary/flax.linen.Sequential.html) requires these arguments to be passed as a `Sequence`, i.e. `nn.Sequential([nn.Dense(16), nn.relu])`

When incorrectly trying it to use as in PyTorch we get the following result:
```
>>> import flax.linen as nn
>>> nn.Sequential(nn.Dense(16), nn.relu)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 6, in __init__
  File "/usr/local/lib/python3.10/dist-packages/flax/linen/module.py", line 1001, in __post_init__
    raise ValueError('parent must be None, Module or Scope')
ValueError: parent must be None, Module or Scope
```

### What you expected to happen:
It would be nice to have a more informative error message here, especially considering the differences to the PyTorch API of the same name.

### Steps to reproduce:
```
>>> import flax.linen as nn
>>> nn.Sequential(nn.Dense(16), nn.relu)
```

**Comment by cgarciae** [comment]
Hey @JohannesAck, thanks for reporting! 
This was recently fixed by #3129 so I will be closing this issue.
