### ISSUE TITLE
Feature requet: Add Keras-like API to flax.training

### ISSUE THREAD

**Issue by carlosgmartin** [google/flax#3150]
[Keras](https://keras.io/) makes it easy to train models without much boilerplate code. It would be nice to have a similar API under [flax.training](https://flax.readthedocs.io/en/latest/api_reference/flax.training.html). Example (based on [compile](https://keras.io/api/models/model_training_apis/#compile-method) and [fit](https://keras.io/api/models/model_training_apis/#fit-method)):

```python3
def fit(
    model: nn.Module,
    optimizer: optax.GradientTransformation,
    loss: typing.Callable,
    metrics: typing.Sequence[typing.Callable],
    x,
    y,
    batch_size: int = 1,
    epochs: int = 1,
    validation_split: float = 0,
    ...
) -> dict:
    ...

history = fit(model, optax.sgd(1e-3), optax.squared_error, ...)
```

This saves users the trouble of writing a full training loop themselves or importing an extra library. This could be very convenient for most use cases. Thoughts?

**Comment by levskaya** [comment]
We intentionally don't try to provide full training-loop functionality in flax.  It's out of scope as the number of design choices and opinions becomes quickly exponential as one considers different kinds of models and training tasks.  

Instead we refer people to open libraries like [scenic](https://github.com/google-research/scenic), [bigvision](https://github.com/google-research/big_vision) or [maxtext](https://github.com/google/maxtext) for full-fledged examples, or for simpler cases our own flax examples.

I'm closing this for now (but feel free to reopen).

**Comment by NITHISHM2410** [comment]
.

**Comment by NITHISHM2410** [comment]
@carlosgmartin I tried writing a simplistic trainer for flax. check [this](https://github.com/NITHISHM2410/flax-pilot) out.
