### ISSUE TITLE
Flax Read the Docs links sometimes broken

### ISSUE THREAD

**Issue by Davidnet** [google/flax#3173]
Hi Flax team!

First of all, amazing work, now while I am learning Flax I use Google search docs like:

<img width="894" alt="Screenshot 2023-07-01 at 7 36 04 PM" src="https://github.com/google/flax/assets/3343006/259eee3b-af0f-4acf-858e-f35497034b5f">

Then the first links are now 404, for example:

* https://flax.readthedocs.io/en/latest/api_reference/_autosummary/flax.linen.LogicallyPartitioned.html
* https://flax.readthedocs.io/en/latest/advanced_topics/lift.html

It is not in all but certains links are 404 now, and it should point to, as for example:

* https://flax.readthedocs.io/en/latest/api_reference/flax.linen/_autosummary/flax.linen.LogicallyPartitioned.html

**Comment by cgarciae** [comment]
@Davidnet thanks for reporting this! This is probably due to #3073. I'll try to see if we can setup forwarding in RDT for this new structure, @chiamp if its not posrible we should rollback this change.

**Comment by cgarciae** [comment]
@Davidnet, fixed both cases via redirects in readthedocs.
Closing this issue for now.

**Comment by namiller** [comment]
This is happening again FYI
