### ISSUE TITLE
Documentation: A small bug in guides/Managing Parameters and State

### ISSUE THREAD

**Issue by konstmish** [google/flax#3176]
The current [documentation page of managing state parameters](https://flax.readthedocs.io/en/latest/guides/state_params.html) uses `flax.core.pop`, which doesn't exist. So the following line, which appears twice in the documentation,
```state, params = flax.core.pop(variables, 'params')```
should be replaced with
```state, params = variables.pop('params')```

**Comment by cgarciae** [comment]
Hey @konstmish, maybe you are using an older version of Flax? Current code base exposes `pop`:
https://github.com/google/flax/blob/8efa9975700a10a63fd2dbe8c0ec5e4fa7294541/flax/core/__init__.py#L21

**Comment by konstmish** [comment]
You're right, I was behind the current version.
