### ISSUE TITLE
RNN API reference example is out of date

### ISSUE THREAD

**Issue by giovannic** [google/flax#3185]
### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OS 11.7
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`:
jax==0.4.13
jaxlib==0.4.13
flax==0.6.11
- Python version:
Python 3.9.13

### Problem you have encountered:

On trying to re-implement my RNN model in Flax, [the code example](https://flax.readthedocs.io/en/latest/api_reference/flax.linen/layers.html#flax.linen.RNN) in the latest documentation errored. This applies to all of the code examples for RNNs

### What you expected to happen:

The API reference should reflect the implementation, i.e:

 * The RNN module documentation should show `cell_size` as a positional argument
 * Code examples should show how to initialise an LSTM cell for a given feature size, e.g.

```python
import jax.numpy as jnp
import jax
import flax.linen as nn

x = jnp.ones((10, 50, 32)) # (batch, time, features)
lstm = nn.RNN(nn.LSTMCell(), 64)
variables = lstm.init(jax.random.PRNGKey(0), x)
y = lstm.apply(variables, x)
y.shape # (batch, time, cell_size)
```

### Steps to reproduce:

```python
>>> import jax.numpy as jnp
>>> import jax
>>> import flax.linen as nn
>>> x = jnp.ones((10, 50, 32))
>>> lstm = nn.RNN(nn.LSTMCell(64))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'cell_size'
```

**Comment by cgarciae** [comment]
Hey @giovannic, sorry about this, we recently made a refactor to the RNN API but we haven't created a new release, we should probably do it today. In the meantime, install the latest Flax from github if you want to use the latest features:

```
pip install -U git+https://github.com/google/flax.git
```
