### ISSUE TITLE
Adding dropout to the model?

### ISSUE THREAD

**Issue by MandaloreUltimate** [google/flax#322]
So I just took the [annotated MNIST example](https://flax.readthedocs.io/en/latest/annotated_mnist.html) and tried to modify the model in a few ways, however, for some reason I can't just add the dropout to CNN class by `x = flax.nn.dropout(x, 0.4)` (like in [some other examples](https://github.com/google/flax/blob/ab88025e4d016b2756a2e06f79ce6d61066912f7/examples/nlp_seq/models.py)), as I get the following error for this line:

> ValueError: Use the `nn.stochastic()` context manager to enable stochastic computations.

**Comment by danielsuo** [comment]
`flax` [documentation](https://flax.readthedocs.io/en/latest/_autosummary/flax.nn.stochastic.html?highlight=stochastic#flax.nn.stochastic) on `nn.stochastic` is a bit sparse, so for now, it might be helpful to see how the `nlp_seq` example uses the context manager (here's a [snippet](https://github.com/google/flax/blob/ab88025e4d016b2756a2e06f79ce6d61066912f7/examples/nlp_seq/train.py#L230)).

I believe the context managers for stochastic and stateful computation are still in flux, so any feedback would be much appreciated!

**Comment by avital** [comment]
This should be made much simpler by the [new Linen API](https://github.com/google/flax/tree/master/flax/linen)
