### ISSUE TITLE
exception flax.errors.InvalidRngError(msg)[source]

### ISSUE THREAD

**Issue by haegray-curp** [google/flax#3257]
Provide as much information as possible. At least, this should include a description of your issue and steps to reproduce the problem. If possible also provide a summary of what steps or workarounds you have already tried.

### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ventura 13.1
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`: Name: flax
Version: 0.6.0, Name: jax
Version: 0.3.25, Name: jaxlib
Version: 0.3.25+cuda11.cudnn82
- Python version: 3.9.13
- GPU/TPU model and memory: 02:00.0 VGA compatible controller: Matrox Electronics Systems Ltd. MGA G200e [Pilot] ServerEngines (SEP1) (rev 42)
- CUDA version (if applicable): 11.6.2

### Problem you have encountered:
Am trying to implement a Monte Carlo dropout layer in my class declaration for ResNet. I continue to receive InvalidRngError when trying to implement. Have tried splitting the rng in numerous places in the code and passing in the dropout_rng to init and apply functions for model.

### What you expected to happen:
I expect the Dropout layers to be initialized so I can use Monte Carlo dropout in my model.

### Logs, error messages, etc:
resnet_trainer, resnet_results = trainer(
  File "/files/trainer_nn.py", line 3172, in trainer
    trainer = TrainerModule(*args, **kwargs)
  File "/files/trainer_nn.py", line 1681, in __init__
    self.init_model(exmp_inputs)
  File "/files/trainer_nn.py", line 2675, in init_model
    variables = self.model.init(init_rng, exmp_inputs, train=True)
  File "/files/trainer_nn.py", line 3456, in __call__
    x = self.block_class(
  File "/files/trainer_nn.py", line 3383, in __call__
    z = nn.Dropout(rate=dropout_rate, deterministic = False)(z)
  File "files/env/lib/python3.9/site-packages/flax/linen/stochastic.py", line 65, in __call__
    rng = self.make_rng('dropout')
flax.errors.InvalidRngError: Dropout_0 needs PRNG for "dropout"

### Steps to reproduce:
Whenever possible, please provide a *minimal example*. Please consider submitting it as a Colab link.

**Comment by chiamp** [comment]
could you provide a minimal reproducible example? Typically this error occurs when you don't pass in the `dropout` rng into `apply`, but it seems like you're still getting the error after doing that

**Comment by chiamp** [comment]
> variables = self.model.init(init_rng, exmp_inputs, train=True)

Can you try setting `train=False`? Typically you would not have to enable Dropout during variable initialization. Even if `train=True`, passing in something like `init_rng={'params': jax.random.PRNGKey(0), 'dropout': jax.random.PRNGKey(1)}` should not throw the error you saw.
