### ISSUE TITLE
Need to explain lax.dot_general in Flax basics

### ISSUE THREAD

**Issue by minkooseo** [google/flax#3261]
### Problem you have encountered:
In the Module Parameters section of [Flab basics](https://flax.readthedocs.io/en/latest/guides/flax_basics.html), there's a line of code with TODO under `SimpleDense`.

```
    y = lax.dot_general(inputs, kernel,
                        (((inputs.ndim - 1,), (0,)), ((), ())),) # TODO Why not jnp.dot?
```

Could you pleaes add explanation why it's not jnp.dot? It's the first doc I read and this line made me feel wonder if I can rely on tutorials to learn flax.

### What you expected to happen:
Using jnp.dot on the line. Or some high level explanation.

**Comment by chiamp** [comment]
Apologies, `lax.dot_general` can be used for more general dot product operations, but using `jnp.dot` will work as well and would simplify the code. I opened a PR to change it to `jnp.dot`
