### ISSUE TITLE
ResNetV1 implementation is actually ResNetV1.5

### ISSUE THREAD

**Issue by borshigida** [google/flax#3275]
[Downsampling is performed by the 3x3 convolution](https://github.com/google/flax/blob/3ea6381139a340fa7b29c74a84205d8bad18b489/examples/imagenet/models.py#L74), which means it is actually [ResNetV1.5](https://catalog.ngc.nvidia.com/orgs/nvidia/resources/resnet_50_v1_5_for_pytorch), not ResNetV1 as claimed. (In the original version the first convolution in the block has stride 2: see [original paper](https://arxiv.org/pdf/1512.03385.pdf), the caption to Table 1.)

**Comment by chiamp** [comment]
Thanks for catching this! I'll open up a PR to update the description.
