### ISSUE TITLE
Callable/ Module fields are seen as unbound modules

### ISSUE THREAD

**Issue by joeryjoery** [google/flax#3279]
### System information
Irrelevant.

### Problem you have encountered:
I'm new to flax, but when building composite modules I wasn't able to call field modules directly without getting unbound errors. I was able to get around this by defining proxy functions, however, this becomes more and more unreadable as I add callable/ module fields.

### What you expected to happen:
It would be nice to be able to call `myModule.apply(..., method=myModule.field)` instead of `myModule.apply(..., method=myModule.proxy_to_field)`. This is more readable and intuitive. At the moment, the design does not allow me to easily use the builder design pattern (or other factory patterns) to populate Module callables for a larger composite Module. The workaround requries me to either predefine proxy methods for all fields or write a possibly conflicting meta-class or something else.

### Logs, error messages, etc:
```python
CallCompactUnboundModuleError             Traceback (most recent call last)
Cell In[21], line 1
----> 1 mya.apply(v, jnp.zeros(3), method=mya.b)

    [... skipping hidden 5 frame]

File ~/anaconda3/envs/jax/lib/python3.9/site-packages/flax/linen/module.py:953, in Module._call_wrapped_method(self, fun, args, kwargs)
    951 if is_compact_method:
    952   if self.scope is None:
--> 953     raise errors.CallCompactUnboundModuleError()
    954   is_recurrent = self._state.in_compact_method
    955   self._state.in_compact_method = True

CallCompactUnboundModuleError: Can't call compact methods on unbound modules (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.CallCompactUnboundModuleError)
```

### Steps to reproduce:
```python
import flax
import flax.linen as nn

import jax
import jax.numpy as jnp

class A(nn.Module):
    b: nn.Module
    
    def do(self, x):
        # Proxy to call `b`.
        return self.b(x)
    
    @nn.compact
    def __call__(self, x):
        return self.b(x)
    

myA = A(nn.Dense(3))
v = myA.init(jax.random.PRNGKey(0), jnp.zeros(3))

# call myA.b through the proxy: Works
myA.apply(v, jnp.zeros(3), method=myA.do)

# call myA.b directly: Doesn't work
myA.apply(v, jnp.zeros(3), method=myA.b)
>> CallCompactUnboundModuleError             Traceback (most recent call last)
>> Cell In[21], line 1
>> ----> 1 mya.apply(v, jnp.zeros(3), method=mya.b)
```

**Comment by joeryjoery** [comment]
I wanted to share another example of a hacky way to solve my problem, simply by generating functions that assign methods for each module field.

```python
def module_methods(m: nn.Module):
    for field in fields(m):
        if field.type == nn.Module:
            name = field.name
            
            def fun(self, *a, **k):
                return getattr(self, name)(*a, **k)

            setattr(m, f'{name.lstrip("_")}', fun)  # Assign generated method to the public module field
    return m


@module_methods
class A(nn.Module):
    _b: nn.Module  # Make module field private with '_'
    
    def do(self, x):
        return self.b(x)
    
    @nn.compact
    def __call__(self, x):
        return self.b(x)
```

Implemented in this way, the code below does not generate errors.

```python
# call myA.b through the proxy: Works
myA.apply(v, jnp.zeros(3), method=myA.do)

# call myA.b directly: Now it works because the decorator assigned a method to the `b` field.
myA.apply(v, jnp.zeros(3), method=myA.b)
```

**Comment by cgarciae** [comment]
Hey @joeryjoery, one very simple way to solve this is just by passing lambda to `method` that calls `b`:

```python
myA.apply(v, jnp.zeros(3), method=lambda m, *args: m.b(*args))
```
That said, in #3281 I am improving `method`'s string support such that you would be able to just do this:

```python
myA.apply(v, jnp.zeros(3), method="b")
```

**Comment by joeryjoery** [comment]
> Hey @joeryjoery, one very simple way to solve this is just by passing lambda to `method` that calls `b`:
> 
> ```python
> myA.apply(v, jnp.zeros(3), method=lambda m, x: m.b(x))
> ```
> 
> That said, in #3281 I am improving `method`'s string support such that you would be able to just do this:
> 
> ```python
> myA.apply(v, jnp.zeros(3), method="b")
> ```

Ha that is amazing, great! I'll use the lambda method for now then until the PR is merged, you can also close this issue afterwards.

On a small sidenote, does that mean that #3281 only allow's the string `method="b"` or also a direct reference `method=myA.b`? I tend to use direct references over strings at the moment because of typos in strings (I can of course use `myA.b.__name__` but I don't like to use direct access of dunders).

**Comment by cgarciae** [comment]
You can use both strings or functions, this is already supported :)
The PR only improves string support for sub-modules to enable this use case.
