### ISSUE TITLE
Add `.find` and `.find_all` to Cursor API

### ISSUE THREAD

**Issue by chiamp** [google/flax#3309]
Given a function `f(path, value) -> bool`, `Cursor.find_all(f)` would return a generator of cursor objects that fulfill the condition function `f` (or an empty generator if the condition was never fulfilled). Example code usage:
```
c = cursor(config)
for layer_cursor in c.find_all(lambda path, x: isinstance(x, LayerConfig)):
  layer_cursor.attention.dropout = 0.5
  layer_cursor.attention.abc = 1
mutated_obj = c.build()
```
`Cursor.find(f)` would do something similar, except it'll return a single cursor object. Example code usage:
```
cursor(tree).find(lambda x: isinstance(x, Foo)).some_property_of_foo.set(4)
```
If no object or more than one object is found, we could have the following behavior:
* do nothing, and simply return `None` or the first object found that fulfills the condition of function `f`
* raise an error if no object or more than one object is found that fulfills the condition of function `f`
* add arguments to `Cursor.find(f, raise_if_empty=True, raise_if_more_than_one=True)` so that the user can choose which behavior they want

**Comment by chiamp** [comment]
@marcvanzee @cgarciae @levskaya

**Comment by marcvanzee** [comment]
I think it makes sense to just return the first occurrence when someone calls `find`. Throwing an error seems overly cautious, I think people often want to get the first (possibly only) occurrence without having to create an iterator.

This also is the default in other places like Python's [`string.find`](https://www.google.com/url?q=https://www.w3schools.com/python/ref_string_find.asp&sa=D&source=docs&ust=1694106586353886&usg=AOvVaw0-wkCkkdColOXbCpS_PDrj) or [`re.search`](https://www.guru99.com/python-regular-expressions-complete-tutorial.html).

**Comment by marcvanzee** [comment]
@cgarciae since he's reviewing the PR.

**Comment by cgarciae** [comment]
I am a bit hessitant of `find` returning the first instance when there is more than one due the non-deterministic behaviour of the traversal based on key order or just due to structure updates. I'd prefer the user explicitly handling the inconsistency instead of possibly introducing subtle bugs.

**Comment by chiamp** [comment]
I had a discussion with @cgarciae and we settled with:
* raising an error if no object is found
* adding an input argument `raise_error` that if `True`, will raise an error if more than one object is found, otherwise it will return the first occurrence (the default value for `raise_error` is `True`)

**Comment by marcvanzee** [comment]
@cgarciae  Hmmm I didn't realize the traversal is non-deterministic, could you elaborate why this is the case?

@chiamp Given that traversal is non-deterministic I wonder if it makes sense at all to return the first occurrence, even if it is behind a flag?

**Comment by chiamp** [comment]
After discussing with @marcvanzee and @cgarciae, we have decided to raise an error when calling `.find_all` if more than one object is found.

**Comment by cgarciae** [comment]
*`find`
