### ISSUE TITLE
Should we override magic/dunder methods for the Cursor API?

### ISSUE THREAD

**Issue by chiamp** [google/flax#3311]
For example, if we override `__add__`:
```
class Cursor(Generic[A]):
  obj: A
  parent_key: Optional[ParentKey[A]]
  ...
  def __add__(self, other):
    return self.obj + other
```
It would allow us to do something like this:
```
c = cursor({'a': 1, 'b': {'c': 2, 'd': 3}})
c['b']['d'] += 1
c.build()
```
Rather than:
```
c = cursor({'a': 1, 'b': {'c': 2, 'd': 3}})
c['b']['d'] = c['b']['d'].obj + 1
c.build()
```

**Comment by chiamp** [comment]
@marcvanzee @cgarciae @levskaya

**Comment by cgarciae** [comment]
I think it makes a lot of sense. I don't think we want to expose `.obj` to the user.
We would also have to support updating the current update value:

```python
c = cursor({'a': 1, 'b': {'c': 2, 'd': 3}})
c['b']['d'] += 1
c['b']['d'] += 1
c.build()
```

**Comment by marcvanzee** [comment]
Looks like a good idea to me! Maybe rename `self.obj` to `self._obj` if we don't want to expose it to make more explicit it is private.
