### ISSUE TITLE
checkpoints.save_checkpoint error

### ISSUE THREAD

**Issue by asparius** [google/flax#3417]
Faced this issue in a cluster environment, while it works in colab. Original notebook is the below.

(https://colab.research.google.com/github/phlippe/uvadlc_notebooks/blob/master/docs/tutorial_notebooks/JAX/tutorial17/SimCLR.ipynb).

### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`:
- Python version:3.8
- GPU/TPU model and memory: V100 32 gb, also tried in T4
- CUDA version (if applicable): 11.8.0

Name: flax
Version: 0.7.2
Summary: Flax: A neural network library for JAX designed for flexibility
Home-page: None
Author: None
Author-email: Flax team <flax-dev@google.com>
License: None
Location: /scratch/users/ocagatan19/hpc_run/envsigclr/lib/python3.8/site-packages
Requires: numpy, tensorstore, typing-extensions, orbax-checkpoint, rich, jax, optax, PyYAML, msgpack
Required-by: flaxmodels

Name: jax
Version: 0.4.13
Summary: Differentiate, compile, and transform Numpy code.
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: /scratch/users/ocagatan19/hpc_run/envsigclr/lib/python3.8/site-packages
Requires: importlib-metadata, ml-dtypes, opt-einsum, numpy, scipy
Required-by: orbax-checkpoint, optax, flaxmodels, flax, chex

Name: jaxlib
Version: 0.4.13+cuda11.cudnn86
Summary: XLA library for JAX
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: /scratch/users/ocagatan19/hpc_run/envsigclr/lib/python3.8/site-packages
Requires: ml-dtypes, scipy, numpy
Required-by: orbax-checkpoint, optax, flaxmodels, chex

### Problem you have encountered:
Even though training works perfectly, it fails to save the checkpoint.

### Logs, error messages, etc:

/lib/python3.8/site-packages/flax/training/checkpoints.py", line 659, in save_checkpoint
    ocp.PyTreeCheckpointHandler(restore_with_serialized_types=False)
TypeError: __init__() got an unexpected keyword argument 'restore_with_serialized_types'

### Steps to reproduce:
checkpoints.save_checkpoint(ckpt_dir=self.log_dir,
                                    target={'params': self.state.params, 
                                            'batch_stats': self.state.batch_stats},
                                    step=step,
                                    overwrite=True)

**Comment by asparius** [comment]
Solved the issue by using Orbax checkpointing.

**Comment by excitedkid** [comment]
> Solved the issue by using Orbax checkpointing.

I got same error. Can you explain more detailed?

**Comment by stevenygd** [comment]
Face the same issue.

**Comment by 4ku** [comment]
same issue

**Comment by 4ku** [comment]
@stevenygd Fixed with `pip install orbax-checkpoint==0.5.10`

**Comment by sriyash421** [comment]
i installed orbax-checkpoint==0.4.1 and it was compatible with jax and jaxlib == 0.4.13

**Comment by beckashi** [comment]
Same here. I am using Python 3.8, JAX 0.4.13, orbax-checkpoint=0.2.3 and flax=0.7.2. None of the newer orbax-checkpoint versions worked for me — PyPI gave: `ERROR: Could not find a version that satisfies the requirement orbax-checkpoint==0.5.10 (from versions: 0.0.0, 0.1.1, 0.1.4, 0.1.6, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3)`.  

[Downgraing flax to 0.6.1](https://github.com/jonbarron/camp_zipnerf/issues/2#issuecomment-1916117104) didn't work either.

but I fixed it with [this way](https://github.com/Alescontrela/viper_rl/issues/3) : 
`pip install flax==0.6.11`

**Comment by yangzhao-666** [comment]
```
import orbax.checkpoint as ocp
checkpointer = ocp.Checkpointer(ocp.PyTreeCheckpointHandler())
checkpoints.save_checkpoint(
    ..., 
    orbax_checkpointer=checkpointer,
)

```
solves my problem without downgrading flax to 0.6.11, I'm using `python=3.8, jax=0.4.13, flax=0.7.2`
