### ISSUE TITLE
Create `.ipynb` notebooks for guides

### ISSUE THREAD

**Issue by chiamp** [google/flax#3457]
Python notebooks were deleted from their corresponding guides in #3434 because of discrepancy issues. We should consider the following:

- [ ] add them again and have them be up-to-date with their corresponding guide
- [ ] set-up redirects when necessary so that the URL's of the old deleted notebooks now point to the new notebooks
- [ ] add a pre-commit hook that can either check when the guide and corresponding notebook have been modified or out-of-sync, and auto-fix it if possible

**Comment by VictorPrins** [comment]
I am happy to work on this as well. My PR #3450 is also related to this. Could you give some feedback on that PR?

**Comment by chiamp** [comment]
Closing after #3434 merged
