### ISSUE TITLE
Quickstart doc doesn't exist

### ISSUE THREAD

**Issue by romanngg** [google/flax#3466]
The "Quickstart" button in https://flax.readthedocs.io/en/latest/#learn-more leads to a 404 page https://flax.readthedocs.io/en/latest/quick_start.html

Looks like it was deleted in https://github.com/google/flax/commit/1383ea3090a4c744bbf1a2892ac2cce40ace5bac

**Comment by chiamp** [comment]
thanks for catching this! Should be fixed now
