### ISSUE TITLE
Fix docs to make them compatible with zsh

### ISSUE THREAD

**Issue by carlosgmartin** [google/flax#3473]
For example, the [contributing docs](https://flax.readthedocs.io/en/latest/contributing.html) give the following commands:
```
pip install -e .[all]
pip install -e .[testing]
```

Running these commands on zsh yields:
```
$ python3 -m pip install -e .[all]    
zsh: no matches found: .[all]
$ python3 -m pip install -e .[testing]
zsh: no matches found: .[testing]
```

The issue is caused by the square brackets.
It can be fixed by wrapping the argument in quotes, as in `".[all]"`, `".[testing]"`, etc.

Jax had the same issue in its docs, and it was fixed:
* https://github.com/google/jax/pull/7126
* https://github.com/google/jax/pull/9194
* https://github.com/google/jax/issues/14315

**Comment by chiamp** [comment]
Fixed! Thanks for catching this
