### ISSUE TITLE
Add missing `mask` arguments to `__call__` methods of normalization modules

### ISSUE THREAD

**Issue by carlosgmartin** [google/flax#3508]
Currently, only [BatchNorm](https://flax.readthedocs.io/en/latest/api_reference/flax.linen/layers.html#flax.linen.BatchNorm.__call__) receives a `mask` argument in its `__call__` method.

**Feature request:** Add the same `mask` argument to the remaining normalization modules:
* [LayerNorm](https://flax.readthedocs.io/en/latest/api_reference/flax.linen/layers.html#flax.linen.LayerNorm.__call__)
* [GroupNorm](https://flax.readthedocs.io/en/latest/api_reference/flax.linen/layers.html#flax.linen.GroupNorm.__call__)
* [RMSNorm](https://flax.readthedocs.io/en/latest/api_reference/flax.linen/layers.html#flax.linen.RMSNorm.__call__)

I can submit a PR for this, if desired.

**Comment by chiamp** [comment]
Closing this after #3510 landed
