### ISSUE TITLE
Release 0.2.0 from current master to fix `python_version<'3.7'` for dataclasses

### ISSUE THREAD

**Issue by SimonBiggs** [google/flax#351]
### Problem you have encountered:
Unable to include flax as a pypi dependency because the `python_version<'3.7'` line of code is not within the pypi release:

https://github.com/google/flax/blob/060737d406bbe0bc353fa034cf76efea4e6fceac/setup.py#L33

### Recommended Fix

Create a 0.2.0 pypi release from the current master branch

**Comment by levskaya** [comment]
Hi @SimonBiggs - sorry this took a while, I just uploaded a 0.2.0 release after getting a few minor fixes in.  Closing for now, but feel free to re-open and let us know if anything's still broken.

**Comment by SimonBiggs** [comment]
Awesome, thanks @levskaya :)
