### ISSUE TITLE
NNX Conv documentation states that kernel size can be an integer for 1D convs.

### ISSUE THREAD

**Issue by haydn-jones** [google/flax#3534]
https://github.com/google/flax/blob/829e004c6d5646f24bd048023a4407e3b4d5aa98/flax/experimental/nnx/nnx/nn/linear.py#L368

The NNX Conv documentation says that you can pass kernel size as an integer for 1D convolutions, however, the very first thing the constructor does is throw a TypeError if the kernel size is an integer.

**Comment by Micky774** [comment]
Should we increase the coverage of https://github.com/google/flax/pull/3511 to ensure non-regression?
