### ISSUE TITLE
Bug in Tutorial: Jax 101 Working with PyTrees "AttributeError: module 'jax.tree_util' has no attribute 'register_static'"

### ISSUE THREAD

**Issue by PawKanarek** [google/flax#3535]
In Tutorial: [Jax 101 Working with Pytrees](https://jax.readthedocs.io/en/latest/jax-101/05.1-pytrees.html#custom-pytree-nodes) there is problem with this note: 

> One shortcut is to use jax.tree_util.register_static to register a type as being a node without children:

```python
from typing import NamedTuple, Any

@jax.tree_util.register_static
class StaticStr(str):
  pass


class YetAnotherContainer(NamedTuple):
  name: StaticStr
  a: Any
  b: Any
  c: Any


# NamedTuple subclasses are handled as pytree nodes, so
# this will work out-of-the-box:
jax.tree_util.tree_leaves([
    YetAnotherContainer(StaticStr('Alice'), 1, 2, 3),
    YetAnotherContainer(StaticStr('Bob'), 4, 5, 6)
])
```

### Logs, error messages, etc:
When i run this code in jupyter notebook it throws an error 
```
AttributeError                            Traceback (most recent call last)
/mnt/disks/persist/repos/Dojo/jax/pytrees.ipynb Cell 19 line 3
      1 from typing import NamedTuple, Any
----> 3 @jax.tree_util.register_static
      4 class StaticStr(str):
      5   pass
      8 class YetAnotherContainer(NamedTuple):

AttributeError: module 'jax.tree_util' has no attribute 'register_static'
```
### System information
- OS Platform and Distribution: Ubuntu 20.04.4 LTS
- Flax, jax, jaxlib versions `-> pip show flax jax jaxlib`
<details>
<summary>flax version info</summary>

```
Name: flax
Version: 0.7.2
Summary: Flax: A neural network library for JAX designed for flexibility
Home-page: 
Author: 
Author-email: Flax team <flax-dev@google.com>
License: 
Location: /home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages
Requires: jax, msgpack, numpy, optax, orbax-checkpoint, PyYAML, rich, tensorstore, typing-extensions
Required-by: 
---
Name: jax
Version: 0.4.13
Summary: Differentiate, compile, and transform Numpy code.
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: /home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages
Requires: importlib-metadata, ml-dtypes, numpy, opt-einsum, scipy
Required-by: chex, flax, optax, orbax-checkpoint
---
Name: jaxlib
Version: 0.4.13
Summary: XLA library for JAX
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: /home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages
Requires: ml-dtypes, numpy, scipy
Required-by: chex, optax, orbax-checkpoint
```

</details>

- Python version: Python 3.8.18
- GPU/TPU model and memory: Google TPU v3-8
- CUDA version (if applicable): None
 

### What you expected to happen:
Everything in tutorial works. 

Searching for "register_static" in github https://github.com/search?q=repo%3Agoogle%2Fflax%20register_static&type=code also gives 0 results. 

I suppose that this might be some outdated API.

**Comment by 8bitmp3** [comment]
@PawKanarek Can investigate/triage. Note that this is for the google/jax repo (not google/flax) but we can look at this.

**Comment by 8bitmp3** [comment]
The doc is from `google/jax`, and you can find `jax.tree_util.register_static` here (in the `google/jax` repo, not `/flax`):

https://github.com/google/jax/blob/ad14478dd9df89aee06dbdaad6259c70d5736b63/jax/_src/tree_util.py#L740

Does this answer your question?

cc @jakevdp

**Comment by PawKanarek** [comment]
Sorry! Posted this in wrong repository! They look so similar :D

**Comment by jakevdp** [comment]
Answered in https://github.com/google/jax/issues/18840
