### ISSUE TITLE
Pooling: passing "sequence of `n` `(low, high)` integer pairs" resulting in TypeError

### ISSUE THREAD

**Issue by rolandgvc** [google/flax#356]
Trying to pass a tuple or list of tuples to a pool operation's padding parameter gives out the following errors: 
`TypeError: Unknown padding type: (1, 1).`
`TypeError : unhashable type: 'list' `

Sample code for reproducing the bug:
```python3
from flax import nn
from jax import random

class FlaxModel(nn.Module):
    def apply(self, x):
        x = nn.max_pool(x, (3, 3), strides=(2, 2), padding=[(1, 1), (1, 1)])
        return x

rng = random.PRNGKey(0)
model, _ = FlaxModel.init_by_shape(rng, [(1, 100, 100, 1)])
```

**Comment by avital** [comment]
Indeed looks like our code doesn't support padding that's a sequence of pairs. @hawkinsp has said that the version of JAX on HEAD added support for this, we should add a test and plumb it through correctly. (Or in the meanwhile if that's impossible, support this by manually padding before calling into `lax.reduce_window`)

**Comment by hawkinsp** [comment]
Yes, JAX at head supports a sequence of `(low, high)` padding pairs.

Flax probably still needs to do some work to add batch and feature dimensions to what the user provides. JAX and XLA don't have opinions about which dimensions are batch and which are feature, but Flax is documented to only accept padding for the spatial dimensions.
