### ISSUE TITLE
NNX attention layer missing `qkv_features` arg

### ISSUE THREAD

**Issue by chiamp** [google/flax#3564]
In Linen, the input arg [`qkv_features`](https://github.com/google/flax/blob/main/flax/linen/attention.py#L431) determines the [head dimension](https://github.com/google/flax/blob/main/flax/linen/attention.py#L436) while the input arg [`out_features`](https://github.com/google/flax/blob/main/flax/linen/attention.py#L430) determines the [output dimension](https://github.com/google/flax/blob/main/flax/linen/attention.py#L559).

In NNX, the input arg [`out_features`](https://github.com/google/flax/blob/main/flax/experimental/nnx/nnx/nn/attention.py#L318) determines **BOTH** the [head dimension](https://github.com/google/flax/blob/main/flax/experimental/nnx/nnx/nn/attention.py#L344) and the [output dimension](https://github.com/google/flax/blob/main/flax/experimental/nnx/nnx/nn/attention.py#L376).

We can get equivalent behavior with the following instantiation:
```
x = jnp.ones((12, 8))
num_heads = 4

linen_attention = nn.MultiHeadDotProductAttention(num_heads)
linen_out, variables = linen_attention.init_with_output(jax.random.key(0), x)

nnx_attention = nnx.MultiHeadAttention(num_heads, in_features=8, rngs=nnx.Rngs(0))
nnx_out = nnx_attention(x)

assert linen_out.shape == nnx_out.shape

for qkvo in ('query', 'key', 'value', 'out'):
  for kb in ('kernel', 'bias'):
    linen_shape = variables['params'][qkvo][kb].shape
    nnx_shape = getattr(getattr(nnx_attention, qkvo), kb).shape
    print(qkvo, kb, linen_shape, nnx_shape)
```
```
query kernel (8, 4, 2) (8, 4, 2)
query bias (4, 2) (4, 2)
key kernel (8, 4, 2) (8, 4, 2)
key bias (4, 2) (4, 2)
value kernel (8, 4, 2) (8, 4, 2)
value bias (4, 2) (4, 2)
out kernel (4, 2, 8) (4, 2, 8)
out bias (8,) (8,)
```
But if we add in a `qkv_features` arg input into the Linen layer:
```
linen_attention = nn.MultiHeadDotProductAttention(num_heads, qkv_features=16)
```
We'll get a different result:
```
query kernel (8, 4, 4) (8, 4, 2)
query bias (4, 4) (4, 2)
key kernel (8, 4, 4) (8, 4, 2)
key bias (4, 4) (4, 2)
value kernel (8, 4, 4) (8, 4, 2)
value bias (4, 4) (4, 2)
out kernel (4, 4, 8) (4, 2, 8)
out bias (8,) (8,)
```
Currently NNX can't replicate this behavior. Should we add a `qkv_features` argument to the NNX attention layer?

**Comment by chiamp** [comment]
cc: @cgarciae

**Comment by cgarciae** [comment]
Thanks for catching this Marcus! Created a PR with a fix.
