### ISSUE TITLE
Quick start badges point to 404

### ISSUE THREAD

**Issue by MartinuzziFrancesco** [google/flax#3589]
The badges [Open in Colab](https://colab.research.google.com/github/google/flax/blob/main/docs/getting_started.ipynb) and [Open on Github](https://github.com/google/flax/blob/main/docs/getting_started.ipynb) in the [quick start](https://flax.readthedocs.io/en/latest/quick_start.html) section of the documentation return `Notebook not found` and `404 - page not found` respectively. I suppose that there was a renaming of the notebook since there is a [quick start](https://github.com/google/flax/blob/main/docs/quick_start.ipynb) example, but the links in the toggles have not been updated

**Comment by chiamp** [comment]
Thanks for catching this! Fixed with #3610
