### ISSUE TITLE
[struct.dataclass] Consider adding optional `kw_only` arguments

### ISSUE THREAD

**Issue by epignatelli** [google/flax#3617]
I often run into the following issue:

```python
from flax import struct

class Foo(struct.PyTreeNode):
  bar: int = struct.field(pytree_node=False, default=1)

class Baz(Foo):
  qux: str
```

Since `qux` does not have a default value, I get:
```
Fields without default values cannot appear after fields with default values
```

Can we consider adding a simple wrapper to `dataclasses.dataclass(kw_only=True)`?

It should be easy for the `struct.dataclass`, we can maybe have another object for inheritance, like `PyTreeNodeKwOnly`?

**Comment by chiamp** [comment]
#3645 allows you to pass in general kwargs to `struct.dataclass`, so you should be able to use `kw_only=True` now.

#3651 adds a test to test this `kw_only` functionality. Please note that `kw_only` is only available for python 3.10 or higher. Currently Flax supports, python 3.9 or higher, and so this test is commented out until Flax upgrades its minimum version requirement.

**Comment by epignatelli** [comment]
Thanks @chiamp, would #3645 pass the test case in the issue above?

**Comment by chiamp** [comment]
Yes, you could do something like this:
```
from flax import struct
import functools

@functools.partial(struct.dataclass, kw_only=True)
class Foo():
  bar: int = struct.field(pytree_node=False, default=1)

@struct.dataclass
class Baz(Foo):
  qux: str

b = Baz('qux_value', bar=123)
print(b)
# Baz(bar=123, qux='qux_value')
```

**Comment by epignatelli** [comment]
Thanks, @chiamp, that is a different test case, though.
The original one still fails.

In the second test case, Pylance also does not recognise that `Baz` has a `bar` attribute: `No parameter named "bar"`.

Is there any plan to fully support type checking with this and propagate the change to the `PyTreeNode` class?

**Comment by chiamp** [comment]
Sorry for the delay. After #3785, `PyTreeNode` can take additional kwargs just like `struct.dataclass`.

**Comment by epignatelli** [comment]
That's great, thanks @chiamp !
