### ISSUE TITLE
Refactor to avoid use of lax.reduce_window_shape_tuple

### ISSUE THREAD

**Issue by jekbradbury** [google/flax#370]
(motivated by https://github.com/google/jax/pull/3803)

`lax.reduce_window_shape_tuple` is not a JAX public API, and we change it from time to time.

A better alternative would be to use the public API `jax.eval_shape` to compute the output shape of a `reduce_window` operator.

Thanks!

**Comment by levskaya** [comment]
@jekbradbury - I don't see this function used anywhere in the flax repo?  Am I missing it somewhere?

**Comment by jheek** [comment]
Closing because `lax.reduce_window_shape_tuple` does not appear anywhere in the flax source. @jekbradbury Please re-open if you still think this is an issue
