### ISSUE TITLE
How to initialize parameters without allocating

### ISSUE THREAD

**Issue by ethanabrooks** [google/flax#378]
Suppose I have an existing `nn.Model`:
```python
x = jnp.ones((1, 2))
module = Dense.partial(features=4)
ys, initial_params = module.init(random.PRNGKey(0), x)
model = nn.Model(module, initial_params)
```
How would I replace the parameters of `model` with a newly initialized set of parameters _without_ allocating any new memory? I am a little new to flax, and I am concerned that a naive approach might perform an allocation and a copy.

Thanks!

**Comment by levskaya** [comment]
So the funny thing about JAX is that you often write code that looks purely functional, e.g. `p_new = f(p_old)` that would literally interpreted require creating new memory.  However we rely on the XLA compiler under `jit` and `pmap` to alias buffers and to reuse memory when possible.  The mechanism for telling XLA to reuse a large pytree of parameters during e.g. an training loop update step is the `donate_argnums` argument to jit/pmap, as documented here:
[jax.jit donate_argnums](https://jax.readthedocs.io/en/latest/jax.html#jax.jit)
[jax.pmap donate_argnums](https://jax.readthedocs.io/en/latest/jax.html#jax.jit)

Now, if you're not running under jit/pmap, you can reason about memory by remembering that JAX uses python reference counting to determine when to clear device buffers.  If you're really working near device memory limits interactively, you could always copy part of the parameters back to host memory, clear them from device memory, modify those parameters in-place on the host by tree traversals or any other mechanism, then copy the modified data back to device:
```python
import numpy as np
# transfer to host
p = np.array(model.params['kernel'])
# delete reference, will eventually free buffer memory
model.params.pop('kernel')
# mutate
p[0, 1] = 1.0
# transfer mutated array back to device
model.params['kernel'] = jnp.array(p)
```

Hopefully that clarifies things a bit.

**Comment by ethanabrooks** [comment]
Thanks for the response. I am currently using the `.replace` argument which I assume works similarly to what you posted.
Is it safe to assume that the following script would not allocate memory more than once?
```python
shape = [([1000], float)]
adam = optim.Adam(learning_rate=0.1)
partial = Net.partial()
_, params = partial.init_by_shape(next(rng), shape)
net = nn.Model(partial, params)

optimizer = jax.device_put(adam.create(net))
_, params = partial.init_by_shape(next(rng), shape)  # HERE
net = net.replace(params=params)
optimizer = jax.device_put(adam.create(net))  # HERE
```
I did some profiling on and off GPU and it looks like no additional memory is being allocated at the lines with the `HERE` comment.
