### ISSUE TITLE
Documentation/notebook errors

### ISSUE THREAD

**Issue by st--** [google/flax#3837]
- https://flax.readthedocs.io/en/latest/guides/flax_fundamentals/flax_basics.html is referring to "_JAX for the impatient_ notebook", which only existed in previous versions of Flax
- the example in https://flax.readthedocs.io/en/latest/experimental/nnx/nnx_basics.html#split-merge-and-update is self-inconsistent, it first says `static, state = model.split()` and later says `state, _ = model.split()`
- the `nnx.Module.split` type annotation suggests that the return value is (static, state) when in fact it is (state, static)

Normally I would just fix these in a pull request, but Google's infrastructure keeps refusing/ignoring my CLA...

**Comment by cgarciae** [comment]
Thanks for reporting this! I've created #3839 to fix NNX Basics.

**Comment by chiamp** [comment]
Closing this issue as #3839 is now merged.
