### ISSUE TITLE
nnx.graph.split infinite recursion when used in a thread

### ISSUE THREAD

**Issue by NeilGirdhar** [google/flax#3899]
The following examples shows how a simple NNX module causes infinite recursion when split in a thread.  Jax PyTrees do not have this problem.

```python
from threading import Thread
from typing import override

from flax.experimental import nnx

class X(nnx.Module, experimental_pytree=True):
    pass

x = X()

class MyThread(Thread):
    @override
    def run(self) -> None:
        nnx.graph.split(x)  # Infinite recursion.

thread = MyThread()
thread.start()
thread.join()
```

### System information
- Ubuntu 24.04
- flax==0.8.3, jax==0.4.26
- Python version 3.12

**Comment by NeilGirdhar** [comment]
This appears to be two bugs:
* the node registry is not shared between threads, and
* when the registry is empty, there is infinite recursion.

**Comment by cgarciae** [comment]
@NeilGirdhar can we close this issue?

**Comment by NeilGirdhar** [comment]
Yes, sure.  I'm not affected by the infinite recursion, but if it happens to someone else we can reopen.
