### ISSUE TITLE
Documentation links 404

### ISSUE THREAD

**Issue by namiller** [google/flax#3917]
Most documentation links 404.

For example a google search for "[flax logically partitioned](https://www.google.com/search?q=flax+logically+partitioned&oq=flax+&gs_lcrp=EgZjaHJvbWUqCAgAEEUYJxg7MggIABBFGCcYOzIPCAEQLhhDGLEDGIAEGIoFMgYIAhBFGDwyBggDEEUYPDIGCAQQRRg8MgYIBRBFGDwyBggGEEUYPDIGCAcQRRhA0gEIMTY3OWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8#ip=1)"

yields [this page](https://flax.readthedocs.io/en/latest/api_reference/flax.linen/_autosummary/flax.linen.LogicallyPartitioned.html) as the first result. Which 404s.

This seems to happen every year or so - perhaps some automated testing is warranted?
https://github.com/google/flax/issues/2335
https://github.com/google/flax/issues/3173

**Comment by chiamp** [comment]
related to #3854

**Comment by IvyZX** [comment]
The google results seems to be valid now.
