### ISSUE TITLE
nn.Dense doesn't respect the provided dtype

### ISSUE THREAD

**Issue by dfdx** [google/flax#3945]
I'm quite confused about the behavior of `dtype` argument in Flax module, in particular `flax.linen.Dense`. 

### Problem you have encountered:

```python
import flax.linen as nn
import jax.numpy as jnp
import jax

dense = nn.Dense(features=4, dtype=jnp.float16)                                # note dtype
dense.init(jax.random.key(0), jnp.ones((3, 4), dtype=jnp.float16))             # note dtype
```

### What you expected to happen:

I expected parameters to have the provided type `float16`.

### Logs, error messages, etc:

Instead, parameters have type `float32`

```python
{'params': {'kernel': Array([[-0.2703914 ,  0.17842741, -0.38600636, -0.11052043],
         [-0.5053559 , -0.3536495 ,  0.28471673,  0.52417654],
         [ 0.01603765, -0.09229418, -0.40094987,  0.19372654],
         [-0.62961626, -0.43575877,  0.25030312,  0.66263646]],      dtype=float32),
  'bias': Array([0., 0., 0., 0.], dtype=float32)}}
```

Do I misunderstand how it should work?

### System information

- OS Platform:  22.04.1-Ubuntu x86_64 GNU/Linux (running in a Docker container)
- versions:
   * flax==0.8.4
   * jax==0.4.26
   * jaxlib==0.4.26+cuda12.cudnn89
- Python version: 3.10.12
- GPU: NVIDIA H100 80Gb
- CUDA version: 12.4
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by PhilipVinc** [comment]
dtype is the output dtype. param_dtype is the dtype of the parameters.
