### ISSUE TITLE
Reduce the number of Conv layers in ResNet18 and 34?

### ISSUE THREAD

**Issue by aabdolrashidi** [google/flax#395]
In the current ResNet model (`examples/imagenet/models.py`), there are three `Conv` layers in every `ResidualBlock` instance regardless of the number of layers. This is accurate for ResNet50 and above. ResNet18 and 34, however, are known to use two `Conv` layers per block instead. It would be fitting to bypass the 3rd `Conv` for models with less than 50 layers.

**Comment by jheek** [comment]
This should be fixed in PR #397
