### ISSUE TITLE
typo in nnx_basics.md

### ISSUE THREAD

**Issue by notnot** [google/flax#4046]
Replace 
Since Modules hold their own state methods can be called directly without the no need for a separate apply method
by
Since Modules hold their own state methods can be called directly without the need for a separate apply method

**Comment by rajasekharporeddy** [comment]
Thanks for reporting. #4047 will fix this.

**Comment by notnot** [comment]
Found another one...

Replace
In practice this means that NNX programs can be express using imperative code
by
In practice this means that NNX programs can be expressed using imperative code

**Comment by rajasekharporeddy** [comment]
Thanks! #4050 addresses the typos in nnx_basics.md file.
