### ISSUE TITLE
nnx.initializers.uniform should support custom lower and upper bounds

### ISSUE THREAD

**Issue by SamPruden** [google/flax#4127]
This is a tiny petty usability thing, but I just had to write this as an `nnx.Conv` argument

```python
kernel_init = lambda key, shape, dtype: jax.random.uniform(
  key, shape, dtype,
  minval = -args.conv_init,
  maxval = args.conv_init
) if args.conv_init else None,
```

Which felt quite silly because it felt like I should be able to do

```python
kernel_init = nnx.initializers.uniform(-args.conv_init, args.conv_init) if args.conv_init else None,
```

However `initializers.uniform` only takes a single `scale` parameter and outputs in `[0, scale)` for some reason. I would say that where applicable the initializers should act like wrappers around the equivalent `jax.random` functions and offer the same options.

I would say the same for `initializers.normal`, however I've just noticed that `random.normal` doesn't let you choose the mean or stddev. That's quite surprising. I would expect those options to be available in both places.

**Comment by cgarciae** [comment]
Hey, we mostly just re-export jax's initializers from [jax.nn.initializers](https://jax.readthedocs.io/en/latest/jax.nn.initializers.html) for convenience.
