### ISSUE TITLE
`test_vmap_and_cond_passthrough[_error]` tests fail

### ISSUE THREAD

**Issue by GaetanLepage** [google/flax#4211]
Context: [bumping `flax` from 0.8.5 to 0.9.0 in nixpkgs](https://github.com/NixOS/nixpkgs/pull/342970).

### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NixOS
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`: jax[lib]==0.4.28, flax==0.9.0
- Python version: 3.12
- GPU/TPU model and memory: -
- CUDA version (if applicable): -

### Problem you have encountered:
When running the test suite, I encounter two failures:
```
=========================== short test summary info ============================
FAILED flax/nnx/tests/transforms_test.py::TestVmap::test_vmap_and_cond_passthrough - ValueError: vmap has mapped output but out_axes is None
FAILED flax/nnx/tests/transforms_test.py::TestVmap::test_vmap_and_cond_passthrough_error - AssertionError: "at vmap.*'broadcast'.*got axis spec None but output was ba...
================== 2 failed, 1924 passed, 3 skipped in 29.49s ==================
```

### What you expected to happen:
All tests succeed.

### Steps to reproduce:
```
pytest
```

**Comment by GaetanLepage** [comment]
https://github.com/google/flax/issues/3319 is possibly related.

**Comment by cgarciae** [comment]
@GaetanLepage can you update `jax` to latests? This is a jax issue we fixed recently.

**Comment by GaetanLepage** [comment]
Thanks for the quick answer.
Actually, we are currently stuck with 0.4.28 for now as the more recent versions have introduced breaking changes regarding packaging.
For now, we will simply go on and skip those tests and work towards our jax update.

As this is not an issue on the flax side, I will be closing it.
