### ISSUE TITLE
JAX update broke my random initialization of a Flax network

### ISSUE THREAD

**Issue by stanislavfort** [google/flax#428]
I am using Flax to define my neural nets by extending the flax.nn.Module. An example could be:

```
class MyNewNet(flax.nn.Module):
 def apply(self, x)
  return x
```

Then I initialize the network by running:

`_, initial_params = MyNewNet.init_by_shape(jax.random.PRNGKey(123456),[((1, 32, 32, 3), np.float32)])
`

This used to work well until a few weeks ago when (I assume) JAX got updated to a new version. When JAX was version v0.1.47 this code worked fine. I haven't figured out how to repair this and wanted to ask you for your help in figuring it out. I'm not sure if this is a bug, but at least in the documentation I couldn't find a way to resolve it.

**Comment by levskaya** [comment]
Sorry about this!  A fairly large internal change to JAX has happened recently in how jit compilation works, a behavior referred to as "omnistaging".  It mostly doesn't affect Flax, but in some cases partial evaluation (what init_by_shape uses) can break - we're still trying to debug why this is happening.

For now, could you try enabling the new JAX behavior with `jax.config.enable_omnistaging()` at the beginning of your imports and seeing if the problem persists?

**Comment by stanislavfort** [comment]
Adding `jax.config.enable_omnistaging()` after importing jax fixed the problem, thank you!
