### ISSUE TITLE
About the Linen API

### ISSUE THREAD

**Issue by cgarciae** [google/flax#437]
Hey, I am the main developer of [Elegy](https://poets-ai.github.io/elegy/). Initially this library was supposed to be a Keras-like interface on top of an intermediate library like Flax or Haiku. Initially Haiku was chosen but it soon became apparent that if modules didn't have references between them doing stuff like transfer learning would be very painful since you would have to merge parameter structures manually to match the code structure.

So in version `0.2.0` all submodules registered themselves under their parent module and you could very simply extract and reuse them since they also keep track of their own parameters and states. Take a look at this VAE example where the standalone decoder is extracted by reference from the full VAE in order to generate new samples:

https://github.com/poets-ai/elegy/blob/master/examples/mnist_vae.py#L197

But with this change we had to implement our own Module class and port all the layers since we were no longer compatible with Haiku (which was not the initial idea). I recently saw some comments in the Linen API which seem to point in this direction:

https://github.com/google/flax/blob/master/flax/linen/module.py#L51

However it seems the API is very new and there is no documentation. I was wondering if you can give me some details on it capabilities:
* Do modules take with them (have reference to) their parameters and states? 
* How does combining modules look like with this API? Say if you have a trained model and want to put a couple of layers on top to do transfer learning, do you still have to manually merge parameter structures?

**Comment by Davidnet** [comment]
I was closely looking at this, it would be very helpful to see the discussion or guideline on how you guys are doing the linen API design spec, if you could share that with us, that would be awesome! Please and thank you!
