### ISSUE TITLE
AssertionError in MNIST Example

### ISSUE THREAD

**Issue by mr128254** [google/flax#448]
Started out with Flax and stumbled across this article: https://flax.readthedocs.io/en/latest/annotated_mnist.html.
When trying to run, I get an AssertionError on line
```py
  _, initial_params = CNN.init_by_shape(jax.random.PRNGKey(0), [((1, 28, 28, 1), jnp.float32)])
```
This is also described here: https://www.gitmemory.com/issue/google/flax/382/669502890. The proposed solution works, therefore I suggest adding 
```py
from jax.config import config
config.enable_omnistaging()
```

**Comment by avital** [comment]
Sorry for that! We made an internal change to support both omnistaging and pre-omnistaging versions of JAX but forgot to cut a new release. I just made v0.2.1 and uploaded to PyPI so you should no longer need those two lines.
