### ISSUE TITLE
I think linen_linear_test.py is outdated

### ISSUE THREAD

**Issue by LysSanzMoreta** [google/flax#455]
Hi!
I was trying to use the nn.Embed part from here https://github.com/google/flax/blob/0132b3f234a9868b47df491efde870bdc58e97a9/tests/linen/linen_linear_test.py and it's outdated,

Thanks!

**Comment by levskaya** [comment]
@LysSanzMoreta could you provide more detail on what's wrong?  I just double-checked that code and nothing seems wrong there?  This test is invoking the nn.Embed layer in a very unusual way for testing (using an initializer that returns a constant embed table for testing) that you wouldn't normally do.

**Comment by LysSanzMoreta** [comment]
Hi, well maybe I am mistaken, but for example it uses _.init_with_output_ instead of just _.init_
https://github.com/google/flax/blob/0132b3f234a9868b47df491efde870bdc58e97a9/tests/linen/linen_linear_test.py#L229

Although if you say you are using it for testing something else, then maybe that is not the case...

**Comment by levskaya** [comment]
`init_with_output` is a supported, canonical function - it's only used when you want -both- the result of the module computation as well as its initialized variables - it's the sort of thing you often want to do in test code.  For a more canonical usage-example of `Embed` you can look at the "wmt" example that implements a transformer encoder-decoder with embeddings.

**Comment by levskaya** [comment]
I might close this issue for the moment (with the understanding that we will be trying to improve documentation for the linen api over the coming weeks.). If you have further questions/concerns about this feel free to reopen the issue.
