### ISSUE TITLE
Updating examples/mnist

### ISSUE THREAD

**Issue by andsteing** [google/flax#479]
This issue tracks updates the `mnist` example to follow practices outlined in #231.

- [x] Port to linen API - once ported all subsequent changes should be done in `linen_examples/mnist`
- [x]  Update `README.md`
- [x]  Add `requirements.txt`
- [x]  Update file structure
- [x]  Use `ml_collections.ConfigDict`
- [x]  Add benchmark test
- [x]  Add unit test for training/eval step
- [x]  Add Colab
- [x]  Adhere to Google Python style
- [x]  Shorten training loop

Removed list:

- Add mypy annotations - not needed.
- Use `clu` - to keep example more concise

**Comment by avital** [comment]
People look at MNIST in particular for a very concise example. I think some of the items on this checklist make the code more concise, and others make the code more verbose. I think it would be good to lean on the direction of keeping this example short.

**Comment by andsteing** [comment]
Good point!

I removed two points that I think make the example more complicated.

I think it's still good practice to have tests. We could discuss if `ConfigDict` is necessary (especially in this case where we have only few parameters), and whether we want to have mypy annotations (in the sake of consistency I would say yes).
