### ISSUE TITLE
MNIST example bug report: AttributeError: 'SummaryWriter' object has no attribute 'hparams'

### ISSUE THREAD

**Issue by samaritanhu** [google/flax#498]
Hi, thanks for contributing such a nice and neat repository! I have one question when I was trying to run `python mnist_main.py --model_dir=/tmp/mnist`. (I was running on CPU instead of GPU) , and this problem occurs - AttributeError: 'SummaryWriter' object has no attribute 'hparams'. Should I use GPU instead for this code or anything I missed to fix this problem? 

Thanks!

**Comment by mohitreddy1996** [comment]
Hi, `hparams` is defined for `SummaryWriter` here: https://github.com/google/flax/blob/39a04e82d6f97ef90c59425599018f2b9df8b6ea/flax/metrics/tensorboard.py#L169

It's weird that you are getting that error (I was able to run the same command on master and the example ran successfully). Could you install the requirements, sync to master and try again?

**Comment by samaritanhu** [comment]
Hi, I sync to the master and upgraded packages: jax == 0.2.0, jaxlib == 0.1.55, flax == 0.2.1, and this problem still exists :( However, `graph/train.py` works on my MacBook. Maybe my package versions are wrong?

**Comment by mohitreddy1996** [comment]
Do you tensorboard locally installed? Could you try again after installing that? https://pypi.org/project/tensorboard/ 

I believe there is something wrong with the setup. We have a local unit test which exercises this codepath and runs as part of Build. https://github.com/google/flax/blob/104af1319ef84f9cf6fb39594a1147ad7e2ee7d5/examples/mnist/mnist_lib_test.py#L67. 
Could you try installing all dependencies by following the steps here: https://github.com/google/flax/blob/104af1319ef84f9cf6fb39594a1147ad7e2ee7d5/.github/workflows/build.yml#L29

**Comment by samaritanhu** [comment]
Thanks! It worked, and I assume there is something wrong with my tensorboard version. Thanks for devoting your time and I love your repo 👍  :)
