### ISSUE TITLE
Helpful error when kernel_size is not an array in Conv

### ISSUE THREAD

**Issue by freddyaboulton** [google/flax#547]
### Problem you have encountered:
If you try to init a Conv module by setting `kernel_size` to an int, you get an unhelpful error message.

### What you expected to happen:
Helpful error message that explains I should set `kernel_size` to an array.

### Logs, error messages, etc:
`TypeError: object of type 'int' has no len()`

### Steps to reproduce:

```python
from flax import nn
from jax import numpy as jnp, random

class CNN(nn.Module):

    def apply(self, x):
        x = nn.Conv(x, features=32, kernel_size=3)
        x = nn.relu(x)
        return x

cnn = CNN.init(random.PRNGKey(0), jnp.ones((1, 28, 28, 1)))
```

**Comment by avital** [comment]
Good point! We should improve our error message here. (Or maybe we should allow simply passing in a single int? What do other frameworks do here?)

**Comment by avital** [comment]
Sure, then by all means let's also do that. We'll take a pull request for this (with tests) if anyone is interested.

**Comment by freddyaboulton** [comment]
Great! Opened #551 !
