### ISSUE TITLE
The submodule assignment system doesn't understand functools.partial modules

### ISSUE THREAD

**Issue by rolandgvc** [google/flax#575]
As discussed in #565 with @avital, the `__setattr__` system for detecting submodule assignment doesn't understand modules created with `functools.partial`. In the following example,
```python
class ConvBlock(nn.Module):
  out_channels: int = 32
  kernel_size: Sequence[int] = (3,3)
  strides: Optional[Sequence[int]] = None
  padding: Union[str, Sequence[Tuple[int, int]]] = 'VALID'
  train: bool = False
  dtype: Any = jnp.float32

  @nn.compact
  def __call__(self, x):
    x = nn.Conv(self.out_channels, kernel_size=self.kernel_size, strides=self.strides,
                padding=self.padding, use_bias=False, name='conv', dtype=self.dtype)(x)
    x = nn.BatchNorm(use_running_average=not self.train, name='bn', dtype=self.dtype)(x)
    return nn.relu(x)


class Model(nn.Module):
  train: bool = False
  dtype: Any = jnp.float32

  def setup(self):
    self.conv_block = functools.partial(ConvBlock, train=self.train, dtype=self.dtype)

  def __call__(self, x):
    x = self.conv_block(32, kernel_size=(3, 3), strides=(2, 2))(x)
    return x
```
trying to initialize the parameters of `Model` would result in `ValueError: Submodules must be defined in 'setup()' or in a method wrapped in '@compact'`.  I've made a colab where you can try this out: https://colab.research.google.com/drive/1ydIe8pwFbkEXouW0onIdxesj2uvgwD8r?usp=sharing. 

Would this be something worth supporting?

**Comment by jheek** [comment]
What to do with a partially applied module constructor is ambiguous.

Because you can also do something like this:
```
class Model(nn.Module):
  dtype: Any = jnp.float32

  def setup(self):
    self.conv = functools.partial(nn.Conv, kernel_size=(3, 3), dtype=self.dtype)

  @nn.compat
  def __call__(self, x):
    x = self.conv(32)(x)
    x = self.conv(32)(x)
    return x
```

so using partial to create a "template" from which you create multiple instances.

**Comment by avital** [comment]
@jheek why is that ambiguous? Wouldn't you expect that to create two different `nn.Conv` submodules?

...oh, I see. That's precisely your point. That if we attach names to "partial modules" during `setup`, then they can't be used more than once with the semantics of "create new module instances" in a `nn.compact` method.

I guess in @rolandgvc's example, the answer is to choose one of the following options:

1.
```py
class Model(nn.Module):
  train: bool = False
  dtype: Any = jnp.float32

  def setup(self):
    self.conv_block = ConvBlock(32, train=self.train, dtype=self.dtype, kernel_size=(3, 3), strides=(2, 2))

  def __call__(self, x):
    return self.conv_block(x)
```

2.
```py
class Model(nn.Module):
  train: bool = False
  dtype: Any = jnp.float32

  def __call__(self, x):
    conv_block = functools.partial(ConvBlock, train=self.train, dtype=self.dtype)
    return self.conv_block(32, kernel_size=(3, 3), strides=(2, 2))(x)
```

@rolandgvc -- what do you think? Looking at it again, it's not clear to me what the benefit was in your original code snippet in separating part of the attributes in `setup` and the rest in `__call__`. Or maybe this was part of a larger example that would better demonstrate the issue?

**Comment by rolandgvc** [comment]
At first thought I was thinking that defining a module's partial in `setup` would act more like a promise, allowing its later initialization in `__call__`. To my mind, this would have allowed us to define the `conv_block` partial once in setup but every instance during `__call__` would have behaved as a instantiation in `setup`, if that makes sense. A use-case for this would be when we want to use `setup` and have a large number of blocks with minor differences (say kernel sizes). This would allow us to write only the partial in `setup` and define/instantiate them in `__call__` while still having the benefits of using `setup`.

**Comment by avital** [comment]
In that case I think you could achieve what you're going for by using `functools.partial` in `setup` and then /also/ wrapping `__call__` with `nn.compact`.

**Comment by avital** [comment]
Basically what @jheek suggests.

**Comment by rolandgvc** [comment]
I see now, I missed his example. Thanks!

**Comment by marcvanzee** [comment]
Closing this issue since @rolandgvc's question seems to be resolved.
