### ISSUE TITLE
Flax is not compatible with jax.jvp

### ISSUE THREAD

**Issue by nestordemeure** [google/flax#580]
What is the recommended way to compute a [forward-mode Jacobian-vector product](https://jax.readthedocs.io/en/latest/jax.html#jax.jvp) for a Flax model ?

I can use Jax `grad` function without problem:

```
loss_value, loss_grad = jax.grad(loss_fn)(optimizer.target)
``` 

But calling `jvp` fails as the `target` member of the optimizer is a `Model` and not a jvp compatible type:

```
jax.jvp(loss_fn, optimizer.target, optimizer.target)
...
TypeError: primal and tangent arguments to jax.jvp must be tuples or lists; found Model and Model.
```

To give more context, the forward-mode Jacobian-vector product is needed to implement the [AdaHessian optimizer](https://github.com/amirgholami/adahessian).

**Comment by jheek** [comment]
`jax.jvp` uses a slightly different syntax. You must pass a tuple of arguments that is passed to loss function so:
`jax.jvp(loss_fn, (optimizer.target,), (optimizer.target,))` is what you intended here.

**Comment by nestordemeure** [comment]
Thank you, I just plugged your fix into my code and it works (hopefully I will put a Flax version of AdaHessian online this weekend)!
