### ISSUE TITLE
example/wmt broken by passing dict as static arg to jitted function

### ISSUE THREAD

**Issue by daniter-cu** [google/flax#587]
Provide as much information as possible. At least, this should include a description of your issue and steps to reproduce the problem. If possible also provide a summary of what steps or workarounds you have already tried.

In file flax/examples/wmt/train.py function create_model marks arg "model_kwargs" as a static arg but static args must be immutable and hashable [at least as of cc8fe15 on JAX main branch]. (see: jax/api.py:jit(...) doc string).

```
@functools.partial(jax.jit, static_argnums=(1, 2, 3))
def create_model(key, input_shape, target_shape, model_kwargs):
```

### Problem you have encountered:
Error is thrown: 
ValueError: Non-hashable static arguments are not supported. An error occured while trying to hash an object of type , {'vocab_size': 32000, 'output_vocab_size': 32000, 'emb_dim': 1024, 'num_heads': 16, 'num_layers': 6, 'qkv_dim': 1024, 'mlp_dim': 4096, 'max_len': 256, 'share_embeddings': True, 'logits_via_embedding': True}. 

The error was:
TypeError: unhashable type: 'dict'

### Steps to reproduce:
Whenever possible, please provide a *minimal example*. Please consider submitting it as a Colab link.
Reproduce by running examples/wmt exactly as instructed.

Workaround:
model_kwargs just needs to be hashable so you can convert the dict to a tuple. Pass the tuple to the jitted function and then convert it back to a dict inside the create_model function.

**Comment by jheek** [comment]
cc @levskaya 

Thanks for pointing out this issue!

One solution here would be to use `flax.core.FrozenDict`  which is an immutable dict and with a hash.

Jax recently made jit more strict requiring hashable static argnums. I'll do a quick run through the examples to see if others examples might be affected
