### ISSUE TITLE
nn.capture_module_outputs equivalent in Linen

### ISSUE THREAD

**Issue by rolandgvc** [google/flax#619]
Currently, `nn.capture_module_outputs` has no direct equivalent in the Linen API. It would be great to have this function brought over as well. It's specifically useful in transfer learning when dealing with backbones.

**Comment by avital** [comment]
I believe @jheek agrees that we should prioritize this. @jheek -- do you think you'll get around to implementing or alternatively you could write up a short design doc and we can mark this as "pull requests welcome"?

**Comment by bastings** [comment]
+1 to prioritizing this. We have a project for which it would be super useful :)

**Comment by avital** [comment]
@bastings -- would a pattern like the one proposed in https://github.com/google/flax/blob/2eb7b985d0abc5a6b78b4cbd22409cb4fe496d69/docs/howtos/extracting_intermediates.rst#store-intermediate-values-in-a-new-variable-collection work for you? You would have to clone a model definition.

**Comment by jheek** [comment]
Fixed in https://github.com/google/flax/pull/1043
