### ISSUE TITLE
Make `ModelParamTraversal` more public?

### ISSUE THREAD

**Issue by lucasb-eyer** [google/flax#62]
`ModelParamTraversal` is currently somewhat hidden within `optim`. But it is much more generally useful, for example for implementing weight-decay (not as a loss) or weight standardization or spectral norm (I think).
So it seems like putting it in `traverse_util.py` (where I'd look for it) would make sense.

**Comment by AlexeyG** [comment]
Sorry for a late reply @lucasb-eyer . This is a good proposal. Would you like to give it a shot and submit a PR? Perhaps we could move it out of optim, but keep backwards compatibility to re-exporting again in `optim`?

**Comment by lucasb-eyer** [comment]
Currently super stretched on finishing multiple projects, so won't be able to get to it anytime in the next few weeks, sorry.

**Comment by marcvanzee** [comment]
I'll give this one a try.

**Comment by marcvanzee** [comment]
I'm removing myself from this issue again since I didn't find time to work on it, so if anyone would like to give this a try, please go ahead!
