### ISSUE TITLE
Fix PyType for nn.Module

### ISSUE THREAD

**Issue by Marvin182** [google/flax#620]
Internally Google uses PyType to check Python types. PyType fails to recognize that Linen nn.Module instances are dataclasses and that the `setup` method might add additional attributes. This results in many errors from PyType (attribute-error, wrong-arg-count, wrong-keyword-args). I disabled these for several examples on the file level. This should only be temporary workaround until the fix is available. Mypy doesn't seem affected.

**Comment by levskaya** [comment]
This issue should hopefully be resolved by #1927 and the use of the standardized `dataclass_transform` decorator... closing for now.
