### ISSUE TITLE
Organize requirements for examples

### ISSUE THREAD

**Issue by Marvin182** [google/flax#623]
Some of our examples have additional dependencies (tensorflow_text for WMT, pillow for PixelCNN). Currently we define these in 3 locations:
- [tests_requires in the setup.py](github.com/google/flax/blob/master/setup.py#L35)
- examples/requirements.txt
- Some examples define their own requirements in linen_examples/<example>/requirements.txt.

Should we converge on a single place for requirements in examples?

Our BUILD workflow installs the the test_requires.
The other 2 locations are currently ignored in our tests.

**Comment by andsteing** [comment]
I think we should have it both in `setup.py tests_require` (for automated tests) and in `linen_examples/{example}/requirements.txt` (so the example directory is self contained; i.e. it should also contain the `flax` dependency)

And get rid of `linen_examples/requirements.txt`

**Comment by 8bitmp3** [comment]
+1 @Marvin182 @andsteing thank you

**Comment by yashkhasbage25** [comment]
Hi I wish to contribute to flax. Since this is labeled as "good first issue". Shall I take up this?

**Comment by andsteing** [comment]
- `test_requires` has been removed from `setup.py`
- `examples/requirements.txt` doesn't exist anymore
- as per #1726 examples' `requirements.txt` can now be updated with less pain
