### ISSUE TITLE
Pytype attribute generics tracker

### ISSUE THREAD

**Issue by jheek** [google/flax#656]
Pytype currently doesn't support Generic types class attributes:
```
class Foo:
  bar: T
```

As a workaround we use `Any` for the attribute instead. This workaround should be reverted once the functionality is implemented

**Comment by avital** [comment]
@jheek  -- Is there a public bug we can reference tracking the current limitation in pytype?

**Comment by marcvanzee** [comment]
@jheek is this still relevant?

**Comment by jheek** [comment]
Yes we are still using this workaround
