### ISSUE TITLE
Carefully rename `linen_examples/` -> `examples/`

### ISSUE THREAD

**Issue by avital** [google/flax#658]
Make sure to catch all references to `linen_examples`, including in publicly linked documents (like in `flax/linen/README.md`).

**Comment by avital** [comment]
This is the last remaining way that people accidentally start using `flax.nn` so we should do this soon. The one issue is that we haven't ported LM1B yet. The easiest thing is to keep an `examples/lm1b/deprecated` directory with the `flax.nn` implementation until we have some way to train LM1B in Linen -- either as a standalone example, or as a configuration option for the WMT example as @levskaya has been suggesting.

**Comment by jheek** [comment]
I think lm1b also uses a deprecated tokenizer? I guess it would stop working anyway?

**Comment by andsteing** [comment]
IIRC @levskaya mentioned recently that he would refactor the `wmt` example so it can also be used as a `lm1b` LM.

so moving to `.../deprecated` and then deleting once `wmt` is updated SGTM

**Comment by levskaya** [comment]
Yeah I'm porting and combining lm1b into wmt example right now to minimize pointless code duplication (it just results in two training loop implementations in the example vs cloning all the modeling code).  It's pretty far along I just need to test a bunch of stuff.

**Comment by Marvin182** [comment]
From my side it would be good to make this change this week. I don't plan to submit any changes to the examples (that could create merge conflicts).

**Comment by avital** [comment]
OK. I will probably just re-make this PR with the most recent changes indeed in the next few days.

**Comment by avital** [comment]
Done.
