### ISSUE TITLE
Port Annotated MNIST to Linen

### ISSUE THREAD

**Issue by avital** [google/flax#659]
Port the [annotated MNIST example](https://github.com/google/flax/blob/master/docs/annotated_mnist.md) to the new Linen API.

Then add it to Read The Docs, and fix the currently broken link from the MNIST Colab

**Comment by 8bitmp3** [comment]
Hi @avital 👋 Are you looking for assistance with porting flax.nn annotated examples to Linen?

**Comment by avital** [comment]
Yes @8bitmp3! Would you like to port the annotated MNIST example?

**Comment by 8bitmp3** [comment]
Sure @avital Do you prefer the Markdown-only format? I think the JAX team uses a Jupyter notebook-to-html extension that yields stuff like https://jax.readthedocs.io/en/latest/notebooks/quickstart.html

**Comment by avital** [comment]
We also have that plugin installed but I prefer the markdown only version here because that allows you to interleave text /within/ a single function, not just between functions.

**Comment by 8bitmp3** [comment]
Ok 👍 @avital I can create a "Jupytext" Markdown version which we can edit during the review

**Comment by avital** [comment]
Awesome! Please take a look at the former annotated MNIST linked to from the top comment on this issue for inspiration (people really liked that; perhaps it could be improved but to first order probably the right thing)

**Comment by 8bitmp3** [comment]
Sounds good @avital, that's the plan. I'm combining the original annotated MNIST [tutorial](https://flax.readthedocs.io/en/latest/annotated_mnist.html) with the Flax Linen [example](https://github.com/google/flax/blob/master/examples/mnist/mnist_lib.py) (under `/flax/examples/mnist/`). And for one-hot encoding, we could do what the Haiku team did in its MNIST [example](https://github.com/deepmind/dm-haiku/blob/master/examples/mnist.py) and use the ready-made [`jax.nn.one_hot`](https://jax.readthedocs.io/en/latest/_modules/jax/_src/nn/functions.html#one_hot) function.

**Comment by avital** [comment]
Yes jax.nn.one_hot sounds like a good idea!

**Comment by avital** [comment]
Hi @8bitmp3 -- just checking if you are looking at this. I'd love to see this in, one of us could do it instead if you're too busy.

**Comment by 8bitmp3** [comment]
Hey @avital 👋 Thanks for checking in. It's been a week of NeurIPS2020 😆. I'll show you what I got real soon, can open as a WIP PR 👍

**Comment by avital** [comment]
#764 closes this. Thanks again @8bitmp3!

**Comment by 8bitmp3** [comment]
@avital Let's also move it into RTD and ensure it appears in a good place in the ToC as per your suggestion here: https://github.com/google/flax/pull/764#issuecomment-769284045

**Comment by avital** [comment]
sounds good @8bitmp3 -- so to be clear, will you be opening a new PR moving the annotated MNIST example into RTD?

**Comment by 8bitmp3** [comment]
@avital I think I should experiment with porting optimizers to DeepMind's Optax first as per https://github.com/google/flax/issues/1053 👍

**Comment by andsteing** [comment]
The updated [annotated MNIST][(https://flax.readthedocs.io/en/latest/notebooks/annotated_mnist.html) example is using `flax.linen` and `optax`.

So closing this issue (also created #1621).
