### ISSUE TITLE
Linen modules should be frozen

### ISSUE THREAD

**Issue by jheek** [google/flax#674]
Currently we don't enforce linen Modules to be frozen after setup. However, this should be the case because Module instances need to be clone-able to work correctly. `__setattr__` should refuse to set attributes after setup is finished.

Update:

Actually there are more sharp edges that can be fixed by freezing correctly.
Currently we accept lists and dicts of sub modules which are registered on assignment. But we can actually freeze them to avoid this common trap:

```
def setup(self):
  self.sub_modules = [Dense()]
  self.sub_modules.append(Dense())
```

We could avoid this by making sub_modules is stored as a tuple and similarly we can avoid the same issue with dicts by transforming them into a FrozenDict

**Comment by avital** [comment]
Marking as "pull requests welcome" if anyone wants to take a look at it. This change will help avoid possible footguns for users.
