### ISSUE TITLE
Run mypy in run_all_tests.sh

### ISSUE THREAD

**Issue by avital** [google/flax#688]
Ideally we want both type checkers to work correctly at least for the library. Also mypy should offer a speedup

_Originally posted by @jheek in https://github.com/google/flax/discussions/685#discussioncomment-140141_

**Comment by marcvanzee** [comment]
I am closing this issue since we haven't followed up on it on 1.5 year.

**Comment by marcvanzee** [comment]
One

**Comment by marcvanzee** [comment]
Sure, done!
