### ISSUE TITLE
Write "Flax Team Principles" doc

### ISSUE THREAD

**Issue by avital** [google/flax#689]
Inspired by https://overreacted.io/what-are-the-react-team-principles/

For example:
* happy to own complexity in core, to empower users
* built to harness JAX's strengths, expose the closest thing to raw JAX as possible for each situation
* our goal is first and foremost to serve our users and potential users
* willing to rethink best practices: we building for the future, let's not get too caught up on what's /currently/ considered standard.

**Comment by 8bitmp3** [comment]
@avital my 2 cents: I noticed that there's some good material in your team's _Linen: a comfortable refinement of FLAX_ doc. For instance, for `### Absorb the Complexity` (like in React):
> ... concise, readable code for the common case of simple layers
> ... familiar syntax
> ... lightweight classes

...all of which kind of revolves around researchers' UX. There're talk of flexibility (composable JAX transformations), functionality (➡️ `### UI Before API`).

**Comment by marcvanzee** [comment]
Closing this since we now have the Flax philosophy, which seems similar in spirit: https://flax.readthedocs.io/en/latest/philosophy.html
