### ISSUE TITLE
"Build" workflow too slow

### ISSUE THREAD

**Issue by Marvin182** [google/flax#697]
Our "Build" workflow now takes over 20min. This means that it takes over 20min to merge a pull request into the master. This is too long to iterate fast.
We should aim to get back down to 10-15min. Main contributors seem to be the tests in the linen_examples. I suggest that we change these to run <5min and also make sure that the example tests all run in parallel.

**Comment by avital** [comment]
See also #639

**Comment by avital** [comment]
#737 and #741 seems to have improved things. Looks like tests now take 11m15s (e.g. https://github.com/google/flax/actions/runs/474491706). And we'll soon be removing `examples/` (#801) which will make things even faster. So I think we can close this issue.
