### ISSUE TITLE
Single Device prefetch_to_device

### ISSUE THREAD

**Issue by n2cholas** [google/flax#709]
[`prefetch_to_device`](https://flax.readthedocs.io/en/latest/flax.jax_utils.html#flax.jax_utils.prefetch_to_device) is great when doing distributed training, but can be a hassle for non-pmap use cases since you need to add then remove a dummy sharding dimension at the front. A convenience function to prefetch data onto the device in single GPU training would be helpful.

Also, `prefetch_to_device` returns `ShardedDeviceArray`s instead of `DeviceArray`s. Is there a difference, or are the two interchangeable? Thanks in advance!

**Comment by avital** [comment]
Hi @n2cholas -- very sorry for the late reply! I'll rope in @jheek who has thought about this much more carefully.

**Comment by marcvanzee** [comment]
@jheek is this something we are still planning on doing?

**Comment by jheek** [comment]
I'll close this for now, users can already "prefetch" something to a single device using `jax.device_put`. The use case seems somewhat niche and prefetching is mostly handled automatically or manually through JAX APIs these days.

**Comment by davidshen84** [comment]
Hi @n2cholas ,

Do you have any working code that can use `prefetch_to_device` with single GPU? My dataset comes from TFDS and I am struggling with how to add the dummy dimmension for `prefetch_to_device`.

I created a [thread](https://github.com/google/flax/discussions/3869) here. I'd be much appreciated if you can share some experiences over there.

Thanks!

**Comment by n2cholas** [comment]
@davidshen84 after profiling a bit, I found that prefetching would not help much for my use case. Have you tried calling `.batch()` twice on your TFDS (first time with the batch size, second time with batch_size=1 i.e. 1 device)? e.g. https://github.com/n2cholas/progan-flax/blob/main/src/main.py#L41-L43
