### ISSUE TITLE
`Module.apply` should accept vanilla dictionaries for variables

### ISSUE THREAD

**Issue by avital** [google/flax#719]
Actually the current behavior is a bit strange I agree. We accept a dict of collections but the collections themselves have to be frozen.
It's a little stubborn if the api doesn't just accept a dict here. After all you can just freeze it and it will accept. The api should first freeze the deep-copy the dict before using it thought to avoid potential silent errors!

_Originally posted by @jheek in https://github.com/google/flax/discussions/715#discussioncomment-163338_

**Comment by marcvanzee** [comment]
This has been fixed alrady.
