### ISSUE TITLE
A flax module without trainable parameter changes the rng

### ISSUE THREAD

**Issue by MostafaDehghani** [google/flax#72]
In a flax module, I turned a function that applies a bunch of numpy operations to a flax (sub-)module that has no trainable parameter, e.g.:
```
def add(x, y):
  return x + y
```
to
```
@nn.module
def add(x, y):
  return x + y
```
I noticed that I get different numbers at the end. Seems this is because the submodule changes the random number generators by splitting the rng of the parent module, while this behaviour is not expected in this case.
Maybe it makes more sense to condition splitting the rng  on the existence of trainable parameters in the submodule?

**Comment by jheek** [comment]
hash based rngs fix this issue and a unit test was added in #77 that tests this particular edge case
