### ISSUE TITLE
Add Named Entity Recognition Example using Transformers

### ISSUE THREAD

**Issue by SauravMaheshkar** [google/flax#722]
### Description of the model to be implemented
I want to implement different variants of the [Transformer Architecture (Vaswani et al., 2017)](https://arxiv.org/abs/1706.03762) perhaps along with [Reformer](https://arxiv.org/abs/2001.04451) or [Performer](https://arxiv.org/abs/2009.14794) for Named Entity Recognition

### Dataset the model could be trained on

[Annotated Corpus for Named Entity Recognition](https://www.kaggle.com/abhinavwalia95/entity-annotated-corpus) published under Open Data Commons, [Database Commons License](https://opendatacommons.org/licenses/dbcl/1-0/) using GMB(Groningen Meaning Bank) corpus

### Reference implementations in other frameworks

1. [NER using Reformer](https://github.com/google/trax/blob/master/trax/examples/NER_using_Reformer.ipynb)
2. [Tensorflow: Bidirectional LSTMs](https://github.com/SauravMaheshkar/Named-Entity-Recognition-/blob/master/Named_Entity_Recognition.ipynb)

**Comment by avital** [comment]
Hi @SauravMaheshkar -- we generally don't accept new official flax/examples unless they cover an important new class of models, to make sure that Flax works well for those use-cases. We would love to see such a model, and would be happy to link to an external github repo from https://flax.readthedocs.io/en/latest/examples.html, feel free to file a pull requests against our docs to showcase your model!
