### ISSUE TITLE
Document common_utils.py and consider reorganizing them.

### ISSUE THREAD

**Issue by avital** [google/flax#729]
These utilities are helpful for many models, yet currently undocumented. It's worth also considering whether they should all live in one bucket "utils" file -- instead we could try to group different sets of utilities under a more explicitly grouped set of utilities (e.g. "replication")

**Comment by marcvanzee** [comment]
I'll take a look at this!

**Comment by marcvanzee** [comment]
Unassigning myself since I didn't do this and not planning to in the short term.
