### ISSUE TITLE
Consider "bound modules"/"interactive mode"

### ISSUE THREAD

**Issue by avital** [google/flax#750]
Currently, Flax modules are generally "unbound" -- they are just wrappers around attributes that expose purely functional methods. But we could easily support a `module.bound(variables)` method that returns a bound module on which you can call methods directly. The question is what to do with mutable collections, e.g. "batch stats".

Leaving this issue here to clarify intent, but the next step is to elaborate on some design constraints and proposals.

**Comment by marcvanzee** [comment]
I think @jheek implemented this, so seems we can close it?

**Comment by jheek** [comment]
Yes
