### ISSUE TITLE
Port checkpointing HOWTO off of old diff system

### ISSUE THREAD

**Issue by avital** [google/flax#783]
And instead, use a standalone doc with tests like in #771 

Here is the old (pre-Linen) HOWTO diff, for reference: https://github.com/google/flax/blob/master/howtos/diffs/checkpointing.diff

**Comment by marcvanzee** [comment]
I wonder if we really need this HOWTO. We are doing this in many of our examples, and I expect that if it is clear to anyone they will ask in Discussions. Did anyone ever ask this? I think it is actually a very clear part of Flax.

**Comment by avital** [comment]
Originally the idea was to use this to demonstrate the ease of "forking and adding behavior" but you're right -- people seem to have been able to figure it out from the examples and docs.

**Comment by marcvanzee** [comment]
Closing this since the old HOWTOs are lost :(
