### ISSUE TITLE
Port scheduled sampling HOWTO from old diff-based system

### ISSUE THREAD

**Issue by avital** [google/flax#787]
And instead, use a standalone doc with tests like in #771

Here is the old (pre-Linen) HOWTO diff, for reference:
https://github.com/google/flax/blob/master/howtos/diffs/scheduled-sampling.diff

**Comment by marcvanzee** [comment]
It appears the old howto branches are removed, and given that these HOWTOs we written pre-Linen, I don't see an easy way to add these. Also since we haven't acted on this in 1.5 I'm closing this issue.
