### ISSUE TITLE
Add links to fine-tuning examples (e.g., HuggingFace)

### ISSUE THREAD

**Issue by avital** [google/flax#789]
May be good to first resolve #686

**Comment by marcvanzee** [comment]
We could do BERT, although then we would have to implement the model. We could do something fun like fine-tuning on some comments of reddit or something like that.

Some useful resources:

- BERT model implementation by Nikita: https://github.com/nikitakit/flax_bert/blob/master/modeling.py
- GH Discussions: https://github.com/google/flax/discussions/927, https://github.com/google/flax/discussions/923

**Comment by avital** [comment]
I am not sure whether there's a Hugging Face JAX/Flax fine-tuning example yet but if so we can link to it. There's also https://github.com/rolandgvc/flaxvision. I think we should also consider an extremely simplified example as a HOWTO.

**Comment by andsteing** [comment]
https://github.com/google-research/vision_transformer/ is another fine-tuning example. I heard it will probably soon be ported to Linen. It also has a Colab that downloads pre-trained checkpoints and uses TPUs for fine-tuning.

**Comment by INF800** [comment]
> I am not sure whether there's a Hugging Face JAX/Flax fine-tuning example yet but if so we can link to it. There's also https://github.com/rolandgvc/flaxvision. I think we should also consider an extremely simplified example as a HOWTO.

There are numerous fine-tuned examples from hugging face community day challenge. May be we can use them?

**Comment by INF800** [comment]
> I am not sure whether there's a Hugging Face JAX/Flax fine-tuning example yet but if so we can link to it. There's also https://github.com/rolandgvc/flaxvision. I think we should also consider an extremely simplified example as a HOWTO.

Can we add one among numerous examples from HF community day challenge

**Comment by marcvanzee** [comment]
I agree @INF800. I changed the title saying we should simply link to existing fine-tuning examples. It seems unnecessary to me to add a new fine-tuning HOWTO, given that so many exist already now.

**Comment by andsteing** [comment]
For your reference: I recently added a link to a fine-tuning example here: ad6a4aedb9b78a5a445426901072d9785329f468

**Comment by marcvanzee** [comment]
Closed after #1926, which contains a link to HuggingFace in our examples README. There are currently >5,000 JAX models in HuggingFace so it seems a bit excessive to link to all of them.
