### ISSUE TITLE
Declare linen submodule in dataclass-style?

### ISSUE THREAD

**Issue by chris-tng** [google/flax#818]
Hi all,

First of all, thank you for your work on flax. This is not an issue but a question.

As a pytorch user, sometimes I want to create a submodule, then pass it as an attribute to another module. This is quite common because people want to have flexibility about how to pick submodules and assemble them into the model. For instance:

```python
dummy = Dummy()
bigdummy = BigDummy(dummy = dummy)
init_vars = bigdummy.init(rngkey, x)
```

the modules are defined as

```python
class Dummy(nn.Module):
  def setup(self):
    self.dense = nn.Dense(4)

  def __call__(self, x):
    return self.dense(x)

class BigDummy(nn.Module):
  dummy: Dummy

  def setup(self):
    self.proj = nn.Dense(6)

  def __call__(self, x):
    return self.proj(self.dummy(x))
```

However, this fails at `bigdummy.init` for attribute access `bigdummy.dummy` because it doesn't run `dummy.setup`. I guess this has to do with how `flax` overrides `__setattr__`. So I'm wondering is there any way that `flax` supports this use case?

Thank you in advance!

Environment: flax 0.3

**Comment by avital** [comment]
Hi @chris-tng -- this is unfortunate and indeed clearly is a surprising and bad user experience. I wonder if we can find a clean way to fix this generally and still preserve some of the guarantees we currently have, and this may interact with  #686 (which will be a pretty serious change), so I'm not sure off the top of my head what the full solution is.

In the meanwhile, here's a workaround that seems to work -- it uses `__setattr__` and creates a new `Dummy` instance in `setup`.

```
class BigDummy(nn.Module):
  dummy_fn: Dummy

  def setup(self):
    self.dummy = self.dummy_fn()
    self.proj = nn.Dense(6)

  def __call__(self, x):
    return self.proj(self.dummy(x))

bigdummy = BigDummy(dummy_fn = lambda: Dummy())
```

what do you think?

**Comment by chris-tng** [comment]
Hi @avital ,

Thanks for your reply. Indeed, it's working

```python
bigdummy = BigDummy(dummy_fn = lambda: Dummy())
```

Personally, I find this is a bit hacky not a great user experience, since I find myself passing around "big" module like 

```python
model = BART(
  generator_fn = lambda: BERT(
    # huge parameter declaration
    # what if submodule
    encoder = lambda: Encoder(
      # param declaration
    )
  )
  discriminator_fn = lambda: GPT(
    # huge parameter declaration
  )
)
```

If we have many hierarchy of modules, this makes the code hard to read with many nesting functions.

I skim through the proposal in #686  , the idea is appealing to me. It would be great to have `setup()` fires immediately in module construction. 

I'm looking forward to the change in #686 . I guess this issue can be closed then?

**Comment by avital** [comment]
Let's not close this issue just yet -- I'd like for whoever works on #686 (probably me or @jheek) to keep this use-case in mind.

I agree this is suboptimal. It may be solvable separate from #686.

**Comment by levskaya** [comment]
@chris-tng @avital this has been a commonly cited pain-point, and I've tried to remedy it with PR #864 - I believe your example should work fine with this change.  (For the record I don't think this is actually so related to #686 - that's more of an interactive use-case question of inspecting instantiated parameters, etc.  whereas this is simply wanting to define modules made from simpler ones at the top-level following the common pytorch pattern.)

**Comment by relational** [comment]
I have tested the example above and can confirm it works now:
```
class Dummy(nn.Module):
  def setup(self):
    self.dense = nn.Dense(4)

  def __call__(self, x):
    return self.dense(x)

class BigDummy(nn.Module):
  dummy: Dummy

  def setup(self):
    self.proj = nn.Dense(6)

  def __call__(self, x):
    return self.proj(self.dummy(x))

dummy = Dummy()
bigdummy = BigDummy(dummy = dummy)
init_vars = bigdummy.init(jax.random.PRNGKey(0), jnp.zeros((5,5))
print(jax.tree_multimap(lambda p: p.shape, init_vars))
```
prints out:
```
FrozenDict({
    params: {
        dummy: {
            dense: {
                bias: (4,),
                kernel: (5, 4),
            },
        },
        proj: {
            bias: (6,),
            kernel: (4, 6),
        },
    },
})
```

However, it breaks if I try to give `dummy` a name:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-137-e3f2b17ce457> in <module>()
      1 dummy = Dummy(name="my_dummy")
      2 bigdummy = BigDummy(dummy = dummy)
----> 3 init_vars = bigdummy.init(jax.random.PRNGKey(0), jnp.zeros((5,5)))

9 frames
/usr/local/lib/python3.7/dist-packages/flax/linen/module.py in init(self, rngs, method, *args, **kwargs)
    956       The initialized variable dict.
    957     """
--> 958     _, v_out = self.init_with_output(rngs, *args, method=method, **kwargs)
    959     return v_out
    960 

/usr/local/lib/python3.7/dist-packages/flax/linen/module.py in init_with_output(self, rngs, method, *args, **kwargs)
    935       rngs = {'params': rngs}
    936     return self.apply(
--> 937         {}, *args, rngs=rngs, method=method, mutable=True, **kwargs)
    938 
    939   def init(self, rngs: Union[PRNGKey, RNGSequences], *args,

/usr/local/lib/python3.7/dist-packages/flax/linen/module.py in apply(self, variables, rngs, method, mutable, capture_intermediates, *args, **kwargs)
    912         method, self,
    913         mutable=mutable, capture_intermediates=capture_intermediates
--> 914     )(variables, *args, **kwargs, rngs=rngs)
    915 
    916 

/usr/local/lib/python3.7/dist-packages/flax/core/scope.py in wrapper(variables, rngs, *args, **kwargs)
    673               **kwargs) -> Union[Any, Tuple[Any, VariableDict]]:
    674     with bind(variables, rngs=rngs, mutable=mutable).temporary() as root:
--> 675       y = fn(root, *args, **kwargs)
    676     if mutable is not False:
    677       return y, root.mutable_variables()

/usr/local/lib/python3.7/dist-packages/flax/linen/module.py in scope_fn(scope, *args, **kwargs)
   1133     _context.capture_stack.append(capture_intermediates)
   1134     try:
-> 1135       return fn(module.clone(parent=scope), *args, **kwargs)
   1136     finally:
   1137       _context.capture_stack.pop()

/usr/local/lib/python3.7/dist-packages/flax/linen/module.py in wrapped_module_method(*args, **kwargs)
    269     _context.module_stack.append(self)
    270     try:
--> 271       y = fun(self, *args, **kwargs)
    272       if _context.capture_stack:
    273         filter_fn = _context.capture_stack[-1]

<ipython-input-136-6ac56c731ead> in __call__(self, x)
     13 
     14   def __call__(self, x):
---> 15     return self.proj(self.dummy(x))
     16 
     17 dummy = Dummy()

/usr/local/lib/python3.7/dist-packages/flax/linen/module.py in wrapped_module_method(*args, **kwargs)
    269     _context.module_stack.append(self)
    270     try:
--> 271       y = fun(self, *args, **kwargs)
    272       if _context.capture_stack:
    273         filter_fn = _context.capture_stack[-1]

<ipython-input-136-6ac56c731ead> in __call__(self, x)
      4 
      5   def __call__(self, x):
----> 6     return self.dense(x)
      7 
      8 class BigDummy(nn.Module):

/usr/local/lib/python3.7/dist-packages/flax/linen/module.py in __getattr__(self, name)
    530     else:
    531       raise AttributeError(
--> 532           f'"{self.__class__.__name__}" object has no attribute "{name}"')
    533 
    534   def __dir__(self) -> List[str]:

AttributeError: "Dummy" object has no attribute "dense"
```
(Tested with jax==0.2.11 jaxlib==0.1.64 flax==0.3.3 )

**Comment by marcvanzee** [comment]
@jheek it seems we can close this now since @levskaya's change seems to have fixed it, or was there something else you still were planning to do?

**Comment by levskaya** [comment]
@relational - sorry about that and thanks for noticing this edge-case.  #1201 is an attempt to fix it.  

I note that we fix it by _ignoring_ the name given to the outer submodule.  In Flax we try to follow a "single unique namespace" policy for the flax submodule tree, specifically: if you're attaching a new, unattached submodule to a self attribute, it will use that attribute name as its name.  So to follow that policy in this case, we have to ignore any outer name for "outside" modules.

**Comment by levskaya** [comment]
Please feel free to re-open the issue if you have more thoughts or concerns, given the existing fixes for bookkeeping's sake I'm going to close it for now.
