### ISSUE TITLE
typos in mnist example 

### ISSUE THREAD

**Issue by murphyk** [google/flax#828]
I have some very small suggestions for cosmetically improving this example:
https://github.com/google/flax/blob/master/linen_examples/mnist/train.py

- line 31, 122: onp -> np

- line 55: `init_shape = jnp.ones((1, 28, 28, 1), jnp.float32)` is not a shape tuple, it's a tensor of data.
Consider renaming to `init_val' or `input_val`.

- line 131. ` eval_model(model, test_ds):`. The model argument is actually the dict of parameters, not a module.
Consider renaming to params to be consistent with eval_step.

**Comment by avital** [comment]
This will be fixed by #829
