### ISSUE TITLE
ONNX support

### ISSUE THREAD

**Issue by DiffeoInvariant** [google/flax#834]
Hi Flax devs--I would like to be able to convert Flax models to and from ONNX (my group is considering using Flax as our default neural network library, but we need to be able to convert our models to ONNX). I found a template for converting ONNX to XLA at https://github.com/google/jax/blob/master/examples/onnx2xla.py, but I couldn't find any indication that Flax models can be converted to ONNX. Is this likely to be supported by Flax any time in the near future?

**Comment by jheek** [comment]
It's unclear to me at this point whether there's anything to gain from adding ONNX support at the Flax level.
Once Jax support a transformation to ONNX, All Flax models should be supported as well.

As your example indicates there has at least been some effort to support onnx -> XLA in Jax. The reverse shouldn't be too difficult either.
You could also use the more indirect Jax -> tf -> onnx. The jax2tf work is still experimental but actively developed at the moment (see: https://github.com/google/jax/tree/master/jax/experimental/jax2tf).
