### ISSUE TITLE
Mutable / Unmutable state when training

### ISSUE THREAD

**Issue by GJBoth** [google/flax#844]
Hi Flax team,

I'm working on a model with an internal state which gets updated during training. When calling the model during validation, I do not want to update these variables. I could technically introduce a training variable, but I feel it could be more elegantly (and much simpler!) by simply checking if a state is mutable:

1 ) Is there an easy way to check if a variable is mutable, so that my code only updates when it is? e.g.
`if is_initialized and var.is_mutable(): var.value = f(....)`
2 ) If I set mutable=False, I only get back the output. Is there a way to get back the state regardless? e.g.
`output, updated_state = model.apply(inputs, mutable=False, return_state=True)`
My usecase is that for my validation metrics I call my loss function with the testdata and extract the metrics, so that I can use the same code for both training and validation.

Thanks!

**Comment by jheek** [comment]
The code for this is already there it is just not exposed as an API. This will be pretty easy.

We decided not to return state that isn't updated. the reasoning is that it becomes easy to accidentally store the same variables twice or return a copy of variables from a compiled function that you don't need.

**Comment by GJBoth** [comment]
I'd be happy to give it a try and implement / write an example if you could give me some pointers; I couldn't find anything in the source code when I looked at it though...

Alright, I understand, but still a shame. Adding a keyword also goes against the design?

**Comment by avital** [comment]
Hi @GJBoth take a look at the discussion we're having on #845
