### ISSUE TITLE
Improve Error Message: Naming a module in setup

### ISSUE THREAD

**Issue by marcvanzee** [google/flax#847]
The error `TypeError: Module instance is frozen outside of setup method.` is thrown  at any time you assign module attributes somewhere other than within setup. It is not always clear to users how to resolve this.

-- Example 1

This code
```
def setup(self):
  self.layer = nn.Dense(...)
  self.layer.name = 'dense'
```

Throws the error `TypeError: Module instance is frozen outside of setup method.`, which confuses users.

-- Example 2
See: #936

**Comment by marcvanzee** [comment]
Similarly, users can be confused about the error message `ValueError: In setup, assign names of Modules via self.<name> and not using keyword argument name="<name>"`. We should provide a more elaborate error message with an example.

**Comment by avital** [comment]
A bit more color here:

For submodules defined in-line within a `@nn.compact` method, you either explicitly pass names to submodules via a `name` argument to the submodule constructor, or they are automatically generated if not, e.g.:

```py
# ... inside a module
@nn.compact
def func(self, x):
  dense1 = Dense(features=16)  # submodule name autoassigned to "Dense1"
  dense2 = Dense(features=16, name='final')  # submodule name is "final"
```

For submodules defined inside `setup`, names are always explicit and are derived from the name of the attribute on which they are assigned (via `__setattr__`, following a very similar logic to that of PyTorch):
```py
# ... inside a module
def setup(self):
   self.final = Dense(features=16)  # submodule name is "final"
```

**Comment by marcvanzee** [comment]
This issue is very closely related to #524.

**Comment by avital** [comment]
In short, as summarized by @salayatana66, "really in `setup` the attribute name is the name of the module."
