### ISSUE TITLE
Write design note for nn.transforms

### ISSUE THREAD

**Issue by marcvanzee** [google/flax#867]
Currently it is difficult to understand this code, and how to use it. We should either improve the documentation or write some tutorial explaining how the transforms work. Some things that can be explained (collected from user chats):

- Give an example of how to wrap a function with `transforms.scan`.
- Explain how to (or maybe support) transforming instances.
- Explain better what `transforms` does, which is difficult to understand since it interacts with `core.lift` in non-trivial ways.
- In order to apply a method of an instance over a batch, and supposing that module has no state variables, is it safe to use `jax.vmap` instead of `transforms.vmap`?

If we end up writing a tutorial, it would be good to improve the error messages around transforms and link to the tutorial. E.g. the error `ValueError: Jax transforms and modules cannot be mixed.` can be improved.

**Comment by marcvanzee** [comment]
@levskaya I'm assigning this to you since I think you mentioned once you were planning to write such a note. Feel free to assign to someone else or clarify here why it is no longer needed.

**Comment by avital** [comment]
We now have this here: https://flax.readthedocs.io/en/latest/design_notes/lift.html, so I think a first version of this is done, but perhaps there are improvements we can make?

**Comment by marcvanzee** [comment]
Closing this since Anselm write a guide (see comment Avital above).
