### ISSUE TITLE
Add HOWTO: Early Stopping

### ISSUE THREAD

**Issue by marcvanzee** [google/flax#886]
Based on https://github.com/google/flax/pull/711

**Comment by avital** [comment]
Copying content from the duplicate #1239:

We recently merged #711, which gives a simple non-(inversion of control) API for early stopping in a user-defined training loop.

It would be good to showcase a HOWTO with side-by-side diffs like in https://flax.readthedocs.io/en/latest/howtos/lr_schedule.html showcasing how this would be integrated into a real (sample) training loop.

**Comment by INF800** [comment]
Anyone working on this? I can send a PR.

**Comment by avital** [comment]
@INF800 not that I know of, want to give it a shot?

**Comment by marcvanzee** [comment]
@INF800 I assigned it to you, thanks for helping! Feel free to send me the PR once it is done.

**Comment by INF800** [comment]
Thankyou. Picking up the task now.

**Comment by INF800** [comment]
@marcvanzee added the `docs/howtos/early_stopping.rst` file *manually*. Is it the right way of doing things?

**Comment by INF800** [comment]
This test (https://github.com/google/flax/pull/1528/checks?check_run_id=3548808026) is failing as I tried to use `.. codediff::`.

**Comment by avital** [comment]
@INF800 -- yes the docs actually run their code to make sure it runs correctly. you can use testsetup:: if you need to initialize things at the top that aren't defined in the code, but we mostly use that for imports. You probably want to get your code in the codediff:: (specifically the right hand side, which is what's tested) to run without failures. You can also run tests locally, see docs/README.md

**Comment by avital** [comment]
In your case perhaps you can add a testsetup:: block with `num_epochs = 10` to get the code to run...?

**Comment by INF800** [comment]
> @INF800 -- yes the docs actually run their code to make sure it runs correctly. you can use testsetup:: if you need to initialize things at the top that aren't defined in the code, but we mostly use that for imports. You probably want to get your code in the codediff:: (specifically the right hand side, which is what's tested) to run without failures. You can also run tests locally, see docs/README.md

I notices that `testsetup::` actually hides it's code contents, so added the variables there along with a dummy training function.

After building the html files, I am not seeing link to my page in left side navigation pannel. Should I make changes somewhere?

**Comment by marcvanzee** [comment]
Closing this since the PR fixing this does not seem to have any activity (#1528), and we actually have a minimal example in the docstring for early stopping now.
