### ISSUE TITLE
Improve Documentation: Clarify when to use np and jnp

### ISSUE THREAD

**Issue by marcvanzee** [google/flax#904]
The [JAX for the impatient](https://flax.readthedocs.io/en/latest/notebooks/jax_for_the_impatient.html) doc compare onp with jnp but doesn't explain when to use which. Some notes from users:

- Is it supposedly better to use onp instead of jnp for 'trivial' computations on shapes? Yes. It avoids compiling and excuting shape computations on device
- It is always better to use np for shape computations.

**Comment by myagues** [comment]
google/jax#5426 will probably cover most of the general cases.

**Comment by marcvanzee** [comment]
Thanks for pointing this out @myagues! That guide looks very good so I'm closing this issue.
