### ISSUE TITLE
4x slowdown in evaluation of RBM (Flax.linen vs jax.experimental.stax)

### ISSUE THREAD

**Issue by PhilipVinc** [google/flax#912]
Provide as much information as possible. At least, this should include a description of your issue and steps to reproduce the problem. If possible also provide a summary of what steps or workarounds you have already tried.

### Problem you have encountered:
I compare a simple implementation of an RBM with flax against a similar implementation with `Jax.experimental.stax`. See [this gist notebook](https://gist.github.com/PhilipVinc/24d7e46abe6a6edd72293f63803b4f09) . 

The two produce the same `jaxpr` code when traced, so I would expect comparable performance (minus dispatch cost and time taken to flatten/unflattne the inputs and outputs), but that is not the case, and flax has a 4x disadvantage.

Essentially, the two implementations are
```python
stax.serial(stax.Dense(alpha * L), stax.Sigmoid, SumLayer)
```
and
```python
class FlaxRBM(nn.Module):
    dtype: Any = np.float32
    alpha: int = 1
    use_bias: bool = True

    @nn.compact
    def __call__(self, x):
        x = nn.Dense(
            name="Dense",
            features=self.alpha * x.shape[-1],
            dtype=self.dtype,
            use_bias=self.use_bias,
        )(x)
        x = nn.activation.sigmoid(x)
        return jnp.sum(x, axis=-1)
```
What I observe is peculiar:
```python
# alpha=1
# Input shape (1,1) 

# jax
63.3 µs ± 247 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

# flax
252 µs ± 7.65 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
which would suggest that flax has a 4x times the dispatch cost of jax (weird... but ok). 

Still, if I increase the size:
```python
# alpha=3
# Input shape (32,20) 

# jax
69.5 µs ± 4.92 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

# flax
280 µs ± 31.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
We finally overcome the dispatch cost, but flax runtime increases too?

```python
# alpha=6
# Input shape (128,30) 

# jax
116 µs ± 8.51 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

# flax
407 µs ± 83.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
???

I also checked that the two produced the same jaxpr, which is indeed the case
```python
jax.make_jaxpr(j_ma.apply)(j_w, x)
{ lambda  ; a b c.
  let d = dot_general[ dimension_numbers=(((1,), (0,)), ((), ()))
                       precision=None ] c a
      e = broadcast_in_dim[ broadcast_dimensions=(1,)
                            shape=(1, 180) ] b
      f = add d e
      g = sign f
      h = mul f g
      i = mul h -2.0
      j = exp i
      k = add j 1.0
      l = log k
      m = add h l
      n = log 2.0
      o = sub m n
      p = reduce_sum[ axes=(1,) ] o
  in (p,) }
```

```python
jax.make_jaxpr(f_ma.apply)(f_w, x)
{ lambda  ; a b c.
  let d = dot_general[ dimension_numbers=(((1,), (0,)), ((), ()))
                       precision=None ] c b
      e = broadcast_in_dim[ broadcast_dimensions=(1,)
                            shape=(1, 180) ] a
      f = add d e
      g = sign f
      h = mul f g
      i = mul h -2.0
      j = exp i
      k = add j 1.0
      l = log k
      m = add h l
      n = log 2.0
      o = sub m n
      p = reduce_sum[ axes=(1,) ] o
  in (p,) }
```

I have `jax==v0.2.8` and `flax==v0.3.0`

**Comment by jheek** [comment]
Python is surprisingly slow indeed. We don't actually spend much time trying to improve the dispatch overhead of Flax because of 2 reasons:
1) Jax & XLA itself have very significant overhead when running op by op.
2) Flax has zero runtime overhead when the model is compiled using jit or pmap because Flax is only touched when the function is compiled but not when it runs.

As you pointed out the JaxPRs are the same so compiling this function will result in the same binary being produced.

We don't want Flax to be excessively slow such that it takes a significant amount of time to debug something in op-by-op or it would take up a significant part of the compilation phase in this example I don't think that is the case.

**Comment by PhilipVinc** [comment]
I was aware that Jax & Xla have significant overheads, and I expect Flax to add to that overhead, so I was not surprised to see a higher overhead for flax.

However, I expect this overhead to be constant with respect to the size of the problem, do you agree? if I increase the size of the matrices, the overhead should not change.

I measured above that Jax/Stax has an overhead of about `60` microseconds, while flax is around `250`.

But that is not what I measured: In the last set of measurements, the Jax/Stax module has a double runtime (meaning that we finally overcome jax overhead, but flax is increasing too. How is that possible?

**Comment by avital** [comment]
Putting aside the specifics here, you should always use `jax.jit`. Is there
still a performance difference then?

**Comment by jheek** [comment]
It's not obvious to me how to interpret the measurements. One thing to keep in mind is that Jax is async which makes interpreting the timings harder. The python overhead overlaps with the computation itself so as long as python stays ahead in scheduling the ops you don't measure any overhead.

**Comment by PhilipVinc** [comment]
Yes it's all jitted. The exact call is this:

```python
@partial(jax.jit, static_argnums=0)
def apply_fun(ma, w, x):
    return ma.apply(w, x)

%timeit _ = apply_fun(j_ma, j_w, x).block_until_ready()
%timeit _ = apply_fun(f_ma, f_w, x).block_until_ready()
```
(I wrap jax modules in a class that exposes the apply)

**Comment by jheek** [comment]
Oops I missed the jit. I was assuming op-by-op execution. So in that case this is strange

**Comment by PhilipVinc** [comment]
Hmm, I'm not sure I follow.
If I do operations on tiny array, what I am measuring should be mainly the `python` cost, that is... `flattening`, `un-flattening`, checking the cache for a method already compiled and dispatching to that method, right? So that's exactly a measurement of the overhead. 

It only happens once because the function is jitted.

Check the updated gist. I went to large sizes of 
```
#input :(2048, 40), alpha=6

# jax
656 µs ± 60 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
#flax
865 µs ± 24.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

and there is still an edge in using jax.

**Comment by PhilipVinc** [comment]
Ah, wait, that's consistent: Flax adds 200 microseconds to the dispatch overhead. It is always ~200 microseconds

**Comment by PhilipVinc** [comment]
Interesting.
On jax's repo I saw the developers (mainly @mattjj ) mention several times that their overhead for jit-calls is around 70 microseconds. Here I measure something around 60, which is consistent.

It would seem that lax adds ~200 microseconds, for a total of ~250 microseconds dispatch cost. 

Might I ask what are you doing that adds so much? If I call reapeatedly the jitted functions with the same pytrees (only changing another input which is simply a jnp.array) is there something I can do to reduce this cost?

I know that this is not an issue in traditional ML workflows, but it is an issue for us/me working in Quantum Mechanics where we try to run a MCMC sampling where thee RBM model gives the acceptance probability.
We cannot always put the whole sampler under `jax.jit` because sometimes the way we propose moves for the MCMC chain involves code that does not fit jax programming style (I think).
While for big networks that's not an issue, we still work a lot with what you guys would call small networks.

We where thinking about transiting [netket](https://github.com/netket/netket) to jax/flax but that is indeed I need to figure out before doing it...

**Comment by jheek** [comment]
Strange actually you aren't really touching much of Flax at all. The first arg is just a function that will be hashed and used to cache the jitted function, that's completely up to Jax. The only part of Flax you touch is the FrozenDict but you actually used that in the other snippets as well and I measured to overhead in this case to be 2 microseconds. In the end you are jitting the same function so the overhead should be identical

**Comment by PhilipVinc** [comment]
I'm not even jitting. I'm just calling something that is already jitted.

Even, I'd expect flax to be faster because `FrozenDict` stores it's hash after computing it once.

**Comment by jheek** [comment]
Yes that's what I would expect as well. You also use the FrozenDict in the other cases so it can't really make a difference. The only difference I can see is that the paramater structure is different between the 3 versions. This shouldn't result in a huge difference though. Within the frozen dicts there are only tuples and dicts which are all handled by the C++ implementation of Jax.

**Comment by jheek** [comment]
Here is a version using the Jax model that is just as slow as the flax version:

```
@jax.jit
def g(f_w, x):
  j_w = flax.core.FrozenDict({'params': [(f_w['params']['Dense']['kernel'], f_w['params']['Dense']['bias']), (), ()]})
  return j_ma.apply(j_w, x)

%timeit _ = g(f_w, x).block_until_ready()
```

I'm surprised that dictionary structure in Flax is so much more expensive here especially because the Stax model has all these useless empty tuples. This is outside the scope of Flax though so you would have to open a Jax ticket to see if the performance can be improved.

**Comment by PhilipVinc** [comment]
`f_w` is the flax model, not the jax one.
(`j_` is a jax model without flax whatsoever, `w_` is a jax model wrapped in a `nn.Module`, which has performance comparable to `j_` and `f_` is my `RBM(nn.Module)` implementation)

And you are converting to a FrozenDict inside the jitted function, so after jitting that code is never executed. 

Since I believe only the arguments to the outmost jitted function matter, I believe that your `g` funtion  is equivalent to calling `j_ma.apply(j_w, x)` under a jit.

**Comment by PhilipVinc** [comment]
Upon inspecting the execution under a sampling profiler (py-spy) I see the following traces.

jax and wrap_jax give similar traces. However, they are very different from flax...
Curiously, they are very different.

It seems that flax hits `cache_miss` continuously. however he is not re-jitting the function so I don't really know what is going on.
I'll try to migrate this issue to jax's repo.

```
➜ sudo py-spy top -- python wrap_test.py

Collecting samples from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python wtest.py' (python v3.8.5)
Total Samples 800
GIL: 0.00%, Active: 100.00%, Threads: 1

  %Own   %Total  OwnTime  TotalTime  Function (filename:line)
  8.00% 100.00%   0.620s     6.45s   <module> (wtest.py:126)
  0.00%  92.00%   0.040s     6.19s   reraise_with_filtered_traceback (jax/_src/traceback_util.py:139)
 86.00%  86.00%    5.33s     5.84s   f_jitted (jax/api.py:395)
  0.00%   0.00%   0.000s    0.800s   _load_unlocked (<frozen importlib._bootstrap>:671)
  0.00%   0.00%   0.000s    0.800s   _find_and_load (<frozen importlib._bootstrap>:991)
  0.00%   0.00%   0.090s    0.800s   _call_with_frames_removed (<frozen importlib._bootstrap>:219)
  0.00%   0.00%   0.000s    0.800s   exec_module (<frozen importlib._bootstrap_external>:783)
  0.00%   0.00%   0.000s    0.800s   _find_and_load_unlocked (<frozen importlib._bootstrap>:975)
  0.00%   0.00%   0.000s    0.780s   _handle_fromlist (<frozen importlib._bootstrap>:1042)
  0.00%   0.00%   0.000s    0.670s   <module> (wtest.py:2)
  0.00%   0.00%   0.000s    0.380s   cache_miss (jax/api.py:286)
  0.00%   0.00%   0.010s    0.380s   bind (jax/core.py:1235)
  0.00%   0.00%   0.000s    0.370s   _xla_call_impl (jax/interpreters/xla.py:576)
  0.00%   0.00%   0.000s    0.370s   call_bind (jax/core.py:1226)
  0.00%   0.00%   0.000s    0.370s   process (jax/core.py:1238)
  0.00%   0.00%   0.000s    0.370s   memoized_fun (jax/linear_util.py:251)
  0.00%   0.00%   0.000s    0.370s   _find_and_load_unlocked (<frozen importlib._bootstrap>:961)
  0.00%   0.00%   0.000s    0.370s   process_call (jax/core.py:598)
  0.00%   0.00%   0.000s    0.330s   <module> (wtest.py:118)
  0.00%   0.00%   0.000s    0.330s   build_JaxModel (wtest.py:81)
  0.00%   0.00%   0.310s    0.310s   backend_compile (jax/interpreters/xla.py:349)
  0.00%   0.00%   0.000s    0.310s   exec_module (<frozen importlib._bootstrap_external>:779)
  0.00%   0.00%   0.000s    0.290s   <module> (jax/__init__.py:94)
  0.00%   0.00%   0.000s    0.280s   <module> (jax/scipy/__init__.py:18)
  0.00%   0.00%   0.000s    0.280s   init (wtest.py:32)
  0.00%   0.00%   0.000s    0.280s   <module> (jax/_src/nn/functions.py:24)
  0.00%   0.00%   0.000s    0.280s   <module> (jax/nn/__init__.py:20)
  0.00%   0.00%   0.000s    0.280s   <module> (jax/scipy/signal.py:17)
  0.00%   0.00%   0.000s    0.280s   <module> (jax/_src/scipy/signal.py:15)
  0.00%   0.00%   0.000s    0.260s   init_fun (jax/experimental/stax.py:295)
  0.00%   0.00%   0.000s    0.250s   init_fun (jax/experimental/stax.py:52)
  0.00%   0.00%   0.000s    0.220s   <module> (jax/__init__.py:22)
  0.00%   0.00%   0.000s    0.200s   _xla_callable (jax/interpreters/xla.py:723)
  0.00%   0.00%   0.190s    0.190s   _compile_bytecode (<frozen importlib._bootstrap_external>:580)
  0.00%   0.00%   0.000s    0.190s   get_code (<frozen importlib._bootstrap_external>:911)
  2.00%   3.00%   0.070s    0.180s   f_jitted (jax/api.py:378)
  0.00%   0.00%   0.000s    0.150s   <module> (jax/__init__.py:92)
  0.00%   0.00%   0.000s    0.150s   <module> (jax/image/__init__.py:18)
  0.00%   0.00%   0.000s    0.140s   <module> (scipy/signal/__init__.py:299)
  0.00%   0.00%   0.000s    0.140s   <module> (scipy/signal/filter_design.py:17)
  0.00%   0.00%   0.000s    0.130s   <module> (wtest.py:4)
```

```
➜ sudo py-spy top -- python flax_test.py

Collecting samples from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python ftest.py' (python v3.8.5)
Total Samples 2800
GIL: 0.00%, Active: 100.00%, Threads: 1

  %Own   %Total  OwnTime  TotalTime  Function (filename:line)
  2.00% 100.00%   0.300s    26.62s   <module> (ftest.py:126)
  0.00%  98.00%   0.020s    26.42s   reraise_with_filtered_traceback (jax/_src/traceback_util.py:139)
  9.00%  97.00%    2.12s    25.96s   f_jitted (jax/api.py:395)
  1.00%  73.00%   0.210s    19.86s   cache_miss (jax/api.py:286)
  1.00%  72.00%   0.260s    19.65s   bind (jax/core.py:1235)
  0.00%  62.00%   0.110s    16.74s   call_bind (jax/core.py:1226)
  0.00%  62.00%   0.020s    16.40s   process (jax/core.py:1238)
  1.00%  62.00%   0.170s    16.37s   process_call (jax/core.py:598)
  2.00%  55.00%   0.290s    13.92s   _xla_call_impl (jax/interpreters/xla.py:579)
  0.00%  35.00%   0.240s     8.08s   _execute_compiled (jax/interpreters/xla.py:836)
  0.00%  35.00%   0.120s     7.84s   <genexpr> (jax/interpreters/xla.py:836)
  0.00%  33.00%   0.150s     7.58s   device_put (jax/interpreters/xla.py:127)
  0.00%  21.00%   0.120s     5.34s   _device_put_device_array (jax/interpreters/xla.py:1302)
 11.00%  11.00%    4.04s     4.04s   _execute_compiled (jax/interpreters/xla.py:837)
  0.00%  17.00%   0.060s     3.89s   _force (jax/interpreters/xla.py:1341)
 17.00%  17.00%    3.83s     3.83s   force_fun (jax/interpreters/xla.py:1373)
  2.00%   6.00%   0.200s     2.26s   _xla_call_impl (jax/interpreters/xla.py:576)
  0.00%  12.00%   0.020s     2.08s   _device_put_device_array (jax/interpreters/xla.py:1301)
  1.00%   2.00%   0.590s     1.07s   memoized_fun (jax/linear_util.py:246)
  0.00%   3.00%   0.070s     1.02s   cache_miss (jax/api.py:274)
  0.00%   3.00%   0.130s     1.01s   _execute_compiled (jax/interpreters/xla.py:839)
  3.00%   5.00%   0.570s    0.990s   _copy_device_array_to_device (jax/interpreters/xla.py:1314)
  0.00%   0.00%   0.000s    0.800s   _find_and_load (<frozen importlib._bootstrap>:991)
  0.00%   0.00%   0.000s    0.800s   _find_and_load_unlocked (<frozen importlib._bootstrap>:975)
  0.00%   0.00%   0.000s    0.800s   exec_module (<frozen importlib._bootstrap_external>:783)
  0.00%   0.00%   0.200s    0.800s   _call_with_frames_removed (<frozen importlib._bootstrap>:219)
  0.00%   0.00%   0.000s    0.800s   _load_unlocked (<frozen importlib._bootstrap>:671)
  0.00%   0.00%   0.000s    0.800s   _handle_fromlist (<frozen importlib._bootstrap>:1042)
  0.00%   2.00%   0.010s    0.790s   call_bind (jax/core.py:1220)
  0.00%   0.00%   0.000s    0.730s   <module> (ftest.py:2)
  0.00%   3.00%   0.040s    0.650s   cache_miss (jax/api.py:277)
  0.00%   1.00%   0.090s    0.620s   _force (jax/interpreters/xla.py:1342)
  3.00%   3.00%   0.560s    0.610s   tree_flatten (jax/tree_util.py:68)
  0.00%   2.00%   0.050s    0.570s   _force (jax/interpreters/xla.py:1332)
  3.00%   3.00%   0.530s    0.530s   __init__ (jax/interpreters/xla.py:1080)
  0.00%   3.00%   0.030s    0.520s   call_bind (jax/core.py:1225)
  0.00%   3.00%   0.140s    0.500s   _copy_device_array_to_device (jax/interpreters/xla.py:1329)
  0.00%   1.00%   0.110s    0.500s   make_device_array (jax/interpreters/xla.py:1042)
  4.00%   4.00%   0.490s    0.490s   is_trivial (jax/lazy.py:133)```

**Comment by marcvanzee** [comment]
Blocked by google/jax#5485

**Comment by levskaya** [comment]
_Tempore omnia vulnera sanabuntur_

I wanted to re-check the results here given how much work has gone on in JAX this year concerning dispatch overheads.

Across the board JAX dispatch times are down -a lot-.  The overhead of using flax vs stax is now extremely slight in dispatch-sensitive tests (lots of tiny launches) and non-existent on any reasonably large computation.

on my macbook, small setting:
- `6.81 µs ± 198 ns` STAX vs `7.81 µs ± 195 ns` FLAX  (old numbers were `65µs` vs `255µs`!)
-  ~`1.14x` now vs ~`4x`, and a 10x absolute improvement in dispatch!

on my macbook, larger setting:
- `304 µs ± 23 µs` STAX vs `308 µs ± 42.8 µs` FLAX (old numbers were `410µs` vs `603µs`!)
- ~`1.x` now vs ~`1.5x`

I reran all the benchmarks on colab cpu and my macbook cpu, results here:
https://colab.research.google.com/drive/1mPa51aFSK_NOSOi3USrLu-GnqOlh-LDX?usp=sharing

So I believe for all practical purposes this issue is resolved, and will mark this issue closed.  Please feel free to re-open if you have further concerns here though!
