### ISSUE TITLE
Respecting input dtype

### ISSUE THREAD

**Issue by jheek** [google/flax#915]
Currently we use a default `dtype=float32` in the standard layer implementations.
We would like to switch this to something more closely resembling numpy semantics.
This means the default is `dtype=None` and in this case the input dtype is respected.

Some layers might have multiple inputs in which case determining the output dtype is less straightforward.
In this case the docstring of the module should explicitly mention how the dtype resolution works.

**Comment by PhilipVinc** [comment]
Is dtype only about the type used for calculation or it will also influence the dtype of the parameters?

Related: #805 
When you make the switch please keep in mind us poor people stuck with complex numbers.

**Comment by jheek** [comment]
@PhilipVinc  Please take a look at the default dtype proposal https://github.com/google/flax/pull/1776 which should fix your complex number use case among other things
