### ISSUE TITLE
[Doc] Missing doc for ConvTranspose

### ISSUE THREAD

**Issue by Conchylicultor** [google/flax#972]
I was fairly surprised to not found a conv transpose op on flax: https://flax.readthedocs.io/en/latest/flax.linen.html#linear-modules.
After investigation, it seems that the operation exists in the code, but do not appear on the doc.

https://github.com/google/flax/blob/b112b1128bd275bc5380b8370887f3c791209712/flax/linen/linear.py#L290

Is it expected ?

**Comment by marcvanzee** [comment]
No, that isn't expected, thanks for catching this! I will add it soon.

**Comment by joaogui1** [comment]
I believe this can be closed: [docs](https://flax.readthedocs.io/en/latest/_autosummary/flax.linen.ConvTranspose.html?highlight=convtranspose)
