### ISSUE TITLE
Improve "No parameter named ... exists ..." error when not passing in a variable collection in `Module.apply`

### ISSUE THREAD

**Issue by avital** [google/flax#977]
Originally reported by @jessicayung -- With the following code:

```py
class Recurrent(nn.Module):
  """A simple recurrent model."""
  ...
  @nn.compact
  def __call__(self, batch_input, verbose=False):
    ...
    user_outputs_matrix = self.variable('lstm_states','user_outputs', jnp.zeros,(self.num_users, self.features))
    ...

Recurrent().apply({'params': params}, batch)
```

one gets the following error:
```
ValueError: No parameter named "user_outputs" exists in "/".
```

The error can be clarified, e.g. "no collection named `"lstm_stats"` passed in -- check the variables passed in to `Module.apply`".

Follow #957 for guidelines for how to create new error classes and documentation for a better user journey once hitting the error.

Also consider, in the doc for this new error class, linking to a not-yet-existent "design note" about variable collections (see #780)

**Comment by marcvanzee** [comment]
Interesting, when I run the following code:

```python
class Recurrent(nn.Module):
  """A simple recurrent model."""
  ...
  @nn.compact
  def __call__(self):
    user_outputs_matrix = self.variable('lstm_states','user_outputs', jnp.zeros,(8, 4))
    return user_outputs_matrix

params = Recurrent().init({'params': jax.random.PRNGKey(0), 'lstm_states': jax.random.PRNGKey(0)})
Recurrent().apply({'params': params})
```

I get a different error: 

```
ValueError: No Variable named "user_outputs" for collection "lstm_states" exists in "/".
```

In any case, we can still improve this. I think it should say something about how this could happen. So here it should explain that this error can occur if you are trying to access a variable that does not exist in the passed params, which can happen if you forget to pass it to `Module.apply()`.
