### ISSUE TITLE
Readthedocs search slow

### ISSUE THREAD

**Issue by marcvanzee** [google/flax#978]
We've heard from different users that readthedocs search is slow. Please reply to this issue if you are experiencing this as well.

Copying a discussion with @cccntu on #932 here (I removed the content there since the discussion was about something else):

@cccntu said:

" I think it's slow in general from my experiences with different packages on RTD. But right now search seems to take forever. (the 'search...' has been running for several minute now.)
Here are some string I just tried: 'BatchNorm', 'FrozenDict', 'dense', 'compact'
(My internet speed is ~100Mbps rn.)

Here is the link produced by using the search box for dense
https://flax.readthedocs.io/en/latest/search.html?q=dense&check_keywords=yes&area=default"

@marcvanzee said:

" I've heard similar complaints from @apaszke from the JAX team as well, but I haven't experienced it myself (your queries are fast when I try it) and also heard from other Flax users they have no problems with it.

In any case, thanks for reporting it, we will see if this is something that occurs more often, and if so, how we can resolve it."

**Comment by cccntu** [comment]
Can confirm that's what I said.

Also wanted to update: I just tried again on my phone and it worked fine. (Didn't work on the same phone last time)

**Comment by marcvanzee** [comment]
Closing this since there haven't been any complaint for >9 months now.
